zh-cn/dynamic-programming-cn.html.markdown
=> [dynamic-programming/cn]Add Translation

perl6.html.markdown
=> [language/perl6] add much needed spacing with markdown headers

elixir.html.markdown
=> [elixir/en] Fix some missing double quotes in Agent section

solidity.html.markdown
References:
https://github.com/adambard/learnxinyminutes-docs/issues/2642
=> [solidity/en] Fixed misnamed contract initializer

fr-fr/rust-fr.html.markdown
=> [rust/fr]  "release" do not translate to "libération" in french in that case

es-es/kotlin-es.html.markdown, ko-kr/kotlin-kr.html.markdown, kotlin.html.markdown, zh-cn/kotlin-cn.html.markdown
=> [kotlin/all] Rename variable fooMutableDate to fooMutableData (#2688)

python3.html.markdown
property is exposed using setter and getters
=> [python/en] add underscore to property

clojure-macros.html.markdown
=> [clojure-macro] Update clojure-macros.html.markdown. Typo fixed

ru-ru/kotlin-ru.html.markdown
=> [kotlin/ru] kotlin-ru.html.markdown

ru-ru/kotlin-ru.html.markdown
=> [kotlin/ru]Ammended a typo in links

python.html.markdown
=> [python/en] Update my site's address

clojure.html.markdown
=> [clojure/en] Fix typo: "ans" should be "and"

ms-my/clojure-my.html.markdown
=> [clojure/ms-my] Add ms-my translation for Clojure

ms-my/clojure-my.html.markdown
=> [clojure/ms-my] Remove asterisks from code comments

zh-cn/go-cn.html.markdown
=> [go/zh-cn] Update content from English fork

awk.html.markdown
Added this tutorial for AWK. Seems an appropriate language for this format of tutorial. This is the first pull request I've ever made to any project, so I hope I did it right!
=> [awk/en] Added tutorial for AWK

LOLCODE.html.markdown
=> [LOLCODE/en] Create LOLCODE tutorial

python3.html.markdown
=> [python3/en] Some improvements to Python 3

java.html.markdown
=> [java/en-us] Fix typo

css.html.markdown
=> Traduje algunos parrafos de el archivo

fr-fr/fsharp-fr.html.markdown
---
I used a quite outdated version. I will update it later.  Also, I have a lot of internal issue to check. It is far from being ready.
=> [WIP][fsharp/fr] I just finish to translate the F# tuto to fr

zh-cn/jquery-cn.html.markdown
=> [jquery/zh-cn]add zh-cn for jquery

c.html.markdown
=> [language/c] Update c.html.markdown

hq9+.html.markdown
- [ \* ] PR touches only one file (or a set of logically related files with similar changes made)
- [ \* ] Content changes are aimed at _intermediate to experienced programmers_ (this is a poor format for explaining fundamental programming concepts)
- [ \* ] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ \* ] Seriously, look at it now. Watch for quotes and double-check field names.
=> [hq9+] Added manual for HQ9+ programming language

typescript.html.markdown
https://github.com/adambard/learnxinyminutes-docs/issues/2737
=> [typescript/en] Update typescript.html.markdown

c.html.markdown
=> [c/en-en] Make reference link in footer/summary link to Stack Overflow article

ca-es/go-ca.html.markdown, ca-es/kotlin-ca.html.markdown
=> [go/ca-es] catalan translation of Go

java.html.markdown
=> [Java/en] Fix small typo in Java English tutorial

shutit.html.markdown
=> [shutit/en] shutit added

cypher.html.markdown
nodes should be indicated with regular parenthesis `()`, some lines contained nodes within square brackets `[]`
=> [cypher/en] fixed node notation in cypher examples

vi-vn/python3-vi.html.markdown
Add Vietnamese translation for Python 3
=> [python3/vi-vn] Add Python 3 tutorial in Vietnamese

vi-vn/html-vi.html.markdown
Add Vietnamese translation for HTML
=> [html/vi-vn] Add HTML tutorial in Vietnamese

java.html.markdown
=> [en/java] Modify the Animal abstract class

zh-cn/standard-ml-cn.html.markdown
=> [sml/zh-cn] Chinese Translation for Standard ML

scala.html.markdown
- [n/a] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
=> [scala/en] fix anologus typo

haxe.html.markdown
Output:
My dog's name isfido, and his other favorite thing is a: teddy
New output:
My dog's name is fido, and his other favorite thing is a: teddy
=> [haxe/en] Fix typo

ca-es/kotlin-ca.html.markdown
=> Kotlin/ca-es: Fix typo

java.html.markdown
=> [java/en] typo

fr-fr/d.html.markdown
=> [d/fr] fix typo

elisp.html.markdown
the example boldified the color instead of colorizing them
=> [elisp/en] fix typo

ru-ru/nim-ru.html.markdown
=> [nim/ru] Translation Nim to russian

scala.html.markdown
Fixes #2759 with a translation from german to english.
=> [scala/en] Add traits in objects chapter

java.html.markdown
I proposed a few changes after discussion with @vendethiel [from the french translation pull request](https://github.com/adambard/learnxinyminutes-docs/pull/2762)
- Removed the second exemple on the switch statement related to the String type in Java 7
- Moved the typecasting section (about object casting) next to the ineritence section.
- Uncommented the code for Java 8 example about interface default method.
=> [java/en] few changes

es-es/amd-es.html.markdown
=> [amd/es-es] Replace 'Tópico' with 'Tema'

java.html.markdown
We could think we always had to use = with ?:
=> [java/en] adding an exemple to ternary operator ?:

fr-fr/ruby-ecosystem-fr.html.markdown
Only french and typo fixes.
The content might be outdated too: Ruby 2.5 instead of 2.0, TruffleRuby...
=> [ruby/fr_fr] french & typo fixes

fr-fr/ruby-fr.html.markdown
Fixed some French
Added more examples on:
- integer/float division
- interpolated strings
- multiline strings
Should I add the examples on the english version?
=> [ruby/fr-fr] more details, more examples

zh-cn/java-cn.html.markdown
=> fix wrongly written

red.html.markdown
=> [red/en] Fix logic in "either" examples

angularjs.html.markdown
Links are not clickable on https://learnxinyminutes.com/docs/angularjs/
=> [angular/en] Clickable links

php.html.markdown
=> [php/en] fix double language for arrays

standard-ml.html.markdown
=> [standard-ml/en] Use the correct identifier name

csharp.html.markdown
=> [csharp/en] Spelling mistake that threw me of while reading

es-es/go-es.html.markdown
=> [go/es] Fix typos

go.html.markdown
=> [go/en] Fix typo in Go comment

git.html.markdown
=> [git/en] Small improvements to git docs (including spelling/grammar and markdown formatting)

json.html.markdown
=> [json/en] Markdown fixup

pl-pl/bf-pl.html.markdown, pl-pl/haskell-pl.html.markdown, pl-pl/json-pl.html.markdown, pl-pl/perl-pl.html.markdown
Attempted to fix the messed-up frontmatter for Polish. See #2829.
=> [perl/pl] and other Polish files: Fixing the frontmatter

kotlin.html.markdown
Thank you for an amazing project, helped me learn Elixir and Kotlin in, well, y minutes 👍
=> [kotlin/en] Added print output for template string command

solidity.html.markdown
=> [solidity/en] Add version pragma

tcl.html.markdown
=> [tcl/en] Fixing typos

tr-tr/kotlin-tr.html.markdown
=> [kotlin/tr] kotlin turkish document

csharp.html.markdown
=> [csharp/en] C# 7 Feature Tuple

zh-cn/red-cn.html.markdown
=> [Red/zh-cn] Add Chinese translation of Red

pt-br/kotlin-pt.html.markdown
=> [pt-br/kotlin] pt-br translation and localization of kotlin en tutorial

perl6.html.markdown
did not render resp. markdown was not upped with it
=> [perl6/en] removed the vimformation

ruby.html.markdown
- [ww ] I solemnly swear that this is all original content of which I am the original author
- [ww ] Pull request title is prepended with `[language/lang-code]`
- [ww ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ww ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ww ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ww ] Yes, I have double-checked quotes and field names!
=> [ruby/en_us] Ruby has "methods" not "functions"

pt-br/solidity-pt.html.markdown
=> [Solidity/PT-BR] Full Translation

zh-cn/elisp-cn.html.markdown
The English version has a typo and is fixed by my previous PR
This changes Chinese translation accordingly
=> [elisp/zh-cn] Fix translation

fr-fr/asymptotic-notation-fr.html.markdown
=> [asymptotic-notation/fr] fr-fr translation for asymptotic-notation

es-es/awk-es.html.markdown, es-es/dynamic-programming-es.html.markdown
=> [awk/es-es] First version of spanish translation

es-es/tcl-es.html.markdown
=> [tcl/es-es] First version of the spanish translation

python.html.markdown
=> [python/en] Correct a variable name

edn.html.markdown
=> [edn/en] Improve initial description of EDN

de-de/scala-de.html.markdown
Hi,
I wanted to read the article but as I went on, I felt the urge to fix some typos and this what came out at the end.
Kind Regards,
Jonas
=> [scala/de] Scala: German translation reviewed.

asciidoc.html.markdown
=> [asciidoc/en] fixes #2644 add `Further Reading` section to AsciiDoc

standard-ml.html.markdown
Recently, the author of ML For The Working Programmer has released the text for free, and since there is already a reference to the book it makes sense to direct the reader to where they can read it online.
=> [sml/en] Add a link to ML For The Working Programmer

fr-fr/python3-fr.html.markdown
=> [python3/fr] Corrected some spelling mistakes and added an f-string example

es-es/asciidoc-es.html.markdown
A little note here.
I have opted for some minnor changes to make the text more natural to Spanish speakers, and use familiar terminology.
For instance, nested lists are called “multilevel lists” in Spanish, which is the name used in office suits.
=> [asciidoc/es-es] adds Spanish translation for AsciiDoc

fi-fi/go-fi.html.markdown
=> [go/fi] Fix typo

de-de/python3-de.html.markdown
brackets where missing for print in python3 de-de
=> [python3/de-de] fixed missing brackets for print

ca-es/asciidoc-ca.html.markdown
=> [asciidoc/ca] adds Catalan translation for AsciiDoc

bash.html.markdown
Addresses #549 by providing sample output of most of the echo commands, where appropriate and deterministic, and descriptive text for outputs elsewhere.
=> [bash/en] Provide example outputs for #549

haml.html.markdown
=> [haml/en] Add more information

bash.html.markdown
=> [bash/en] Fixed formatting for The Black Hole

it-it/matlab-it.html.markdown
=> [matlab/it-it] removed text left from the original translation

it-it/html-it.html.markdown
=> [html/it-it] adds Italian translation for html

java.html.markdown
=> [java/en] Add default keyword

java.html.markdown
=> added use of break keyword & new tutorial link

id-id/rst-id.html.markdown
=> [rst/id-id] Add Indonesian translation for RST

ca-es/groovy-ca.html.markdown, es-es/groovy-es.html.markdown, groovy.html.markdown, pt-br/groovy-pt.html.markdown, zh-cn/groovy-cn.html.markdown
It didn't make sense to add strings arithmetically, so I changed it into string concatenation.
<hr/>
=> [groovy/many] small fix in iteration over a map

fr-fr/java-fr.html.markdown
I started the french translation of Java from the english version. About 55% done.
I have translated all before "Classes And Functions".
=> [java/fr] -Create java-fr.html.markdown

pt-br/qt-pt.html.markdown
=> [qt/pt-br] Translation of Qt to pt-br.

de-de/swift-de.html.markdown, es-es/swift-es.html.markdown, pt-br/swift-pt.html.markdown, pt-pt/swift-pt.html.markdown, ru-ru/swift-ru.html.markdown, swift.html.markdown, tr-tr/swift-tr.html.markdown, zh-cn/swift-cn.html.markdown
=> [swift/many] Style guidelines

it-it/markdown.html.markdown
=> [markdown/it-it] Update structure and typo fix

smalltalk.html.markdown
=> [smalltalk/en] Fix some unclosed comments in the smalltalk documentation

nix.html.markdown
=> [nix/en] document using ? to test set membership

CHICKEN.html.markdown
RSR5 --> R5RS and RSR7 --> R7RS
Fixes #2803
=> [chicken/en] Fix typo in CHICKEN language

de-de/git-de.html.markdown
=> [git/de] add more commit examples

awk.html.markdown
=> [awk/en] fix for Local Variable in "arithmetic_functions"

git.html.markdown
=> [git/en] added signed commit example

forth.html.markdown
=> [Forth/en] Fix tuck definition

haxe.html.markdown
=> [haxe/en] minor typos

r.html.markdown
Fixes #2236 since it looked like it had gone unfixed for quite some time.
=> [r/en] Fix read.csv per #2236

nim.html.markdown
Fixes #2603 since it looked like it had gone unfixed for quite some time.
=> [nim/en] Add multi-line comments

it-it/rst-it.html.markdown
=> [rst/it-it] Italian translation for rst

vi-vn/typescript-vi.html.markdown
=> [typescript/vi-vn] Added Vietnamese translation for TypeScript language

de-de/nix-de.html.markdown
This translation is based on the English version.
=> [nix/de] Translate nix to german

de-de/edn-de.html.markdown
This translation is based on the english version.
=> [edn/de] Translate edn to german

de-de/qt-de.html.markdown
This translation is based on the english version.
=> [qt/de] Translate qt to german

de-de/pyqt-de.html.markdown
This translation is based on the english version.
=> [pyqt/de] Translate pyqt to german

python3.html.markdown
Addresses #2808 by adding a new section to [python3/en] addressing single inheritance, and modifies multiple inheritance section accordingly.
=> [python3/en] Add single inheritance section

whip.html.markdown
=> [whip/en] Add comment to separate functions categories

pt-br/c-pt.html.markdown
=> [c/pt-br] small typo

pt-br/c++-pt.html.markdown
=> [c++/pt-br] Small typos

pt-br/asymptotic-notation-pt.html.markdown
=> [asymptotic-notation/pt-br] Small typo

pt-br/asciidoc-pt.html.markdown
=> [asciidoc/pt-br] Small typo

pt-br/amd-pt.html.markdown
=> [amd/pt-br] Small typo

csharp.html.markdown
Added examples for using @ symbol with strings and interpolated strings
=> [csharp/en] Clarify use case for verbatim strings

zh-cn/go-cn.html.markdown
=> [go/zh-cn]Add brace

pt-br/awk-pt.html.markdown
No for this question, this is a translation
=> [awk/pt] Translate awk to pt_BR

de-de/edn-de.html.markdown
=> [edn/de] fixing typos

typescript.html.markdown
=> [typescript/en] Fix link to javascript docs

pt-br/javascript-pt.html.markdown
=> [javascript/pt-br] Small typo

pt-br/json-pt.html.markdown
=> [json/pt-br] Small typo

pt-br/java-pt.html.markdown
=> [java/pt-br] Small typo

pt-br/visualbasic-pt.html.markdown
=> [visualbasic/pt-br] Small typos

de-de/LOLCODE-de.html.markdown
=> [lolcode/de] Translation for LOLCODE

pt-br/whip-pt.html.markdown
NO, because this is a translation
=> [whip/pt-br] Translate whip to pt_BR

csharp.html.markdown
Add explanation and examples for delegates and events for issue #2314
=> [csharp/en] #2314 Add delegates and events to csharp/en

csharp.html.markdown
Added explanation and examples for tuples, deconstruction of tuples and other objects, and discarding unwanted fields during deconstruction
=> [csharp/en] Add topics for tuples to csharp/en

vi-vn/less-vi.html.markdown
=> [less/vi-vn] Added Vietnamese translation for Less

pt-br/csharp-pt.html.markdown
=> [csharp/pt-br] Small typos

pt-br/csharp-pt.html.markdown
=> [csharp/pt-br] Missing translation

pt-br/css-pt.html.markdown
=> [css/pt-br] Missing translation

pt-br/perl-pt.html.markdown
=> [perl/pt-br] Missing translation

pt-br/c-pt.html.markdown
=> [c/pt-br] Small typos

de-de/html-de.html.markdown, html.html.markdown
improved the content a little bit
=> [html/en,de] improved the content a little bit

java.html.markdown
=> Improve comment about final modifier

java.html.markdown
=> Improve comments on abstract classes

javascript.html.markdown
```
// Because those cases can cause unexpected results, we'll keep on using
// semicolons in this guide.
```
The guide says that semicolons would be used to avoid unexpected results, so I added semicolons to all lines that were missing them to keep consistent.
=> [javascript/en] Adding missing semicolons

vim.html.markdown
Adds a small blurb about `:help` to the vim documentation.  Also cleaned up whitespace.
=> [vim/en] Vim help docs

it-it/rst-it.html.markdown
=> [rst/it] Improve wording

it-it/go-it.html.markdown
=> [go/it] Wording and missing translation

pt-br/dynamic-programming-pt.html.markdown
=> [dynamic-programming/pt-br] - Better reading

pt-br/dynamic-programming-pt.html.markdown
=> [dynamic-programming/pt-br] - Small typos

csharp.html.markdown
Added pattern matching, reference locals and local functions under c#7 features
=> [csharp/en] Add more c#7 features

java.html.markdown
=> Improve TreeMap documentation

java.html.markdown
=> Improve arithmetic output

vi-vn/sass-vi.html.markdown
=> [sass/vi-vn] Added Vietnamese translation for Sass language

vi-vn/markdown-vi.html.markdown
=> [markdown/vi-vn] Added Vietnamese translation for Markdown language

python.html.markdown
=> [python/en] Add data type checking examples

javascript.html.markdown
=> [javascript/en] Add several usefull functions to work with arrays

crystal.html.markdown
=> [crystal/en] Update crystal.html.markdown

latex.html.markdown
Switched 'tumbnails' to 'thumbnails'
=> [LaTeX/en] Small typo

perl6.html.markdown
=> [perl6/en]: fix typo.

zh-cn/javascript-cn.html.markdown
=> [chinese/zh-cn] Update javascript-cn.html.markdown

typescript.html.markdown
=> [typescript/en] Fix naming of constant

java.html.markdown
https://github.com/adambard/learnxinyminutes-docs/issues/3038
=> [java/en] removing erronous statement about classes

fr-fr/crystal-fr.html.markdown
=> [crystal/fr] Corrected mistake

crystal.html.markdown
=> [crystal/en] Corrected mistake

c.html.markdown
This PR implements the recommendations documented in issue #3035. Thanks!
=> [c/en] Fixed and improved compiler flag recommendations

hu-hu/python-hu.html.markdown
=> [python/hu] Hungarian translation of Python entry

de-de/dynamic-programming-de.html.markdown
=> [dp/de] Translation for Dynamic Programming

lambda-calculus.html.markdown
=> [lambda-calculus/en] Added lambda calculus file

pt-br/latex-pt.html.markdown
=> [latex/pt] Translate latex to pt_BR

zh-cn/make-cn.html.markdown
mostly base on english version, adjust and add some examples,
also fix some targets that can't run.
=> [make/zh-cn] Chinese Version of GNU Make

nl-nl/html-nl.html.markdown
=> [html/nl-nl] Added dutch translation for html

bash.html.markdown
=> [bash/en] Add arrays and alias

php.html.markdown
for simplification purposes, use only one variant of namespace examples while learning about exceptions.
=> [en-en/php] unifies namespace variants in exception handling

tr-tr/css-tr.html.markdown, tr-tr/css.html.markdown
=> [CSS/TR]Turkish translate for CSS documentation

python3.html.markdown
=> [python3/en] Fix omitting in list and clarified comments

pascal.html.markdown
=> [Pascal/en] Add pascal language

standard-ml.html.markdown
Show an example of pattern-matching using the case expression.
=> [Standard ML/en] Add case expression to SML docs

sv-se/haskell-sv.html.markdown
=> [haskell/sv-se] initial

scala.html.markdown
Take, leave, or modify as desired!
Specifically:
* Acknowledge weirdness of no parameters in `foreach println`
* Mention what `Unit` is
* Clarify abstract comments
* Fix capitalization of George in example
* Explicitly introduce regex
* Re-iterate `s` in comments, it's gotten very separated
* Reword explanatory comment about `foreach`
=> [scala/en] A few editing improvements as I read through

sv-se/nix-sv.html.markdown
=> [nix/sv-se] initial

zh-cn/crystal-cn.html.markdown
=> [crystal/zh-cn] New Chinese translation

de-de/go-de.html.markdown
=> [go/de] Change array length from '4' to '3' in explanation

python3.html.markdown
=> [python3/en]: fix typo

python.html.markdown
=> [python/en]: fix typo

zh-cn/typescript-cn.html.markdown
=> [typescript/zh-cn] fix reference (#3040)

python3.html.markdown
=> Corrections on Python3 page

nix.html.markdown
=> [nix/en]: remove and update broken link

common-lisp.html.markdown
=> [common-lisp/en]: clean up and add more information

bf.html.markdown
=> Update name #2120

pt-br/c-pt.html.markdown
What?! I can't swear it. I'm just fixing some typos/translations!
=> [c/pt-br] small typo and better translated words

zh-cn/python3-cn.html.markdown
=> [zh-cn/python3] Reorder confusing comments

matlab.html.markdown
Conditional statements: in the original, if the second condition is tested, it's never true.
Method: as the comment states above the line: "the object does not need to be passed to the method"; and _cannot,_ to be precise.
=> matlab/en "Conditional statements" and "Method" update 

solidity.html.markdown
=> [solidity/en] Make event name consistent, remove trailing spaces

es-es/perl6-es.html.markdown
=> [perl6/es-es] Added Spanish translation for Perl 6

tr-tr/c++-tr.html.markdown, tr-tr/git-tr.html.markdown
=> C++/tr - Turkish translation for C++ education stuff.

ruby.html.markdown
=> [ruby/en] Various improvements to Ruby language doc

c.html.markdown
I think that this puts it more in line with the previous example and spares some confusion.
=> [C/en] Change bits to bytes

objective-c.html.markdown
=> [objective-c/en] Add missing block referred to in comment

tcl.html.markdown
Suggested by @loxaxs. Fixes #2912.
- [n/a] I solemnly swear that this is all original content of which I am the original author
=> [tcl/en] Workaround for broken syntax highlighting

de-de/python3-de.html.markdown
=> [python3/de] Fix a few typos

ruby.html.markdown
=> [Ruby/en] Fixed a typo

tr-tr/c++-tr.html.markdown, tr-tr/git-tr.html.markdown
=> [c++/tr] Fixed: Several typos

awk.html.markdown, es-es/awk-es.html.markdown, pt-br/awk-pt.html.markdown
I solemnly swear that this is all original content of which I am the original author
- [+] Pull request title is prepended with `[language/lang-code]`
- [+] Pull request touches only one file (or a set of logically related files with similar changes made)
- [+] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [+] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [+] Yes, I have double-checked quotes and field names!
=> [awk/en] Fix atan2 args order

julia.html.markdown
=> [julia/en-us] porting julia from 0.4  to 0.6.4

ro-ro/elixir-ro.html.markdown
=> [elixir/ro] Added Romanian translation for Elixir

lambda-calculus.html.markdown
- [-] I solemnly swear that this is all original content of which I am the original author
- [-] Pull request touches only one file (or a set of logically related files with similar changes made)
- [-] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [-] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [-] Yes, I have double-checked quotes and field names!
=> Add SKI, SK and Iota

fsharp.html.markdown
=> [fsharp/en] Fix sentence mistake

it-it/python3-it.html.markdown, ruby.html.markdown
=> [ruby/en-us][python3/it-it] Fix typos

asymptotic-notation.html.markdown
=> [docs/asymptotic-notation] Fix content error, closes #3006

julia.html.markdown
=> [julia/en] add comprehension filter example

python3.html.markdown
I indicate that a set doesn't contain duplicate elements and add a little example
=> Python3 Clarification about sets

citron.html.markdown
=> [Citron/en] pull request

go.html.markdown
=> clear up wording

bash.html.markdown
=> shebang updated

ro-ro/elixir-ro.html.markdown
=> [Elixir/ro] Add language label

es-es/learnsmallbasic-es.html.markdown
The final 404 error. I've gone through every link on the site and every one of them is functional now!
=> Fix build error in SmallBASIC (es-es)

ruby-ecosystem.html.markdown
Update info on major versions in common use
Move info on versions above info on version managers
=> [ruby-ecosystem] Update ruby-ecosystem.html.markdown

javascript.html.markdown
=> [javascript/en] add for/of loops

de-de/bash-de.html.markdown
Variable was not initialised in this stage for this loop - Removed the $
=> [bash/de] Update bash-de.html.markdown

fr-fr/dynamic-programming-fr.html.markdown
=> [Dynamic Programming/fr-fr] Fix typos

scala.html.markdown
Simple `a` vs `an` grammar correction
- [ X] I solemnly swear that this is all original content of which I am the original author
- [ X] Pull request title is prepended with `[language/lang-code]`
- [ X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [X ] Yes, I have double-checked quotes and field names!
=> [scala/en] Correct English a/an usage

java.html.markdown
=> [Java/en] Added Lambdas section.

pythonstatcomp.html.markdown
No semicolons needed in Python
=> Removed semicolons

solidity.html.markdown
=> [solidity/en] Fix dead link to style guide, mention Emacs mode

pythonstatcomp.html.markdown
Improve code by using context managers to handle closing of files.
Also, replace the flame-war indexing comment for one with some explanations to why things are as they are.
=> [pythonstatcomp/en] Improvements to syntax and comments

haskell.html.markdown
=> [haskell/en] tweaked tuple information to demonstrate wildcards and a more useful tuple function 

scala.html.markdown
Reverts adambard/learnxinyminutes-docs#2769
The information added there was misleading (see the comment) and I think it will confuse people.
=> Revert "[scala/en] Make return value example actually demonstrate issue"

moonscript.html.markdown
=> [moonscript/en] Created MoonScript markdown

montilang.html.markdown
=> [montilang/en] Add language MontiLang

it-it/matlab-it.html.markdown, matlab.html.markdown, pt-br/matlab-pt.html.markdown
Chinese version fixed in #3194
=> [Matlab/en, it-it, pt-br] Matlab all version fix

fr-fr/lambda-calculus-fr.html.markdown
=> [Lambda Calculus/fr-fr] Translation

processing.html.markdown
=> [processing/en] Add Language Processing

zh-cn/python3-cn.html.markdown
=> [Python3/zh-cn] fix typo

zh-cn/julia-cn.html.markdown
=> [Julia/zh-cn] Update from english version & update for Julia 1.0

julia.html.markdown
=> [Julia/en] Update output for Julia 1.0

zh-cn/swift-cn.html.markdown
update to swift 4.1 & fix typo
=> [Swift/zh-cn] update to swift 4.1

awk.html.markdown
=> [English/en] Update awk.html.markdown

fr-fr/pyqt-fr.html.markdown
Translation PyQt doc in french.
---
=> [PyQT/FR] Add french translation PyQT

zh-cn/c-cn.html.markdown
=> [C/zh-cn] Fix typos

zh-cn/awk-cn.html.markdown
=> [awk/zh-cn] translate awk to Chinese(zh-cn)

fr-fr/lambda-calculus-fr.html.markdown
=> Fix PR #3139

kotlin.html.markdown
=> [language/kotlin] Update kotlin.html.markdown

es-es/fsharp-es.html.markdown
New tutorial of F# in Spanish from Angel Arciniega
=> Add F# tutorial in Spanish

rust.html.markdown
The source code can be run by Rust Playground without warnings
=> The source code can be run by Rust Playground

ru-ru/rust-ru.html.markdown
Implement translation to Russian
=> Create traslation rust.html.markdown to Russian

fsharp.html.markdown
Add a note pointing out the use of single char "=" equality operator.
=> [fsharp/en] Add note on equality operator

common-lisp.html.markdown
=> [CommonLisp/en] fixed inconsistency between code and output value

de-de/git-de.html.markdown
=> [git/de] fixed small typos

vim.html.markdown
=> [vim/en] Added full screen movement for vim

ms-my/clojure-macros-my.html.markdown
=> [clojure-macros/ms-my] Added Malay translation for clojure macros

ms-my/common-lisp-my.html.markdown
=> [common-lisp/ms-my] Added Malay translation for Common Lisp

ms-my/elisp-my.html.markdown
=> [elisp/ms-my] Add Malay translation for Elisp

php.html.markdown
=> [php/en]: typo

es-es/erlang-es.html.markdown
traduction to language spanish
=> Learn Erlang in Spanish

pt-br/rust-pt.html.markdown
=> [rust/pt-br] Small typos

pt-br/vim-pt.html.markdown
=> [vim/pt-br] Small typos

pt-br/go-pt.html.markdown
=> [go/pt-br] Small typos

pt-br/bash-pt.html.markdown
=> [bash/pt-br] Small typo

pt-br/c++-pt.html.markdown
=> [c++/pt-br] Better translation

clojure.html.markdown
The previous name is considered rude by Brits
=> clojure/en Changed a name in a code example to make it British English-friendly

pt-br/css-pt.html.markdown
=> [css/pt-br] Translates `media queries` section to pt-br

pascal.html.markdown
=> [pascal/en] add functions/procedures

purescript.html.markdown
=> [purescript/en] fix array of ints/numbers

typescript.html.markdown
=> [typescript/en] Add Readonly Examples for Typescript

ruby.html.markdown
---
Fixes #3042 using existing comment plus some editing for clarity
=> [ruby/en] fixes #3042 (spring cleanup)

pascal.html.markdown
=> [pascal/en] add additional data types and arrays

textile.html.markdown
=> [textile/en] add textile #2994

rst.html.markdown
=> [rst/en] fix typo: tabless -> tables

elixir.html.markdown
=> [Elixir/en] - #2594 - Adds clarification for functions with multiple clauses.

lambda-calculus.html.markdown
=> [Lambda Calculus/en] - Closes #3114 - Fixes lambda calculus evaluation formula by fixing associativity

es-es/python3-es.html.markdown
=> [python3/es-es]  Fixed and enhanced for python 3 with Spanish language corrections

latex.html.markdown
=> [latex/en] Added a resource to read

pt-br/cmake-pt.html.markdown
=> [cmake/pt-br] Add portuguese language for cmake

it-it/jquery-it.html.markdown
=> [jquery/it-IT] Add italian language for jquery

it-it/pyqt-it.html.markdown
=> [pyqt/it-IT] Add italian language for pyqt

it-it/asciidoc-it.html.markdown
=> [asciidoc/it-IT] Add italian language for asciidoc

it-it/qt-it.html.markdown
=> [qt/it-IT] Add italian language for qt

nl-nl/dynamic-programming-nl.html.markdown
=> [dynamic-programming/nl-nl] Add Dutch language for dynamic-programming

it-it/toml-it.html.markdown
=> [toml/it] Add it-IT translation for TOML

opencv.html.markdown
=> [opencv/en]

it-it/ruby-it.html.markdown
=> [ruby/it] Translation of Ruby in Italian

cs-cz/javascript.html.markdown
=> [javascript/cz] improve wording, fix typos, add missing text from English original

fr-fr/markdown-fr.html.markdown
* Fix issue #2864
* Fix formatting
* Fix ruby code snippet
* Fix translation
* Add missing keyboard keys section
=> [Markdown/fr] Fix formatting & add missing keyboard keys section

c++.html.markdown
=> [c++/en] Addresses #3009, corrects C++ headers description

it-it/java-it.html.markdown
- Fix a typo
- Convert o' / e'/ u' to ò / è / ù
=> [java/it] Fix typos and accent marks

de-de/opencv-de.html.markdown
=> [opencv/de] Translate opencv to german

de-de/shutit-de.html.markdown
=> [shutit/de] Translate shutit to german

de-de/hq9+-de.html.markdown
=> [hq9+/de] Translate hq9+ to german

de-de/rst-de.html.markdown
=> [rst/de] Translate rst to german

de-de/paren-de.html.markdown
=> [paren/de] Translate paren to german

typescript.html.markdown
=> [typescript/en] Add example of "implements" keyword

nl-nl/vim-nl.html.markdown
=> [vim/nl-nl]Add Dutch Vim translation

pt-br/make-pt.html.markdown
=> [make/pt-br] Add portuguese language for make

pt-br/cypher-pt.html.markdown
=> [cypher/pt-br] Add portuguese language for cypher

c++.html.markdown
=> [c++/en] efficient typo fix

pt-br/factor-pt.html.markdown
=> [factor/pt-br] Add portuguese language for factor

julia.html.markdown
---
Camel cased everything per the style spec to help clear out issue #1483
=> [julia/en] fix for #1483

pcre.html.markdown
=> [pcre/en] Fix PCRE examples, closes #3226

it-it/pcre-it.html.markdown
=> [pcre/it] Add pcre-it.html.markdown

it-it/typescript-it.html.markdown
=> [typescript/it] Add typescript-it.html.markdown

yaml.html.markdown
=> Fix YAML, closes #3172

kotlin.html.markdown
=> [kotlin/en] Update link to run Kotlin in the browser

smalltalk.html.markdown
=> [smalltalk/en] Fix formatting

cs-cz/python3.html.markdown
Changes as per #3023 by @zbohm. For proper credits, I've made @zbohm commit author.
=> [python/cz] Fix text, closes #3023

yaml.html.markdown
=> [yaml/en] Explain regexp, closes #2197

red.html.markdown
=> [Red/en] Explain initialize, closes #1467

yaml.html.markdown
=> [yaml/en] Correct wording, closes #3098

smalltalk.html.markdown
Changes made by @timrowledge in a PR which was made in his fork of this repo by mistake. I have simply copied over his work here.
@timrowledge Please take a look!
=> [smalltalk/en] Fix content, closes #2622

solidity.html.markdown
Cherry-picked commit 86eb5be from #3066. Author credits to @varshard for his work.
=> Fix solidity, replace constant function with view function

tmux.html.markdown
Just adding a simple snippet about copy mode.  I use it a lot but used to forget what the key command was!
=> [tmux/en] adding info about copy mode

html.html.markdown
Changing up the HTML file to be limited to 80 line length.  Helps readability of the longer lines.
=> Enforcing 80 char linelength

mercurial.html.markdown
=>  Add the distributed source control management tool mercurial.

ansible.html.markdown
Also cleaned up some white space and make the yaml code blocks use a consistent notation.
=> Updated the Ansible docs now that AWX (open source tower) is available

typescript.html.markdown
Changing up the Typescript file to be limited to 80 line length.  Helps readability of the longer lines.
=> [typescript/en] Updating the line length to 80

es-es/pyqt-es.html.markdown
=> [pyqt/es-es] PyQT Spanish translation

mercurial.html.markdown
=> [mercurial/en] Multiple fixes

es-es/pyqt-es.html.markdown
=> [pyqt/es] Add language code

dynamic-programming.html.markdown
=> [Dynamic programming] Fixed links

clojure-macros.html.markdown
=> [clojure-macros] Fixed links

pt-br/dynamic-programming-pt.html.markdown
=> [Dynamic programming-PT/BR] Fixed links

ms-my/clojure-macros-my.html.markdown
=> [clojure-macros/ms-my] Fixed links

pt-br/csharp-pt.html.markdown
Translation of comments (line 98 and 99)  and correction of comments (line 62)
=> [csharp/pt-br] Update csharp-pt.html.markdown

pt-br/typescript-pt.html.markdown
=> [typescript/pt-br] Removed duplicate text

pt-br/ruby-pt.html.markdown
Translation of comments (line 98 and 99)  and correction of comments (line 62)
=> [ruby/pt-br] Update ruby-pt.html.markdown

pt-br/xml-pt.html.markdown
=> [xml/pt-bt] Better translation

pt-br/whip-pt.html.markdown
=> [whip/pt-br] Better translation

pt-br/paren-pt.html.markdown
=> [paren/pt-br] Small typos

pt-br/yaml-pt.html.markdown
=> [yaml/pt-br] Fixing translation

zh-cn/clojure-macro-cn.html.markdown
=> [clojure-macros/zh-cn] Fixed links

fr-fr/dynamic-programming-fr.html.markdown, nl-nl/dynamic-programming-nl.html.markdown
=> [Dynamic programming/FR and NL] Fixed links

pt-br/python3-pt.html.markdown
=> [python3/pr-br] Fixed typo

kotlin.html.markdown
See [What's New in Kotlin 1.3 / Parameterless main](https://kotlinlang.org/docs/reference/whatsnew13.html#parameterless-main).
=> [kotlin/en] Mention parameterless main function

sql.html.markdown
=> [sql/en] Adding SQL entry

es-es/lambda-calculus-es.html.markdown
=> [lambda-calculus/es-es] Translate Lambda Calculus to es_ES

php.html.markdown
Fix exception handling example to account for variance in handling exceptions in PHP when using it normally as opposed to inside a namespace.
=> [php/en] Fix exception handling example

zh-cn/markdown-cn.html.markdown
=> [markdown/zh-cn] Update Chinese translation

es-es/pascal-es.html.markdown
=> [pascal/es-es] Translate Pascal to es_ES 

es-es/coldfusion-es.html.markdown
Sorry I had to delete my other PR, branch became a mess after I tried to squash/rebase, still learning those
=> [coldfusion/es-es] Translate ColdFusion to es_ES 

ansible.html.markdown
https://github.com/adambard/learnxinyminutes-docs/pull/3392
=> [ansible/en] Additional spelling / grammar

json.html.markdown
=> [en-us]Fixed typo.

powershell.html.markdown
=> [powershell/en] add list syntax example

processing.html.markdown
=> [processing/en] Fix build error and styling

ansible.html.markdown
=> [ansible/en] Fix build error and styling

CONTRIBUTING.markdown
=> Add local build instructions, closes #3396

zh-cn/dart-cn.html.markdown
Same to my last commit of english version, fix bool implicit conversions support of chinese version.
=> [dart/zh-cn]Fix bool convert of chinese version.

ansible.html.markdown
=> [ansible/en] Cleaning up further

m.html.markdown
- [] Yes, I have double-checked quotes and field names!
=> [M (MUMPS)/en] Add M/MUMPS language

python3.html.markdown
=> [python3/en] show that True and False are ints

python3.html.markdown
=> [python3/en] show chaining operators nicer

es-es/common-lisp-es.html.markdown
Closes #3338. the original translation was edited according to my review.
Co-authored-by: Ivan Choff <ivanchoff@gmail.com>
=> [common-lisp/es] Spanish Translation for Common Lisp

yaml.html.markdown
Just removed a duplicate is in YAML docs
=> [yaml/en] Removed duplicate is in YAML docs

sl-si/asciidoc-sl.html.markdown
I've added Slovenian translation for AsciiDoc.
=> [sl-si/asciidoc] Add Slovenian translation for AsciiDoc

python3.html.markdown
=> [python3/en] Add note about dictionary item ordering in Python 3.7+

python3.html.markdown
A reminder to be aware of using mutable defaults.
Whether it is a real problem or not depends on exact use-case, but an update fully describing that and updating code with copying list, or defaulting with None and conditional initialization, would probably negatively affect readability of the example.
=> [python3/en] A note about common gotcha with mutable defaults

vim.html.markdown
=> [vim/en] markdown listify lists

perl6.html.markdown
- format consistently
- remove whitespace
- add example(s)
- fix typos
=> [perl6/en]  Add some changes

bash.html.markdown
Fixed line length (not more than 80 characters) and some minor mistakes. @divayprakash Could you please review?
=> [bash/en] Fix line length

perl6-pod.html.markdown, perl6.html.markdown
=> [perl6-pod/en] Add Perl 6 Pod tutorial

solidity.html.markdown, zh-cn/solidity-cn.html.markdown
Change:
**Solidity code should not be mixes with Javascript code**
=> [solidity/en,cn] Solidity code should not be mixed with Javascript code

c++.html.markdown
- [] Yes, I have double-checked quotes and field names!
=> [c++/en] add missing spaces after `//`

pt-br/stylus-pt.html.markdown
=> [Stylus/pt-br]

dart.html.markdown
=> [dart/en] Fix var/class/func naming, closes #2276

pt-br/asymptotic-notation-pt.html.markdown
=> [asymptotic-notation/pt-br] fix several typos

perl6-pod.html.markdown
=> [perl6-pod/en] Add some minor changes

smalltalk.html.markdown
Fixing tabs/spaces as per feedback received in EMail & some other minor changes
```
Hi,
In case you still want feedback, when I open the tutorial in vanilla Chrome, the boxes with the examples wrap badly.  It looks as if a tab stop is too far to the right. It doesn't affect all the boxes equally -- the one about Constants is mostly OK.
In other feedback, that's exactly the level of tutorial I find helpful, so thanks for writing it!
```
=> [smalltalk/en] Fixing tabs/spaces as per feedback received in EMail & some other minor changes

awk.html.markdown
=> [awk/en] fix minor spelling mistakes

stylus.html.markdown
=> [stylus/en] Translate stylus into en

typescript.html.markdown
=> typescript/en Fixes typo

javascript.html.markdown
It would also print myBoolean from prototype's prototype
=> [javascript/en] Fix prototype example

it-it/logtalk-it.html.markdown, logtalk.html.markdown
=> [logtalk/en,it-it] Improve section on compiling and loading source files

tr-tr/html-tr.html.markdown
Fixes #3461 by adding `lang` code line to html Turkish page.
=> [html/tr-tr] Fix #3461

python3.html.markdown
=> [python3/en] Update integer division

ar-ar/python3-ar.html.markdown
=> [python3/ar] Learn python 3 in Y minutes Arabic translation 

pascal.html.markdown
=> [pascal/en] Fixed missing escape character

pt-br/pascal-pt.html.markdown
=> [Pascal/pt-br] Translating Pascal guide to Brazilian Portuguese

m.html.markdown
^cars("Tesla",1,"Name") 
was defined in line 119
s ^cars("Tesla",1,"Name")="Model 3"
=> [M (MUMPS)/en] One-liner

python.html.markdown
Updating set info to be more descriptive and informative
=> [python/py3] Updating set info

lambda-calculus.html.markdown
I think it should be: `ADD = λab.(a S)b`
=> [lambda-calculus] propose correction for ADD

lambda-calculus.html.markdown
=> [lambda-calculus/en] markdown syntax issue

html.html.markdown, p5.html.markdown
=> [p5.js/en] Added new library p5.js docs and some edits in html docs

fr-fr/awk-fr.html.markdown
=> [awk/fr] add awk-fr.html.markdown

c++.html.markdown
=> [c++/en] Typo in c++

ru-ru/learnvisualbasic-ru.html.markdown
=> Create Russian translation of VB tutorial

de-de/yaml-de.html.markdown
=> [yaml/de-de] edited translation

pl-pl/java-pl.html.markdown
=> [java/pl-pl] Full Java translation to Polish

vyper.html.markdown
- [ √ ] I solemnly swear that this is all original content of which I am the original author
- [ √ ] Pull request title is prepended with `[language/lang-code]`
- [ √ ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ √ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ √ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ √ ] Yes, I have double-checked quotes and field names!
=> [vyper/en] Create vyper.html.markdown

dynamic-programming.html.markdown
=> added more resources

de-de/git-de.html.markdown
=> [git/de] Edited translation

de-de/markdown-de.html.markdown
It did not render the text 100% correct.
=> [markdown/de] Escaped backtick, I don't know how you render the comments.. Maybe it would work..

p5.html.markdown
Fix the issue [#3505](https://github.com/adambard/learnxinyminutes-docs/issues/3505).
=> [p5/en] Fix layout problem on webpage

kotlin.html.markdown
=> [Kotlin/EN] Refactor kotlin examples

pt-br/coffeescript-pt.html.markdown
This PR:
- fixes a wrong code equivalence to javascript
- rename variables using accents to variables without accents. 
- The usage of portuguese accents like í, á, ã, etc is considered a bad practice, even when the code is in portuguese. The recommendation is to use the word without accents, i.e., líquido becomes liquido
- fixes the links which were included in the code block, and therefore displayed as text like `[text](url)`
=> [coffeescript/pt-br] Fix typos and layout

de-de/asciidoc-de.html.markdown
=> [asciidoc/de] Added commas

de-de/python-de.html.markdown
Chapters 6.1, 6.2 and 7 taken from the english version.
Chapters 5 and 6 swapped to match the english version.
Texts in Chapters 5 and 6 Chapters expanded to include missing parts.
Kapitel 6.1, 6.2 und 7 aus der englischen Version übernommen.
Kapitel 5 und 6 in der Reihenfolge getauscht, um der englischen Version zu entsprechen. 
Texte der Kapitel 5 und 6 Kapitel um fehlende Teile erweitert.
=> [python/de] chapter 5+6 updated, chapter 6.1, 6.2, 7 added

toml.html.markdown
=> [toml/en] update toml doc and fix typos

zh-cn/make-cn.html.markdown
=> [make/zh] Update make-cn.html.markdown

haxe.html.markdown
Changes as suggested by @Botster in #3513.
=> [haxe/en] Fix grammatical errors, closes #3513

cypher.html.markdown
=> [Cypher/en] Escaping underscores (unwanted italic)

awk.html.markdown
=> [awk/en] add some related links 

fr-fr/erlang-fr.html.markdown
=> [fr-fr/erlang] fix syntax

pt-br/clojure-pt.html.markdown
=> [clojure/pt-br] fix some typos

de-de/c++-de.html.markdown
=> [c++/de] added language, resolves #3537

rst.html.markdown
=> [rst/en] Updating rules for list / sublist creation

prolog.html.markdown
=> [prolog] - typo fix in prolog.html.markdown

typescript.html.markdown
=> [typescript/en] Add doc for for-of and for-in loops in Typescript

es-es/kotlin-es.html.markdown
I'll create a pull request for english language soon
=> [kotlin/es-es] Add some additional information and improved examples

python3.html.markdown
=> [python3/en]Add output for python3 f-string.

ansible.html.markdown
=> [ansible/en]Fix typo

pug.html.markdown
Added support for the Pug language.
=> [pug/en] Add Pug language tutorial

bc.bc, bc.html.markdown
=> [bc/en] New tutorial

c++.html.markdown
As a naive learner I wouldn't have expected the `+=` operator to return anything. 
I was also surprised to learn that `this` is not simply an object, but a pointer to an object.
I had do make a web search to learn about those two things.
=> [c++/en] Add more explanation to the += overloading example

scala.html.markdown
=> [language/lang-code] Update scala docs link for Map

typescript.html.markdown
They're super useful.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions
https://mariusschulz.com/blog/typescript-2-0-tagged-union-types
=> [typescript/en] Add tagged union types

th-th/pascal.th.html.markdown
=> [pascal/th] fix a yaml typo, translator[s]:

ja-jp/asciidoc.html.markdown
=> [asciidoc/ja-jp]Add translate for AsciiDoc in ja-jp

emacs.html.markdown
A tutorial on the basics of Emacs. It can be enhanced by adding a primer on Emacs Lisp. I might add that later, but I'd prefer it if someone else contributed it as my experience with Elisp is limited right now.
=> [emacs/en] Basic Emacs tutorial

swift.html.markdown
=> [Swift/en] Update to Swift 5 and include omitted examples

zfs.html.markdown
=> [zfs/en] fix unclosed code block, command prompts, spelling

reason.html.markdown
=> [reason/en] Add Reason language

wasm.html.markdown
=> [webassembly/en] added WebAssembly tutorial

it-it/javascript-it.html.markdown
Translated from the version 2570367 of 21 Jan
=> [javascript/it-it] Create javascript-it.html.markdown

kotlin.html.markdown
=> [Kotlin/en] Kotlin enum

zh-cn/sql.html.markdown
=> [sql/zh-cn] Update Chinese version of SQL.

de-de/python3-de.html.markdown, solidity.html.markdown
added qualifier payable to the function Info, hence without it's not compileable
=> [solidity/en] added qualifier payable hence it's not compilable, [python/de] correction

perl6.html.markdown
Only some small types of mixing old/new code/comment from i rewrite i guess.
=> [perl6/en] Object Model example mixed old/new code/comments

mercurial.html.markdown
=> [mercurial/en] Fix mercurial workflow link

python3.html.markdown
=> [python3/en] Added enumerate function

reason.html.markdown
Some changes based on suggestions from by @amartincolby
=> [reason/en] Apply some spelling and ordering suggested

mercury.html.markdown
=> [mercury/en] Added Mercury

de-de/dhall-de.html.markdown, dhall.html.markdown
=> [dhall/de]: add German translation

tr-tr/edn-tr.html.markdown
=> [Edn/tr-tr]

tr-tr/sql-tr.html.markdown
Sql file created and added for Turkish language
=> Sql file added for Turkish

python3.html.markdown
=> [Python3/en] Added write to and read from a file syntax

perl6.html.markdown
=> [Perl6/en]Modify an error about the Range constructor

groovy.html.markdown
=> Optional parameters in methods

c++.html.markdown
* Fix minor spelling / grammar problems ("tp de-allocate", "refences", "dont"...)
* Remove filler words ("Basically", "As a matter of fact"...)
* Remove spaces before parens in smart pointer initialization code sample (consistent with the other sections, e.g. the `Tuples` section)
* Clarify `std::weak_ptr` use case
=> [C++/en] Minor fixes to Smart Pointer section

CONTRIBUTING.markdown
To be commited simultaneously with https://github.com/adambard/learnxinyminutes-site/pull/63
=> Nixify so it can be easily developed on Nix

zh-cn/yaml-cn.html.markdown
=> [yaml/zh-cn]Update yaml-cn.html.markdown

ldpl.html.markdown
---
Hi there! I've written **learn LDPL in y minutes**. I hope this may be useful. Thank you very much!
=> [ldpl/en] LDPL example documentation added.

cs-cz/python3.html.markdown
=> [python/cs-cz] Update examples: bool + generators

ca-es/html-ca.html.markdown
=> [html/ca-es] Catalan translation of HTML

python3.html.markdown
=> [python3/en] Fix explanation for slices, closes #3629

pt-br/groovy-pt.html.markdown
=> [groovy/pt-br] Small typo

pl-pl/bf-pl.html.markdown
=> [bf/pl-pl] Fix translation

uk-ua/python-ua.html.markdown, uk-ua/wasm.html.markdown
This pull request adds [wasm/ua] and updates my name in [python/ua]
- (no, translation) I solemnly swear that this is all original content of which I am the original author
=> [wasm/ua] Add translation

uk-ua/wasm-ua.html.markdown
- [] I solemnly swear that this is all original content of which I am the original author
=> [wasm/ua] Fix lang param

fr-fr/elixir-fr.html.markdown
=> [elixir/fr-fr] Add french translation

ru-ru/kotlin-ru.html.markdown
=> [kotlin/ru-ru] fix typo

lsf/lambda-calculus-lsf.html.markdown, lsf/latex-lsf.html.markdown
=> [LaTeX and λ/lsf] Add a new language

swift.html.markdown
=> [swift/en] Fix typos

th-th/typescript.th.html.markdown, typescript.html.markdown
=> [typescript/en,th-th] Fix typo in typescript comments

clojure.html.markdown
=> [clojure/en] Add "Clojure for the Brave and True" resource

pt-br/clojure-pt.html.markdown
=> [clojure/pt-br] Add "Clojure for the Brave and True" resource

de-de/nix-de.html.markdown
=> [nix/de] Fix broken link

pt-br/markdown-pt.html.markdown
=> [markdown/pt-br] Fix markdown-pt portuguese mistakes

pt-br/python3-pt.html.markdown
=> [Python/pt-br] Improve translation

CONTRIBUTING.markdown
Nothing personal, I'm just not willing to support two build methods.
=> Revert "Nixify so it can be easily developed on Nix"

de-de/bash-de.html.markdown
Was breaking the syntax coloring
=> [bash/de] Fix missing double quotes

python3.html.markdown
=> [python3/en] Fixed a small typo

de-de/c++-de.html.markdown
=> [C++/de-de] Fixed some typos in german translation

csharp.html.markdown
=> [C#/en] Update some urls

zh-cn/yaml-cn.html.markdown
=> [yaml/zh-cn] Sync with en-us

coq.html.markdown
=> [coq/en] New Coq tutorial

javascript.html.markdown
---
I don't believe I've seen any documentation for ES6 features. Please let me know if this is the appropriate document to place them in or if I should start another one.
=> [en/js] - Adds documentation for some basic ES6 features.

csharp.html.markdown
=> [en/csharp] - Fixes the spacing of comments in the English C# documentation

pt-br/php-pt.html.markdown
=> [php/pt-br] Small typo

pt-br/cypher-pt.html.markdown
=> [cypher/pt-br] Small typo

pt-br/typescript-pt.html.markdown
=> [typescript/pt-br] Small typo

pt-br/css-pt.html.markdown
=> [css/pt-br] Translation adjustments

pt-br/bash-pt.html.markdown
=> [bash/pt-br] Translation adjustments

pt-br/yaml-pt.html.markdown
=> [yaml/pt-br] Translation adjustments

pt-br/julia-pt.html.markdown
=> [julia/pt-br] Better translation

pt-br/latex-pt.html.markdown
=> [latex/pt-br] Grammar error

pt-br/typescript-pt.html.markdown
=> [typescript/pt-br] Better translation

pt-br/stylus-pt.html.markdown
=> [stylus/pt-br] Typos

pt-br/javascript-pt.html.markdown
=> [language/lang-code] Small Typos Fix

es-es/hy-es.html.markdown
=> [hy/es-es] Add spanish traduction to hy

es-es/factor-es.html.markdown
=> [factor/es-es] Add spanish traduction to factor

ruby.html.markdown
=> [en/ruby] - Adds documentation for multiline comments

pt-br/haskell-pt.html.markdown
=> [haskell/pt-br] Small typo

pl-pl/bf-pl.html.markdown
=> [bf/pl-pl] Fix typo in url

it-it/bash-it.html.markdown
=> [bash/it-it] Add explanation of `=~` and `alias` inside bash/it-it

it-it/elixir-it.html.markdown
=> [elixir/it-it] Add section about pipes, and fix docs here and there

c.html.markdown, es-es/c-es.html.markdown, pt-br/c-pt.html.markdown, ru-ru/c-ru.html.markdown, tr-tr/c-tr.html.markdown, zh-cn/c-cn.html.markdown
=> [C/en,es,tr,pt-br,zh-cn,ru-ru] update book link

pt-br/elisp-pt.html.markdown
=> [elisp/pt] Correção ortográfica

pt-br/whip-pt.html.markdown
=> [whip/pt] Correção ortográfica

pt-br/haskell-pt.html.markdown
=> [haskell/pt] Correção ortográfica

dart.html.markdown
=> [dart/en] Add example for Optional Positional Parameter

ta_in/css-ta.html.markdown
=> [css/ta_in] Update css-ta.html.markdown

css.html.markdown
=> [en/css] fix spacing

typescript.html.markdown
=> [en/typescript] add type assertion section

common-lisp.html.markdown
=> [common-lisp/en] Update common-lisp.html.markdown

es-es/hq9+-es.html.markdown
=> [HQ9+/es-es] Added spanish traduction for hq9+

es-es/pcre-es.html.markdown
=> [pcre/es-es] Added spanish traduction for pcre

zh-cn/powershell-cn.html.markdown
=> [powershell/zh-cn] Add poweshell Simplified Chinsese version

pt-br/clojure-pt.html.markdown
=> [clojure/pt-br] Rewrite text to be more natural in portuguese

dynamic-programming.html.markdown
=> [dp/en] Add some resources for Dynamic Programming

java.html.markdown
=> [Java/en] Minor typo fix in doWhile loop comment

go.html.markdown
=> [go/en] add go build tag

pt-br/clojure-macros-pt.html.markdown
=> [clojure-macros/pt-br] Fix language typos

ansible.html.markdown
Change-Id: I46fe48764029d243b211cef04f06fdf62ea39219
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> [ansible/en]: Fix quotes in command line example

pt-br/vim-pt.html.markdown
Added information under "Alguns atalhos e dicas" and "Macros"; removed some wild text in the header (essentially, one of the contributors was one of vim's modes)
=> [pt-br/vim] Add command tips and examples, fix wild text

pt-br/pascal-pt.html.markdown
I translated this a while back and decided to add myself as a contributor besides a translator because I changed much of the original text to what I feel is a more legible, better explanation of the Pascal language.
=> [pascal/pt-br] Update contributors in pascal-pt

de-de/java-de.html.markdown
Just a simple update to the link
=> Updated link to java coding guidelines, the old one is broken

swift.html.markdown
=> [swift/en-us] add downcast to the tutorial

haskell.html.markdown
=> [haskell/en]

wasm.html.markdown
=> [wasm/en] add example of how struct might be returned

ansible.html.markdown
=> [ansible/en]Fix typos

python3.html.markdown
Added a version without parentheses to make it clear what they are doing;
Added return values for True and False because 3 also has it.
=> Explaining better and improving consistence

linker.html.markdown
Simple fix to replace a localhost link with the actual site URL.
=> [linker/en] Fix link to Russian translation

elixir.html.markdown
=> [elixir/en] Use https links

ansible.html.markdown
Forwarded: https://github.com/adambard/learnxinyminutes-docs/pull/
Change-Id: Ic41e20f44f7e7aeab1811d8d48964c5d57c335eb
Signed-off-by: Philippe Coval <rzr@users.sf.net>
=> [ansible/en]: Fix URL link

kdb+.html.markdown
=> update broken link

php.html.markdown
=> [php/en] Remove an extra double quote

de-de/html-de.html.markdown
=> [html/de-de] fixed some typos in german translation

de-de/bash-de.html.markdown
=> [bash/de-de] typo fixed

el-gr/python3-gr.html.markdown
=> [python/el-gr] Add greek translation for python 3

powershell.html.markdown
=> [PowerShell/en] Update url

zh-cn/git-cn.html.markdown
=> [Git/zh-CN] Fixed typo

dart.html.markdown
=> [dart] fixed typo

csharp.html.markdown
- An ambiguous sentence, needed full stop (.)
- "i.e." instead of "ie."
=> [c#/en] Updated grammar

de-de/latex-de.html.markdown
=> [latex/de-de] fixed some small typos in translation

javascript.html.markdown
=> [javascript/en] Add missing semicolon for consistency

python3.html.markdown
=> [Python3/en] copy sets

it-it/bash-it.html.markdown
=> piccola correzione di testo
