adambard/learnxinyminutes-docs

- zh-cn/yaml-cn.html.markdown
> [yaml/zh-cn] Fix typo and minor sync

- zh-cn/css-cn.html.markdown
> [CSS/zh-cn] Fixed typo

- zh-cn/markdown-cn.html.markdown
> [markdown/zh-cn] Fix typo

- vimscript.html.markdown
This is a tutorial for the Vim scripting language. It presumes that the reader is already familiar with Vim in general and only covers its scripting.
> [vimscript/en] Vimscript tutorial

- hdl.html.markdown
> [hdl/en] Add Hardware Description Language Documentation

- rust.html.markdown
Sorry if this annoys anyone, just feels a bit annoying to not have the language's name be capitalized :P
> [rust] update lang name to be correct

- python3.html.markdown
- [X ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [X ] Yes, I have double-checked quotes and field names!
> python3/en/ Update string formatting

- de-de/bc.html.markdown
I resolved the issues in [this](https://github.com/adambard/learnxinyminutes-docs/pull/3633) Pull request. 
Unfortunately I could not get the source branch anymore, so I had to create a new PR. I'm sorry.
>  [bc/de-de] added translation in german for bc

- toml.html.markdown
> [toml/en] Fixed Typo and added a few examples

- go.html.markdown
> go/en: add type switch and multiple cases

- zh-tw/dart-tw.html.markdown
> [dart/zh-tw] Translated Dart to zh-tw

- ruby.html.markdown
> [ruby/en] Change "invokation" to "invocation"

- CONTRIBUTING.markdown
> [CONTRIBUTING.markdown] Change "buid" to "build"

- vimscript.html.markdown
- Correct "command-mode" to "command-line mode"
- Improve the variable type checking
- Typos
> [vimscript/en] Fix minor issues

- de-de/c-de.html.markdown
I have translated the English version of C to German.
This PR will solve Issue #3592.
Sometimes it was quite difficult to translate the words because the content would make less sense when translating to German. I hope it's not that bad.
> [de-de/c] Translated C to German (See Issue #3592)

- rust.html.markdown
> [rust/en] Small stylistic fix.

- go.html.markdown
> [go/en] Clarify safety of taking local variable address.

- go.html.markdown
> [go/en] Add value/reference semantics information for arr/slices.

- de-de/d-de.html.markdown
> [D/de-de] Fixed some typos in translation

- es-es/clojure-es.html.markdown
> [clojure/es] Update translation

- de-de/c-de.html.markdown
I made a whitespace after the character `{` in functions etc.
I changed the indentation because of a discussion in PR #3839
> [c/de-de] made a whitespace after { character

- c.html.markdown
> [C/en] Rephrase variable declaration comments

- pascal.html.markdown
> [pascal/en] Fixed a spelling mistake

- de-de/c-de.html.markdown
I reworded the comment so that the English and the German version have the same content.
See PR #3864
> [c/de-de] reworded variable declaration comment

- processing.html.markdown
Before: 2 -1 = 0
After: 2 - 1 = 1
> [processing/en] Fixed a small math error

- go.html.markdown
> [go/en] Add Golang University playlist links

- cs-cz/python.html.markdown
> [python/cs-cz] Fix bad description of floor division

- es-es/ruby-es.html.markdown
> [ruby/es] Fixed a spelling mistake

- dynamic-programming.html.markdown
> [dynamic-programming/en] Fix whitespace to be consistent

- raku.html.markdown
Given the context, there is a missing function call.
EDIT: Also fixed output typo
> [raku/en] Added missing function call

- cobol.html.markdown
> [en-en/cobol] Added COBOL. With all the current press, I think this is inevitable.. I'm not an expert, but it's a start.

- cobol.html.markdown
> [en-en/cobol] Corrections and some added explanation.

- ja-jp/python-jp.html.markdown
> [Python/ja-jp] Fix tiny typo

- processing.html.markdown
> [processing/en] Fixed some small typos

- lua.html.markdown
- [ X ] I solemnly swear that this is all original content of which I am the original author
- [ X ] Pull request title is prepended with `[language/lang-code]`
- [ X ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ X ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ X ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ X ] Yes, I have double-checked quotes and field names!
> [lua/en] Fix typo by indicating a range with '...' instead of '..'

- vim.html.markdown
> [vim/en] Add shortcut for quit vim

- mips.html.markdown
> [MIPS/en] minor fix for uncommented comment line

- el-gr/vim-gr.html.markdown
> [vim/el-gr] Add greek translation for vim

- it-it/zfs-it.html.markdown
> [zfs/it] Add zfs-it.html.markdown

- it-it/sql-it.html.markdown
> [sql/it] Add sql-it.html.markdown

- de-de/elm-de.html.markdown
> [elm/de] Translate elm to german

- de-de/pug-de.html.markdown
> [pug/de] Translate pug to german

- de-de/clojure-macros-de.html.markdown
> [clojure-macros/de] Translate clojure-macros to german

- c++.html.markdown
> [C++/en] Remove extra space

- ldpl.html.markdown
> [ldpl/en] Removed dead links

- python.html.markdown
> [python/en] Update python.html.markdown

- bash.html.markdown
> [bash/en] Add indirect expansion

- jsonnet.html.markdown
> [jsonnet/en]

- set-theory.html.markdown
> [set-theory/en] Propose Set Theory

- git.html.markdown
> [git/en] Correcting Minor Typos

- set-theory.html.markdown
> [set-theory/en] Fix formatting issues

- matlab.html.markdown
Corrected "Multiple each element in A" to "Multiply each element in A" in line 237.
- [ Yes ] I solemnly swear that this is all original content of which I am the original author
- [ Yes ] Pull request title is prepended with `[language/lang-code]`
- [ Yes ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ Yes ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ N/A ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ Yes ] Yes, I have double-checked quotes and field names!
> [matlab/en] Correcting typo

- smalltalk.html.markdown
> [smalltalk/en]Fix symbol concatenation example in Smalltalk

- nl-nl/json-nl.html.markdown
Added a few missing characters.
> [json/nl] Small translation fixes

- elixir.html.markdown
> [elixir/en] Added link

- de-de/ruby-de.html.markdown
> [ruby/de] Update to be in sync with English version

- php.html.markdown
> Explains variable declaration plus a minor improvement

- vim.html.markdown
> [vim/en] added the join command

- powershell.html.markdown
> [powershell/en] Adding things people may find useful

- dart.html.markdown
Fix typo in introductory paragraph.
> [dart/en] fix typos

- bash.html.markdown
pass "-e" flag to echo to interpret escape characters correctly
> [bash/en] fix small omission

- ruby.html.markdown
> [ruby/en] Add Ruby shorthand block syntax examples

- zh-cn/c-cn.html.markdown
> [C][zh-cn]Fix typo

- php.html.markdown
> Explains the weird behavior of PHP tag in a PHP script

- dart.html.markdown
Updated const declaration and removed print addressing missing array.
> [dart/en-en] Updated example 8

- fr-fr/crystal-fr.html.markdown
> [crystal/fr] Minor fix about "on/ont"

- ruby.html.markdown
Hi.. i thought it could be useful include some tricks. See 'Files changed' for more details.
> [ruby/en] Ruby useful tricks

- fr-fr/fsharp-fr.html.markdown
Translate untranslated comment and explicitly cite currying
> [f#/fr] Add missing translation

- dart.html.markdown
`var hasValue ??= "default Value";` 
doesn't work in dart 2.7.0
> [dart/en-en] Updated example 33

- typescript.html.markdown
> [typescript/en] incorrect syntax in inheritance example

- zh-cn/opencv-cn.html.markdown
> [OpenCV/zh-cn]Add translation for opencv

- dart.html.markdown
> [dart/en-en] Updated example 9: made 'i' variable non-final

- zh-cn/opencv-cn.html.markdown
> fix translation error for opencv-cn.html.markdown

- jsonnet.html.markdown
----
Python style comment should starts with `#` 😉
> [jsonnet/en] Update jsonnet.html.markdown

- zh-cn/python-cn.html.markdown
> [python/zh-cn] Fix wrong method name in comment

- opencv.html.markdown
> [OpenCV/en] Fixed the links to be clickable

- red.html.markdown
> [red/en] Fix Stack Overflow link

- bash.html.markdown
MacOS no longer ships bash as the default shell, so I felt it necessary to remove it from the intro.
> removed MacOS from intro

- qsharp.html.markdown
- [✓] I solemnly swear that this is all original content of which I am the original author
- [✓] Pull request title is prepended with `[language/lang-code]`
- [✓] Pull request touches only one file (or a set of logically related files with similar changes made)
- [✓] Yes, I have double-checked quotes and field names!
Related to issue: #3115 
Co-authored-by: Mariia Mykhailova <mamykhai@microsoft.com>
> [qsharp]/en] Add documentation for Q#

- lbstanza.html.markdown
> [LB Stanza/en] Include the LB Stanza Progamming Language

- fsharp.html.markdown
changes regarding objectives in https://github.com/fsharp/fsfoundation/issues/827, as http://www.tryfsharp.org/Learn seems to be broken and https://dotnet.microsoft.com/languages/fsharp is seen as a good but barely used resource.
> [F#/en] Fsharp dugnad 15 07 2020

- cobol.html.markdown
Fixed multiple errors in the COBOL tutorial.
> [cobol/en] Update to cobol.html.markdown

- zh-cn/make-cn.html.markdown
> [make/zh-cn] fix translation error for make-cn.html.markdown

- fr-fr/elisp-fr.html.markdown
Also use "motif" as a translation for "pattern", but still mention
"pattern" as it is commonly understood.
> [fr-fr/elisp-fr.html.markdown] Fix typos

- typescript.html.markdown
> [typescript/en-us] add type to Point.dist and fix error

- de-de/processing-de.html.markdown
> [processing/de-de] Translated processing to german

- janet.html.markdown
> [janet/en] initial version

- zh-cn/yaml-cn.html.markdown
You can also use https://yamlonline.com/ for the yaml validator as well as yaml converter to json,csv,xml,base64 also for beautify and minify YAML.
> YAML to JSON

- vim.html.markdown
Add information about vimtutor, a tutor that comes with vim. I haven't changed any part of the YAML frontmatter.  
- [] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
> [vim/en] Update vim.html.markdown, add vimtutor

- raylib.html.markdown
Adds a tutorial for [raylib](https://github.com/raysan5/raylib)
> [raylib/en] Add raylib tutorial

- de-de/vim-de.html.markdown
> [vim/de-de] Translate vim to german

- fr-fr/javascript-fr.html.markdown
Co-authored-by: Carl20cent <carl.vincent38@gmail.com>
resolves and closes #3894
***
> [js/fr] fix for...of loop

- powershell.html.markdown
Changing to reflect current capabilities and draw similarities to other languages in terms of capabilities
> [Powershell/en] Refactoring Powershell Wiki

- tr-tr/jquery-tr.html.markdown
Notes:
This document is an original document, not a translation! (You guys wanted me to express this detail in the PR a few PR ago)
Thank you again, for all the effort guys!
> [jquery/tr-tr] jQuery Original Document in Turkish!

- tr-tr/ruby-tr.html.markdown
> [ruby/tr-tr] Ruby Original Document in Turkish!

- sql.html.markdown
> [sql / en] Ambiguous ISO

- pt-br/elixir-pt.html.markdown
> [elixir/pt-br] typo

- zh-cn/haskell-cn.html.markdown
> [haskell/zh-cn]Update haskell-cn.html.markdown

- latex.html.markdown
> [latex/en] Include variables in \forall formula

- c++.html.markdown
> `[language/C++]` Changed operator < to !=

- pt-br/fsharp-pt.html.markdown
**This document is a translation from the english version on this repository.
> [F#/pt-br] Add translation for F# to Brazilian Portuguese

- rst.html.markdown
> [rst/en] Fixed a typo and reworded some sentences

- smalltalk.html.markdown
I've corrected two minors errors in the text.
> [smalltalk] Correcting orthograph

- pt-br/awk-pt.html.markdown
> [awk/pt-br] Small corrections

- pt-br/matlab-pt.html.markdown
> [matlab/pt-br] Small corrections

- pt-br/kotlin-pt.html.markdown
> [kotlin/pt-br] Small corrections

- pt-br/self-pt.html.markdown
> [self/pt-br] Small corrections

- pt-br/julia-pt.html.markdown
> [julia/pt-br] Small corrections

- pt-br/bash-pt.html.markdown
> [language/lang-code] Accentuation fix

- pt-br/typescript-pt.html.markdown
A couple of typo fixes, and I saw some lines that were not translated so I went ahead and fixed that on this commit.
> [language/lang-code] Typo fix and adding translation on needed lines

- pt-br/groovy-pt.html.markdown
> [groovy/pt-br] Small corrections

- pt-br/typescript-pt.html.markdown
> [typescript/pt-br] Small corrections

- set-theory.html.markdown
> [set-theory/en] correct equality statement

- pt-br/lua-pt.html.markdown
> * [x]  I solemnly swear that this is all original content of which I am the ~original~ author**
> * [x]  Pull request title is prepended with `[language/lang-code]`
> * [x]  Pull request touches only one file (or a set of logically related files with similar changes made)
> * [x]  Content changes are aimed at _intermediate to experienced programmers_ (this is a poor format for explaining fundamental programming concepts)
> * [x]  If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
>   
>   * [x]  Yes, I have double-checked quotes and field names!
> 
> **This document is a translation from the english version on this repository.
> [pt-br/lua] Add translation for Lua to pt-BR

- yaml.html.markdown
---
There are some improvements that are hard for me to write:
* Add a WYSIWYG YAML to JSON converter. I have found https://www.json2yaml.com/ but it has some issues and I can't find the website's mantainer. Is there a better one?
* Add notes about avoid using folded_style according to https://github.com/yaml/YAML2/wiki/Folded-Block-Scalars
* Mention YAML's pitfalls like https://hitchdev.com/strictyaml/why/implicit-typing-removed/
> [yaml/en] Remove unused anchor

- json.html.markdown
> [json/en] use https

- jquery.html.markdown
Brief explanation of jQuery status
> [javascript] Added note

- haskell.html.markdown
The `!!` operator was previously used without any explanation whatsoever
> [Haskell/en] Explain the !! operator

- fr-fr/c++-fr.html.markdown
> Fix a small french typo

- go.html.markdown
> go/en - Fix typo in build tag description

- jsonnet.html.markdown
> [jsonnet/en] typo and grammar fix

- bash.html.markdown
Hi again,
I've been re-reading all the pages for the languages I love and use, to track and fix tiny issues.
Here are my updates for bash:
- I added https:// for the links, it's 2021, http:// is dead
- fixed two comments which where `#text` => `# text` for consistency
- added a link to `trash-cli` Python package which provides `trash` as a "safe" alternative to `rm`
- add warning that `sed -i` erase (replace) the input file
- add `...` around fgrep and grep -F, for consistency too
> [bash/en] Small updates

- lua.html.markdown
- [x ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
> [lua/en] - Fixed dead link for: Lua for programmers

- c++.html.markdown
Just forcing http:// links to be https:// when possible.
I also read everything carefully and didn't find any mistake or easy improvements I could add (but I'm not that familiar with C++)
> [c++/en] just force http links to be https

- latex.html.markdown
Hi again, (not my first pull-request)
It bothered me that the document for LaTeX contained 
- I definitely have to lookup the placement options each time.
-   % Again, I have to look these up. Each. And. Every. Time.
So I added a few lines to explain the most basic options of float positions and tables layout.
It's really not that magical, at least for the basic options (and they are enough, [I wrote a 300 page thesis](https://perso.crans.org/besson/phd.pdf) with almost no need for any other options except the one introduced here)
I also added a last short section about using LaTeX to display non-ASCII symbols (like French ç with \,c) or writing in non-ASCII input.
I think it's mandatory to include this, as most LaTeX users are *not* native English speakers.
I mentioned LuaTeX and …
> [latex/en] Add some explanations for: floats, tables, and non-ASCII input

- julia.html.markdown
Small update on julia.html.markdown, typos and comments.
(it's not my first tiny pull request here)
> [julia/en] Small update on julia.html.markdown, typos and comments

- kotlin.html.markdown
> [kotlin/en] Typo in comment

- c.html.markdown
Just add a few explanations where I thought details were missing:
- "Floating-point numbers and calculations are not exact" was mentioned without any examples. Many students of mine believe that floating-point calculation errors are very rare and esoteric, but they are not!
- Just a little bit of more details for "goto" and labels.
> [c/en] Just a few explanations, a couple of tiny changes

- coq.html.markdown
change 8-bits in comment to singular
> [coq/en] 8-bits => 8-bit

- zh-cn/java-cn.html.markdown
Simplify the description in Chinese to prevent verbosity.
> [java/cn] Update java-cn.html.markdown

- docker.html.markdown
> [docker/en] Add syntax highlighting, fix typos

- python.html.markdown
> [python/en] Fix tiny typos

- zh-cn/c-cn.html.markdown
This file has moved to process/coding-style.rst
> 修改Linux内核编码风格链接

- zh-cn/qt-cn.html.markdown
> [Qt/zh-cn]Add translation for qt

- de-de/elixir-de.html.markdown
> [elixir/de-de] add hint to numeric underscore for better readability

- fr-fr/java-fr.html.markdown
jours de la semaine = day of the week.
jours de l'année = day of the year.
> [java/fr] Fix typo

- purescript.html.markdown
Here is a swift update for the latest update. There is definitely room for more improvement as I believe some of the given examples aren't ideal, e.g. pattern matching. This at least should get readers of to a better start.
> [purescript/en] Updates for latest PureScript

- fr-fr/asymptotic-notation-fr.html.markdown
> [asymptotic-notation/fr] fix small typos

- fr-fr/set-theory-fr.html.markdown
- set-theory.html.markdown
> [set-theory/fr] Added French translation for Set theory 

- zh-cn/perl-cn.html.markdown
indentation was wrong and fixed.
> [perl/zh-cn]fix indent

- zh-cn/cmake-cn.html.markdown
> [CMake/zh-cn]Translation CMake

- zh-cn/wolfram-cn.html.markdown
> [wolfram/zh-cn]Create wolfram-cn.html.markdown

- zh-cn/asciidoc-cn.html.md
> [asciidoc/zh-cn] Add translation

- el-gr/vim-gr.html.markdown
Fixes #4211. @adambard I hope that's enough :). 
-[x] Yes, I have double-checked quotes and field names!
> [wim/gr] Try fixing display bug

- elixir.html.markdown
I really struggled to parse what was being explained, but found the wording on https://hexdocs.pm/elixir/1.12/Atom.html much easier to understand.
> [Elixir/en] Update description of an Atom.

- fortran95.html.markdown
> [fortran/en] Add new resource

- mongodb.html.markdown
> [MongoDB/en] Add Learn MongoDB in Y Minutes

- toml.html.markdown
It will correctly show structured, formatted JSON to give a better understanding
> Fix JSON code blocks in TOML

- bash.html.markdown
Additional info on arguments and return values for functions
> [bash/en] update

- java.html.markdown
> [java/en] Added more info about Collections initialization

- c.html.markdown
> [c/en] mostly word clarification and extra descriptions

- crystal.html.markdown
Crystal 1.0 was released this year (currently at 1.1.1 actually), which solidified the language. Updating based on language changes.
- [YES] I solemnly swear that this is all original content of which I am the original author
- [YES] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [YES] Pull request touches only one file (or a set of logically related files with similar changes made)
- [YES] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- …
> [crystal/en] Update crystal based on Crystal 1.0

- haskell.html.markdown
> [haskell/en] Add boolean and and or

- fish.markdown
- [ X] I solemnly swear that this is all original content of which I am the original author
- [ X] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [ X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ X] Yes, I have double-checked quotes and field names!
> [fish/en] Add fish shell

- csharp.html.markdown
> [csharp/en] Update C Sharp markdown.

- gdscript.html.markdown
Made a tutorial for Godot's GDScript. Related to #4242
> [GDScript/en] Add GDScript

- php.html.markdown
> [PHP/en] Nullsafe operator

- c++.html.markdown
I've been learning from this site, and it seems good, and the general consensus online is that it's one of the better online tutorials/books for learning C++.
(I'm not the site's author, though.)
- [maybe] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [n/a] Yes, I have double-checked quotes and field names!
> [C++/en] Add learncpp.com to further reading

- sing.html.markdown
> [sing/en] Added sing language

- easylang.html.markdown
> Add Easylang

- typescript.html.markdown
> [typescript/en] Updates enum usage

- opencv.html.markdown
It was a dead link and doesn't seem to be active anymore.
> [opencv/en] Removing Dead link

- typescript.html.markdown
> [typescript/en] Add template literal types

- texinfo.html.markdown
> [texinfo/en] Learn Texinfo in Y minutes

- cs-cz/markdown.html.markdown
- I tried my best, but was unable to try this on local build of the website, because I encountered several problems installing `gem` packages (esp. `nokogiri`).
- My former intention was to only correct a few typos, but after a while I found out that the original translation was stylistically not very good and felt pretty much "robotic" and that it needed several stylistic improvements.
---
> [markdown/cs-cz] Improve translation language style and add subchapter on table of contents

- cs-cz/markdown.html.markdown
- markdown.html.markdown
- I added two new subchapters and some reference links for English article on Markdown.
- I also made minor improvements and typo fixes that I previously introduced into the Czech translation.
---
> [markdown/en] add chapters on table of contents and markdownlint

- go.html.markdown
> [go/en] Update documentation for expensiveComputation()

- pascal.html.markdown
> [pascal/en-us] Fixed a few typos

- hdl.html.markdown
> [hdl/en] Fix variable name typo

- go.html.markdown
- [Yes] I solemnly swear that this is all original content of which I am the original author
- [Yes] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [Yes] Pull request touches only one file (or a set of logically related files with similar changes made)
- [No, only a typo fix] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [Did not change YAML] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [Yes] Yes, I have double-checked quotes and field names!
> [go/en] fixed typo

- .github/CODEOWNERS
Add our new maintainer for Korean @justin-themedium to code owners. Thank you for your help!
> [misc/ko-kr] Add Justin as code owner for Korean

- zh-cn/nim-cn.html.markdown
> [nim/zh-cn] Add translation

- zh-cn/go-cn.html.markdown
> [go/zh-cn] Add translation

- mips.html.markdown
- x ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
> [mips/en] Fixed errors

- zh-cn/python-cn.html.markdown
> [python/zh-cn] Empty tuple is also False

- go.html.markdown
> [go/en] render bullet points correctly

- set-theory.html.markdown
> [Set theory/set-theory] fix typo

- scala.html.markdown
> [scala/en] Add missing class instantiation and fix typos

- cobol.html.markdown
I corrected 2 minor typos (first instance is extra/misplaced period & the second instance is a misspelling).
> [cobol/en] Correct 2 minor typos

- pug.html.markdown
> [pug/en] Fix typos in mixins

- CONTRIBUTING.markdown
> [CONTRIBUTING.markdown] removed 'of' + judgement -> judgment

- vim.html.markdown
yank and delete unexplained at first occurrence
not even basic requirement i.e. yank = copy
- added draft explanations
> [vim/en] explain yank and delete at first occurrence

- csharp.html.markdown
The name used in the comment for the BikeBrand enum was incorrect.
> [csharp/en] Use correct name for enum in comment

- wasm.html.markdown
> [WebAssembly/en] Fix type error

- nix.html.markdown
Replace original link with archived version from wayback machine.
> [nix/en] Fix dead link for `Rommel Marinez` Further Reading

- swift.html.markdown
the variable name should be `someIdentifier` instead of `willSet`.
> fix a typo

- visualbasic.html.markdown
* The comment "Ouputs the above" was misleading, changed it to a more apt comment ("Pausing the execution")
> [visualbasic/en] Update to more apt comments

- javascript.html.markdown
var => function/global , let => lexical/block scoped
> [javascript/en]Update javascript.html.markdown

- ocaml.html.markdown
Add type info for the list example.
> [ocaml/en] Update ocaml.html.markdown

- dart.html.markdown
Replace the old links which were deprecated with the new URLs they redirect to.
> [dart/en] Replace deprecated links

- r.html.markdown
Fixed output provided in comments beside the command.
> [R/en] Fixed output of a command

- c++.html.markdown
> [c++/en] Fix newline error

- html.html.markdown
Minor edits to typography edits to improve readability in beginning and ending descriptions
> [html/en] Minor typographical improvements

- c.html.markdown
> [c/en] clarity, errata, and grammar in array section

- bash.html.markdown
> [bash/en] Add info on background commands with &

- bash.html.markdown
> [bash/en] More details about pipe and redirection

- easylang.html.markdown
> [Easylang] One keyword has changed

- lua.html.markdown
> [lua/en] add Lua community links

- phel.html.markdown
> [phel/en] Add phel.html

- zh-cn/docker-cn.html.markdown
> [Docker/zh-cn] Init translation

- zh-cn/raylib-cn.html.markdown
> [raylib/zh-cn] Completed translation

- pt-br/r-pt.html.markdown
Translation of the markdown file of R to Brazilian Portuguese and update of the header with some information regarding the translator.
> [r/pt-br] Translate R Markdown

- mongodb.html.markdown
Reading thru & found couple of typos, here's the fixes.
> [mongodb/en] fix couple of typos

- fr-fr/rust-fr.html.markdown
> [rust/fr] Fix/french translations

- fr-fr/set-theory-fr.html.markdown
Multiple errors prevented the translation from being displayed:
* contributors was indented with a tab instead of two spaces.
* the category was not the same as the original english file.
* a code block was closed at the end of the file, but never
opened.
fixes issue #4189
> [set-theory/fr] Fix multiple errors.

- zh-cn/rust-cn.html.markdown
> [rust/zh-cn] fix chinese translation.

- pt-br/rust-pt.html.markdown
> [rust/pt] fix portuguese translation.

- uk-ua/rust-ua.html.markdown
> [rust/uk] fix ukrainian translation.

- es-es/rust-es.html.markdown
> [rust/es] fix spanish translation.

- de-de/vim-de.html.markdown
The line duplicated was the English pattern already translated
into German.
> [vim/de] remove duplicated line

- ru-ru/rust-ru.html.markdown
> [rust/ru] fix russian translation.

- pt-br/yaml-pt.html.markdown
- Updated to latest EN version (with respective translation)
- Fixed some pt-BR typos
- Fixed indentations to be equal to the original EN version
> [YAML/pt-br] Some fixes and update

- latex.html.markdown
> [latex/en] addition of two resources

- pt-br/latex-pt.html.markdown
Updates the pt-br translation
Fixes some mistakes
> [latex/pt-br] Update/improve pt-br translatoin of LaTeX

- vi-vn/json-vi.html.markdown
In json/vi-vn
- [ yes ] I solemnly swear that this is all original content of which I am the original author
- [ yes ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [ yes ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ yes ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ no ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ yes ] Yes, I have double-checked quotes and field names!
> [json/vi-vn] Add a missing comma

- fr-fr/rust-fr.html.markdown
> [rust/fr-fr] Fix typo.

- fortran90.html.markdown
> [Fortran/en] adjust name, edit format, add 2018 standard

- fr-fr/set-theory-fr.html.markdown
> [set-theory.fr-fr] Fix multiple typos.

- pt-br/awk-pt.html.markdown
Edit is based on correction in the English edition.[1]
[1] https://github.com/adambard/learnxinyminutes-docs/pull/4437
> [AWK/pt-br] correct example gsub

- zh-cn/awk-cn.html.markdown
Edit based on the correction of the English original.[1]
[1] https://github.com/adambard/learnxinyminutes-docs/pull/4437
> [AWK/zh-cn] correct example gsub

- docker.html.markdown
- zh-cn/docker-cn.html.markdown
- Fix document category for Docker
- Fix document category for Docker in zh-cn
> [docker/en and zh-cn] Fix document category

- erlang.html.markdown
> [erlang/en] Update link to personal site

- vimscript.html.markdown
> [vimscript/en] fix typo:  pacing -> placing

- solidity.html.markdown
> [solidity/en] fix minor typos

- bash.html.markdown
> [bash/en] fix typo

- pt-br/markdown-pt.html.markdown
- Fix syntax, typos and text style for markdown-pt
- Keep lines <=80 chars in markdown-pt-br
- Add table of contents
- Update pt-br translation of Markdown
- Improve pt-br translation of Markdown
> [markdown/pt-br] Update, fix and improve translation

- de-de/asciidoc-de.html.markdown
> [asciidoc/de], remove overly long lines

- hack.html.markdown
This file was updated about 6 years ago. Since then, there have been many changes, including a distancing from PHP. This commit is an overhaul of the previous documentation for learning Hack in Y minutes.
Over the years, there have also been many language changes and updates, for example, the introduction of Hack Arrays (vec, keyset, and dict) and the Hack Standard Language (HSL). To read more about how the language has changed and evolved, you can read the HHVM Blog: https://hhvm.com/blog/.
> [hack/en] Overhaul Hack in Y Minutes

- pt-br/git-pt.html.markdown
> [git/pt-br] Update/improve Git pt-br translation/document

- git.html.markdown
> [git/en] add code example to git-config

- pt-br/git-pt.html.markdown
> [git/pt-br] Improve wording of git-config examples

- ansible.html.markdown
> [ansible/en] added new Ansible tutorial

- hack.html.markdown
Reverting back to `php` as the `hack` header is likely not supported and the `php` highlighting is probably good enough (for now) to at least render the page.
> [hack/en] Revert update to code block header

- bf.html.markdown
> [bf/en] Dead link

- openscad.html.markdown
- [N/A] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
> [openscad/en] Add OpenSCAD learnxinyminutes

- it-it/solidity.html.markdown
Notes:
- I left some technical terms in English, because in Italy we tend to use the English expressions (I think the Italian translation would be counter-intuitive)
- I chose not to translate the code in section 9.G (it could be less readable)
- I didn't translate the images and the code linked to the Remix IDE (and Gists). Maybe done in a separate PR.
> [solidity/it-it] Solidity italian translation

- python.html.markdown
> [python/en-us] add sets to empty things that are false

- awk.html.markdown
It was either this or change the parameter to `localvar` 🤷
> [awk/en-us] fix variable declaration

- gdscript.html.markdown
> [GDScript/en] add example of iterating over an int with `for`

- gdscript.html.markdown
"it's" is a contraction of "it is"
"its" is the possessive
> [GDScript/en] Fix usage of `its`

- c.html.markdown
Bit surprised no ones spotted this before. Or perhaps there's a open issue/PR, and I simply wasn't able to spot it.
> [C/en] It's C, not c

- lua.html.markdown
> [lua/en] fix typos and minor improvements

- de-de/c++-de.html.markdown
- de-de/csharp-de.html.markdown
- de-de/qt-de.html.markdown
- es-es/c++-es.html.markdown
- fr-fr/c++-fr.html.markdown
- fr-fr/csharp-fr.html.markdown
- it-it/c++-it.html.markdown
- it-it/qt-it.html.markdown
- pt-br/c++-pt.html.markdown
- pt-br/csharp-pt.html.markdown
- pt-br/qt-pt.html.markdown
- ru-ru/c++-ru.html.markdown
- ru-ru/c-ru.html.markdown
- ru-ru/qt-ru.html.markdown
- tr-tr/c++-tr.html.markdown
- tr-tr/c-tr.html.markdown
- tr-tr/csharp-tr.html.markdown
- zh-cn/c++-cn.html.markdown
- zh-cn/csharp-cn.html.markdown
- zh-cn/qt-cn.html.markdown
- Update c++ to upercase C++
- Update c# to upercase C#
- Update c to upercase C
> [c,c++,c#/multiple languages] Convert to uppercase C/C++/C# language names

- git.html.markdown
> [git/en] add git blame

- go.html.markdown
> [go/en] fix typo

- c++.html.markdown
- csharp.html.markdown
> [c++,c#/en] Update to uppercase language name

- zh-cn/powershell-cn.html.markdown
> [powershell/zh-cn] correct mistakes 勘误

- hjson.html.markdown
> [hjson/en] add HJSON

- pt-br/tmux-pt.html.markdown
Changed a word to pt-br, fixed identation and included the command `[`
> [tmux/pt-br]Updating to latest changes in english version

- powershell.html.markdown
Jump-Location is no longer maintained and ZLocation is the declared successor.
> [powershell/en] Switch Jump-Location to ZLocation

- zh-cn/gdscript-cn.html.markdown
---
According to this pr #4327 , I made some update.
> [GDScript/zh-cn] Add `for` usage with int

- es-es/ruby-es.html.markdown
Esto se refiere al verbo "hacer", con ce; y no al verbo "haber".
> [ruby/es] Cambio de "has" por "haz"

- rdf.html.markdown
> [rdf/en] Add page for RDF (Resource Description Framework)

- rdf.html.markdown
> [rdf/en] Add RDFS further reading entry

- csharp.html.markdown
> [c#/en] Proofread parts of C#

- typescript.html.markdown
> [typescript/en] Update "Further Reading" links

- python.html.markdown
> [python/en] Clarify casting and move bool() function section

- func.html.markdown
> [funC/en-EN] added FunC intro

- zig.html.markdown
Hello everyone, this is a PR to add the Zig programming language on the website.
I don't have the website locally, but I hope the formatting is okay.
Lines are limited to 80 characters, I put the right info in the headers, I tend not to explain too much very basic concepts, etc. I'm sure this can be improved in many ways, but this already is good enough to be put online, I think. Tell me what to change otherwise.
Thanks, and merry Christmas everyone!
> [zig/en] Introduce the Zig programming language.

- pt-br/sql-pt.html.markdown
> [sql/pt-br] adding sql for pt-br language

- vim.html.markdown
Add additional commands to vim/en related to folds to expand the existing section and add visual search/replace
> [vim/en] add additional fold commands and visual regex; reformat

- pt-br/dart-pt.html.markdown
> [dart/pt-br] More natural language

- yaml.html.markdown
> [yaml/en] Add more information/examples about YAML capabilities

- python.html.markdown
> [python/en] Clarify things

- fr-fr/set-theory-fr.html.markdown
Hi, French is my native language and I think I might have found a typo regarding a pronoun in French in the original text it says 'la première élément' but seems to have a typo it should be 'le premier élément'. Just trying to be helpful. Enjoy your day. BTW I like your awesome website https://learnxinyminutes.com thanks for this cool initiative.
> [set-theory/fr-fr] Hi, I might have found a typo

- ldpl.html.markdown
> [ldpl/en] fixed spelling errors

- python.html.markdown
Edit of the lines (line breaks, edit by rephrasing, etc) to stay within the
limit set.  Exceptions are/remain the untouched links to external references.
> [python/en] stricter restraint of 80 characters/line maximum

- markdown.html.markdown
It already was mentioned, the additional link eases installation and thus promotes its subsequent use.
> [markdown/en] add link to markdownlint

- hy.html.markdown
> [hy/en] Remove dead link

- cobol.html.markdown
> [COBOL/en] Fix typo: sting → string

- bash.html.markdown
- use snake case
- fix examples
- add notes to expansions
> [bash/en] Update bash help

- pt-br/processing-pt.html.markdown
> [processing/pt_br] Adds processing translation to pt_br

- vimscript.html.markdown
> [vim/en] Delete repeated word "one" in §Intro

- awk.html.markdown
> [awk/en] keep code block within 80 characters/line (maximum)

- fr-fr/awk-fr.html.markdown
> [awk/fr] limit code block to 80 characters/line (maximum)

- es-es/awk-es.html.markdown
> [awk/es] limit the code block to 80 characters/line (max)

- docker.html.markdown
- fr-fr/set-theory-fr.html.markdown
> [docker/en] Rewriting the docs for Docker

- CONTRIBUTING.markdown
Application of markdownlint, and an additional explicit hint to the freely
available tool here may ease the future maintenance of the project.
> CONTRIBUTING, lint and hint to markdownlint

- python.html.markdown
> [python/en] Add missing json import

- fr-fr/yaml-fr.html.markdown
- yaml.html.markdown
> [yaml/en] [yaml/fr] add another example for YAML null value

- clojure.html.markdown
- es-es/clojure-es.html.markdown
- fr-fr/clojure-fr.html.markdown
- ko-kr/clojure-kr.html.markdown
- ms-my/clojure-my.html.markdown
- pt-br/clojure-pt.html.markdown
- ro-ro/clojure-ro.html.markdown
- ru-ru/clojure-ru.html.markdown
- tr-tr/clojure-tr.html.markdown
- zh-cn/clojure-cn.html.markdown
> Fix broken 4clojure links

- es-es/python-es.html.markdown
> [python/es-es] parentheses required in print functions are added

- de-de/yaml-de.html.markdown
Corrected minor typo: "Zeiangaben" -> "Zeitangaben"
> [yaml/de-de] Fixed minor typo

- python.html.markdown
> [python/en]removed tutorial that no longer exists

- bf.html.markdown
> [brainfuck/en]: add several docs & fix online interpreter url

- zh-cn/clojure-macro-cn.html.markdown
> [clojure-macros/zh-cn] Delete a unmatched parenthesis.

- r.html.markdown
I believe referring to a hash sign (`#`) as the "number symbol" is misleading. Therefore I changed it to how I think it would be clearer.
> [r/en] Specified what "number symbol" is

- mips.html.markdown
> [mips/en] MIPS fixes

- yaml.html.markdown
> [YAML/en] Fix typo

- groovy.html.markdown
> [groovy/en] Small groovy bang fix

- groovy.html.markdown
https://groovyconsole.appspot.com/
> [groovy/en] Add example with syntax to create a list with data

- pt-br/csharp-pt.html.markdown
- pt-br/visualbasic-pt.html.markdown
Grammar fix mentioned in #3684
> [csharp/pt-br] Grammar fix

- pt-br/yaml-pt.html.markdown
Issue #3684 make some changes to yaml pt-br that is still pending.
This pull request review that changes.
> [yaml/pt-br] Update yaml-pt.html.markdown

- zh-cn/ruby-cn.html.markdown
> [ruby/zh-cn] fix typo

- es-es/r-es.html.markdown
> [r/es-es] Fix typo

- ocaml.html.markdown
> [ocaml/en] Add further resources

- dynamic-programming.html.markdown
The link to a quiz on https://www.commonlounge.com/discussion/cdbbfe83bcd64281964b788969247253 is no longer valid.
> [dynamic-programming/en] Removed outdated link from dynamic-programming section.

- sql.html.markdown
Capitalization on final instance of "LIKE" was inconsistent with the standard proposed at the beginning of the article
- [N/A] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [N/ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
> [sql/en] Fixing a small capitalization error

- ocaml.html.markdown
> [ocaml/en] Proofread

- v.html.markdown
> [v/en] Adding markdown file for V

- zh-cn/c-cn.html.markdown
> [c/cn] Typedefs to typedef

- python.html.markdown
Clarify Method Resolution Order and removed duplicated concept definitions (to adhere to "explain once and just once").
> Clarify "Method Resolution Order"

- jquery.html.markdown
> [jquery/en] Add Extra whitespace in order to fix isplay problems

- kotlin.html.markdown
See https://kotlinlang.org/docs/control-flow.html#when-expression
> [kotlin/en] when is not a function, but an expression

- java.html.markdown
comment didn't relate to assignment
> [java/en] mistake fix and add missed assignment

- haskell.html.markdown
Please add an up-to-date community maintained version of the already recommended LYAH (Learn You a Haskell) tutorial.
> [haskell/en] Add up-to-date community version of LYAH tutorial

- awk.html.markdown
- es-es/awk-es.html.markdown
- fr-fr/awk-fr.html.markdown
- pt-br/awk-pt.html.markdown
- zh-cn/awk-cn.html.markdown
> [awk] Fix wrong example output (in all languages)

- python.html.markdown
ceil and floor return ints not floats - check in repl or the python3 docs here: https://docs.python.org/3/library/math.html
> [python/en] Update expected results for ceil and floor

- xml.html.markdown
> [xml/en] Fixed dead link in `xml.html.markdown`

- rust.html.markdown
> added block comments

- java.html.markdown
> [java/en] fix code formatting

- yaml.html.markdown
- [ x ] I solemnly swear that this is all original content of which I am the original author
- [ x ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [ x ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ x ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ x ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ x ] Yes, I have double-checked quotes and field names!
> [yaml/en] minor typo in boolean comment

- tact.html.markdown
> [Tact/en-EN] Added Tact lang intro

- tact.html.markdown
> [tact/en] Update Tact doc with all examples

- elisp.html.markdown
> [elisp/en] Add futher reading section and change emacs download links

- ru-ru/common-lisp-ru.html.markdown
> [common-lisp/ru] Fix broken links

- php.html.markdown
> [php/en] Add more information for strings

- lua.html.markdown
Reopening this because [my last PR](https://github.com/adambard/learnxinyminutes-docs/pull/4713) was closed due to someone just checking information about a 20 year old version of Lua and not caring about if I had any clarifications to make apparently.
> [lua/en] Fix incorrect information about numbers

- python.html.markdown
> [python/en] Clarify args and kwargs

- nim.html.markdown
- ru-ru/nim-ru.html.markdown
- zh-cn/nim-cn.html.markdown
> [nim/*] Update my website

- pt-br/set-theory-pt.html.markdown
> [set-theory/pt-br] Adds brazilian portuguese translation for set theory

- pt-br/sass-pt.html.markdown
> [scss/pt-br] fix typo

- jq.html.markdown
close: https://github.com/adambard/learnxinyminutes-docs/issues/4770
> fix 404 of jq page

- pt-br/c-pt.html.markdown
> [c/pt-br] fix untranslated english section

- powershell.html.markdown
> [powershell/en] Fix typo

- opencv.html.markdown
Fixed an error on line 177, where the variable name `aces` was used instead of `faces`.
Also added some comments that would explain the last example better to beginners.
Did not add myself as contributor.
> [opencv/en] Fixed spelling error and added comments

- tcsh.html.markdown
- replace tabs with 4 spaces
- fix markdown syntax 
- fix gramatical errors
> [tcsh/en] fix: tcsh.html.markdown

- pt-br/emacs-pt.html.markdown
> [clojure/pt-br] Create emacs-pt.html.markdown

- vi-vn/xml-vi.html.markdown
> [xml/vi-vn] add Vietnamese translation

- es-es/chapel-es.html.markdown
> [chapel/es-es] Add Spanish translation

- pt-br/d-pt.html.markdown
> [d/pt-br] Translate D to pt-br

- de-de/crystal-de.html.markdown
> [crystal/de-de] Translated crystal to German.

- m.html.markdown
Slightly re-arranged and including more explanations and links.
> [M/M] expanded m.html.markdown

- forth.html.markdown
> [forth/en] Fix expected result for one-to-12 loop

- ar-ar/sql-ar.html.markdown
Translating SQL in Arabic, names of columns, tables and databases were kept in English.
> [sql/ar] Add translation

- java.html.markdown
Moved the 'how to declare AND assign multiple integers' line from operators to right after the line on how to initlaize and assign values to multiple variables. Also changed the name of the variables and the comment technique to flow better.
Edit: forgot to initalize the variables i1 and i2 in the operators section
> [java/en] Update java.html.markdown 

- smalltalk.html.markdown
[smalltalk/en]: Rectified code snippet and Updated contact info & disclaimer
> [smalltalk/en]: Rectified code snippet and Updated contact info & disclaimer

- ballerina.html.markdown
> [ballerina/en] Add Ballerina Programming Language

- css.html.markdown
Hi! I added some information about pseudo classes. See https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links for more information.
> [css/en] link pseudo classes info added

- fa-ir/vim-fa.html.markdown
> [vim/fa-ir] Initial translation to Persian (farsi)

- pt-br/elixir-pt.html.markdown
> [elixir/pt-br]

- hocon.html.markdown
This is my first time writing as lengthy of documentation as this, so I hope I did alright! 😄 I had a bit of a hard time balancing the level of experience that the explanations were targeted towards, so if I explained certain parts too verbosely or too little, please let me know and I'll fix it ASAP!
> [hocon/en] Add HOCON

- arturo.html.markdown
**Repo:** https://github.com/arturo-lang/arturo
**Website:** https://arturo-lang.io/
----
> [arturo/en] Added Arturo tutorial

- nix.html.markdown
> [nix/en] Add `@` syntax to set pattern matching section

- sed.html.markdown
> [sed/en] Add sed page

- ATS.html.markdown
- (N/A) If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- (N/A) Yes, I have double-checked quotes and field names!
I doubt that the syntax highlighter will support ATS, so this will at the very least require some edits to figure out the best syntax highlighting.  Other than that, if there's anything else I can do to improve it, I will be happy to edit it.
> [ATS/en] Add documentation for ATS

- it-it/php-composer-it.html.markdown
- [**X**] I solemnly swear that this is all original content of which I am the original author
- [**X**] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [**X**] Pull request touches only one file (or a set of logically related files with similar changes made)
- [**X**] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [**X**] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [**X**] Yes, I have double-checked quotes and field names!
I think this can be useful for someone and this is my first pull …
> [php-composer/it] Add new translation

- docker.html.markdown
> [docker/en] Add space between $ and docker command for clarity

- janet.html.markdown
> [Janet/en] Update janet.html.markdown

- pt-pt/kotlin-pt.html.markdown
> [kotlin/pt-pt]: Added Kotlin translation for pt-pt

- python.html.markdown
> typo in learn x in y minutes python page

- asymptotic-notation.html.markdown
> [asymptotic-notation/en] Typo, add a missing n

- tailspin.html.markdown
> [Tailspin/en] Add page for the Tailspin language

- assemblyscript.html.markdown
AssemblyScript is based on TypeScript, therefore the tutorial is based on Learn Typescript in Y minutes
> [assemblyscript/en] Learn AssemblyScript in Y minutes

- lua.html.markdown
Fixes typo in url so it doesn't result in a 404
> [lua/en] Fix url

- swift.html.markdown
> [swift/en] describe convenience initializers

- go.html.markdown
corrected an error in the number pi
> Update go.html.markdown corrected an error in the number pi

- mongodb.html.markdown
> [MongoDB/en] Fix comment: wrong method

- fsharp.html.markdown
> [F#/en] added mutation

- pt-br/pug-pt.html.markdown
This commit adds the translation for the Pug documentation from English to
Brazilian Portuguese. The translated content includes an introduction to Pug,
syntax examples for tags, attributes, JavaScript usage, loops, conditionals,
including content, mixins, and additional resources. This translation aims
to make the Pug documentation more accessible to Portuguese-speaking users.
It covers the basic concepts and functionalities of Pug, providing a
comprehensive guide for developers interested in using the Pug templating
engine for HTML generation in their projects.
> [pug/pt-br] Add translation for Pug documentation

- de-de/pug-de.html.markdown
Adjusting file paths in the German language file to match the updated Pug file names for consistency and clarity of the project structure.
- Updated references from "index.png" to "index.pug"
- Updated references from "includes/nav.png" to "includes/nav.pug"
> [pug/de-de] Fix file extension in instructions about include

- httpie.html.markdown
- Add a comprehensive guide on using HTTPie as a powerful command-line HTTP client. The guide covers basic usage, URL shortcuts, optional GET and POST methods, querystring parameters, sending data in JSON, form data, and files, managing headers and authentication, as well as response handling options.
- The guide aims to provide developers, testers, and system administrators with a simple and intuitive reference for interacting with HTTP servers using HTTPie.
> [httpie/en] Add guide for using HTTPie

- jinja.html.markdown
> [jinja/en] Create page about Jinja

- zh-cn/csharp-cn.html.markdown
> [csharp/zh-cn] update translation

- hy.html.markdown
for looping seems to have updated in this version
- don't think i did change it
- copy's and pastes into the repo for me
> hy/en Update hy.html.markdown for 0.28.0

- osl.html.markdown
> [osl/en] Added OSL and covered almost everything

- ru-ru/zfs-ru.html.markdown
> [zfs/ru] Add russian translation for ZFS doc

- hu-hu/pythonlegacy-hu.html.markdown
> [python/hu-hu] Fix typo

- de-de/nix-de.html.markdown
- nix.html.markdown
- sv-se/nix-sv.html.markdown
> [nix/(en,de,sv)] link to additional documentation resources

- de-de/sql-de.html.markdown
> [sql/de] Translate sql to german

- pt-br/css-pt.html.markdown
There are some errors in the css presented that have also been corrected in this version.
> [css/pt-br] Fix some errors in the last translation.

- ja-jp/python-jp.html.markdown
> [python/ja-jp] added translations

- es-es/python-es.html.markdown
> [python/es] Update incorrect variables

- ja-jp/rust-jp.html.markdown
> [rust/ja-jp]Add traslate for rust in ja-jp

- ja-jp/css-jp.html.markdown
> [css/ja-jp] Added New Translated Document: css-jp.html.markdown

- it-it/zfs-it.html.markdown
Sync with `zfs.html.markdown` origin file.
> [zfs/it-it] Update zfs.html.markdown

- zh-cn/zfs-cn.html.markdown
Sync with `zfs.html.markdown` origin file.
> [zfs/zh-cn] Update zfs.html.markdown

- c++.html.markdown
Updated `string::length()` and `string::size()` usage demonstration for finding the length for individual strings.
Included <cstring> header to show `strlen()` usage for char* pointer or char[] array based C-compliant string length.
Got my #4887 closed due to forked repository deletion, so re-creating a PR to propose the same changes.
> [cpp/en] String length content addition

- fr-fr/c-fr.html.markdown
New C French translation c-fr.html.markdown file
> [c/fr] C French translation

- es-es/curto-es.html.markdown
> [curto/es] Add Curto lang

- zh-cn/objective-c-cn.html.markdown
> [objective-c/cn] Adding Chinese translation for Objective-C

- fr-fr/sql-fr.html.markdown
Added French translation for SQL
> [sql/fr] SQL French translation

- es-es/typescript-es.html.markdown
- fr-fr/typescript-fr.html.markdown
- hu-hu/typescript-hu.html.markdown
- it-it/typescript-it.html.markdown
- nl-nl/typescript-nl.html.markdown
- pt-br/typescript-pt.html.markdown
- ru-ru/typescript-ru.html.markdown
- th-th/typescript.th.html.markdown
- tr-tr/typescript-tr.html.markdown
- typescript.html.markdown
- vi-vn/typescript-vi.html.markdown
- zh-cn/typescript-cn.html.markdown
> [typescript/*] remove dead links and format

- sql.html.markdown
Add more inline code examples, that might be useful :
- multiline comments /* */
- ORDER BY ASC / DESC
- AS
- IN, NOT IN, BETWEEN, AND, OR
- GROUP BY, HAVING
- UNION
> [sql/en] More examples

- pcre.html.markdown
Small fix : domain name => protocol
> [pcre/en] fix domain name => protocol

- fr-fr/pcre-fr.html.markdown
Added French translation for PCRE
> [pcre/fr] PCRE French translation

- fr-fr/c-fr.html.markdown
> [c/fr] fix filename

- sql.html.markdown
> [sql/en] fix semicolons

- de-de/c-de.html.markdown
> [c/de-de] Fix typo

- de-de/opencv-de.html.markdown
> [opencv/de-de] Fix typos and spelling in German

- de-de/yaml-de.html.markdown
> [yaml/de-de] Fix typos, grammar and spelling

- de-de/asciidoc-de.html.markdown
> [asciidoc/de-de] Fix typo, grammar and spelling

- de-de/json-de.html.markdown
> [json/de-de] Fix typo

- de-de/bc.html.markdown
> [bc/de-de] Fix typos

- de-de/rst-de.html.markdown
> [rst/de-de] Fix typos, spelling and grammar

- de-de/pyqt-de.html.markdown
> [pyqt/de-de] Fix typos, spelling and grammar

- fr-fr/sql-fr.html.markdown
> [sql/fr] translation, merge en -> fr

- de-de/bf-de.html.markdown
> [bf/de-de] Fix typos, spelling and grammar

- de-de/qt-de.html.markdown
> [qt/de-de] Fix typos, spelling, grammar and translation

- de-de/python-de.html.markdown
> [python/de-de] Fix some typos

- wikitext.html.markdown
> [wikitext/en] WikiText (markdown language for Wikipedia)

- de-de/make-de.html.markdown
> [make/de-de] Fix typos, spelling and grammar

- de-de/dynamic-programming-de.html.markdown
> [dynamic-programming/de-de] Fix spelling

- de-de/bash-de.html.markdown
> [bash/de-de] Fix typo and spelling

- de-de/shutit-de.html.markdown
> [shutit/de-de] Fix typos, spelling and grammar

- de-de/clojure-macros-de.html.markdown
> [clojure-macros/de-de] Fix typos

- de-de/csharp-de.html.markdown
> [csharp/de-de] Fix typo, spelling and grammar

- de-de/dhall-de.html.markdown
> [dhall/de-de] Fix typo

- de-de/tcl-de.html.markdown
> [tcl/de-de] Fix typos

- apl.apl
Please leave a comment if you know what else this needs!
> [apl/en] Add a short APL introduction.

- apl.html.markdown
> [apl/en] format correctly

- gleam.html.markdown
This is relatively new programming language for Erlang's BEAM VM by Louis Pilfold with version 1.0.0 released recently.
> [gleam/en-us] Adding initial version of the gleam.html.markdown file

- fr-fr/javascript-fr.html.markdown
Introduce more js features. #1253
Add :
- Regex
- Ternary conditional operator
- Error handling try ... catch
- Rest parameter (ES6)
- Promise (ES6)
- Async / Await (ES2017)
- Optional chaining operator (ES2020)
- Another syntax for import
Remove :
- Duplicate spread operator (ES6)
> [javascript/fr] Add new js features

- pt-br/p5-pt.html.markdown
------
- Document the usage of p5.js library in Portuguese, aiming to facilitate learning for artists, designers, teachers, and students. Include detailed explanations and examples of key functions like setup(), draw(), and rendering shapes.
- The tutorial covers setting up the canvas, drawing shapes, handling mouse interactions, and creating animations with p5.js.
- Additionally, provide resources for further learning such as official documentation, video tutorials, and example repositories.
> [p5.js/pt-br] Add p5.js tutorial in Brazilian Portuguese

- toml.html.markdown
> [toml/en] change toml from 0.4.0 to 1.0.0

- ru-ru/dynamic-programming-ru.html.markdown
> [dynamic-programming/ru-ru] Added translation

- de-de/pug-de.html.markdown
- pug.html.markdown
> [pug/en] Fix style attribute syntax error

- nim.html.markdown
> [nim/en] Clarify Nim zero value for uninitialized variables

- rescript.html.markdown
Since ReScript is very similar to reason, this document is more or less a translation of the existing [reason tutorial](https://learnxinyminutes.com/docs/reason/) by Seth Corker (lmk if/how I should credit this). There are some breaking API and syntax changes, for which I've updated the comments and examples.
> [rescript/en] add ReScript

- de-de/java-de.html.markdown
- el-gr/java-gr.html.markdown
- fa-ir/java-fa.html.markdown
- fr-fr/java-fr.html.markdown
- id-id/java-id.html.markdown
- java.html.markdown
- pl-pl/java-pl.html.markdown
- uk-ua/java-ua.html.markdown
New link to the book "Thinking in Java" was extracted from Bruce Eckel's (author of the book) website: [MindView](https://www.mindviewllc.com/quicklinks/#java).
> [java/*] Update obsolete link to "Thinking in Java" for all [lang-code].

- es-es/racket-es.html.markdown
> [racket/es] Parameters

- vim.html.markdown
This seems a little pedantic, but calling it Normal Mode makes it easier to search online for issues you're having.
> [vim/en] Replace Command Mode with Normal Mode

- id-id/php-id.html.markdown
> [php/id-id] Fixed the typos & updated the translation

- rust.html.markdown
The article is deep, yet to the point and serves as a good "index" of sorts. It also helps those coming from other languages to piece together what Rust syntax means in their "native" language (yes, I mean programming language).
> [rust/en] Added link to fasterthanli.me

- linker.html.markdown
> [linker/en] translate russian docs to english

- es-es/make-es.html.markdown
> [make/es] Translate make to spanish

- pt-br/lambda-calculus-pt.html.markdown
> [lambda-calculus/pt-br] Lambda Calculus portuguese translation

- openmp.html.markdown
Added documentation for openMP, C/C++ parallel programming tool.
> [OpenMP/en] Added documentation for OpenMP

- de-de/clojure-de.html.markdown
> [clojure/de] Translate clojure to german

- ru-ru/javascript-ru.html.markdown
Fix link to Javascript Garden + change link protocols to https
> [javascript/ru] Update link in docs with https.

- es-es/elisp-es.html.markdown
- ms-my/elisp-my.html.markdown
- pt-br/elisp-pt.html.markdown
- zh-cn/elisp-cn.html.markdown
See #4735 and #4522 
I hope the article doesn't need to change for these, ChatGPT 4 said they don't.
> [elisp/*] minibuffer -> echo area

- hcl.html.markdown
> [hcl/en] Add guide for Terraform / HCL language

- it-it/logtalk-it.html.markdown
- logtalk.html.markdown
> [logtalk/en] [logtalk/it-it] Update Logtalk docs for the current major version of the language

- kdb+.html.markdown
> [kdb+/en] Update KX links

- id-id/php-id.html.markdown
> [php/id] rename function

- raylib.html.markdown
> [raylib/en] Updated example

- ko-kr/clojure-macros-kr.html.markdown
> [clojure-macros/ko-kr] add: ko-kr/clojure-macros-kr.html.markdown

- ko-kr/common-lisp-kr.html.markdown
> [common-lisp/ko-kr] add: ko-kr/common-lisp-kr.html.markdown

- qml.html.markdown
> [qml/en] Add QML tutorial

- python.html.markdown
> [python/en] "rounds down" -> "rounds towards zero"

- golfscript.html.markdown
> [GolfScript/en] 

- smalltalk.html.markdown
Added new method 'separate' to the Array section.
> [smalltalk/en] add mixed type array

- chapel.html.markdown
Chapel has changed a lot since this page last updated. And this PR syncs with latest version.
Also resolves https://github.com/chapel-lang/chapel/issues/12671.
> [Chapel/en] Update chapel.html.markdown

- yaml.html.markdown
Correct an error explaining the example of "Merge Key Language-Independent Type" of YAML
> [yaml] Fix an example

- golfscript.html.markdown
Added some nifty string tricks.
> `[golfscript/en-en]` Update golfscript.html.markdown

- bqn.html.markdown
> [bqn/en] Add BQN tutorial

- miniscript.html.markdown
> [miniscript/en] Add MiniScript documentation.

- kotlin.html.markdown
Adds a section introducing lambda functions and their syntax *before* their use in higher-order functions.
- [X ] I solemnly swear that this is all original content of which I am the original author
> [kotlin/en] Add small section for lambda functions.

- typescript.html.markdown
Add example of optional type and unwrapping the type
> [typescript/en] multiple types

- dart.html.markdown
Added final vars as variable sources for copy, updated comments in one style, updated failing examples
> [dart/en-en] Updated exercise 11

- dart.html.markdown
Added more concise and clear introduction to using booleans and checked null comparison.
> [dart/en-en] Updated example14

- it-it/fish-it.html.markdown
Adding full Italian translation of fish shell, by a native Italian speaker.
> [fish/it-it] Translation, merge en -> it

- go.html.markdown
+ map value when  key doesn't exist is 0 in case of map[string]int
+ common use case to check to see if key exist in the map
> [go/en] missing map keys

- nim.html.markdown
Add example of objects and reference objects.
Add small example to tuple section, to explain how objects differ from tuples.
> [nim/en] add objects and ref objects

- rescript.html.markdown
Removes some deprecated features/syntax and changes one standard library call.
> [rescript/en] update ReScript tutorial

- apl.html.markdown
* Add the further reading section, which includes link to the APL wiki, a older version of APL book
by the creator of APL, and some additional books.
> [apl/en]: Add Further Reading section

- de-de/d-de.html.markdown
> [d/de-de] Fix typo, spelling

- de-de/crystal-de.html.markdown
> [crystal/de-de] Fix typo

- de-de/haml-de.html.markdown
> [haml/de-de] Fix typo

- fr-fr/bash-fr.html.markdown
> [bash/fr-fr] update based on [bash/en]

- zh-cn/lua-cn.html.markdown
> [lua/zh-cn] 增加lua相关“模块”注意事项

- gleam.html.markdown
- golfscript.html.markdown
> Remove unsupported highlight languages

- be-by/python-by.html.markdown
> [python/be] fix translator link

- ca-es/go-ca.html.markdown
The Go wiki on GitHub has moved to go.dev 
The old link was broken, Updating the link ensures doc remains accurate and helpful.
> [go/ca-es] Update go.html.markdown 

- c++.html.markdown
I just think someone added a line between the comment and what it actually refers to and this could be confusing to some.
> [c++/en] Move comment in c++.html.markdown

- c++.html.markdown
> [c++/en] fixing typo

- zh-cn/markdown-cn.html.markdown
> [markdown/zh-cn] Update the translation

- phix.html.markdown
> [phix/en]: Add "+" output

- java.html.markdown
> [java/en] Fix mix usage of spaces and tabs as indents

- de-de/paren-de.html.markdown
> [paren/de-de] Fix some typos

- de-de/edn-de.html.markdown
> [edn/de-de] Fix typo

- miniscript.html.markdown
> [miniscript/en] Fix typos

- de-de/clojure-de.html.markdown
> [clojure/de-de] Fix typos, grammar and spelling

- de-de/elm-de.html.markdown
> [elm/de-de] Fix typos and spelling

- montilang.html.markdown
> [montilang/en] Fix typos

- de-de/sql-de.html.markdown
> [sql/de-de] Fix typos, spelling and grammar

- powershell.html.markdown
- [✅] I solemnly swear that this is all original content of which I am the original author
- [✅] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [✅] Pull request touches only one file (or a set of logically related files with similar changes made)
Before:
...
[System.Collections.Hashtable]$b = @{}  # => Point **a** at a new hash table
...
After:
...
[System.Collections.Hashtable]$b = @{}  # => Point **b** at a new hash table
...
Change:
In the comment - from "Point **a** at..." to "Point **b** at..." because the variable **b** is being pointed at the new hash table, not variable **a**
> [powershell/en] Fixed Typo

- de-de/lua-de.html.markdown
> [lua/de-de] Fix typos

- sorbet.html.markdown
> [sorbet/en] Fix typo

- sing.html.markdown
> [sing/en] Fix typo

- de-de/asciidoc-de.html.markdown
> [asciidoc/de-de] Fix typos

- linker.html.markdown
> [linker/en] Fix missing translation

- tr-tr/gdscript-tr.html.markdown
> [GDScript/tr-tr]

- es-es/rst-es.html.markdown
>  [RST/es-es] Included translation of RST into spanish.

- fish.html.markdown
- it-it/fish-it.html.markdown
1. [fish/*] `fish_path_add` -> `fish_add_path`
According to the [fish document](https://fishshell.com/docs/current/cmds/fish_add_path.html), the command is `fish_add_path` rather than `fish_path_add`
2. [fish/en] `qoutation` -> `quotation`
There's no word named `qoutation`, and easily to guess it would be `quotation`
3. [fish/*] drop the equal sign for `set name = 'My Variable'`
fish's set variable is `set VAR VAL` ([document](https://fishshell.com/docs/current/cmds/set.html))
> [fish/*] Fix typos and mistakes

- sed.html.markdown
> [sed/en] Fix typo

- gleam.html.markdown
> [gleam/en] Fixed grammar mistakes 

- de-de/haskell-de.html.markdown
Resolves #5116 - Comment introducing !! index operator moved up / added , following English version.
> [haskell/de-de] Added missing comment line about index operator

- java.html.markdown
Update Java language features introduced in recents versions.
- [] Yes, I have double-checked quotes and field names!
> [java/en] Update java.html.markdown with modern Java updates

- jinja.html.markdown
> [jinja/en] Fixes bullet point rendering issue

- lean4.html.markdown
> [lean/en] space before colon

- ru-ru/d-ru.html.markdown
Update contributor links. 
* Add HTTPS
* dprogramming.ru is long gone and leads to a SEO junk website
* lhs-blog.info moved to lhs.su. lhs-blog.info is some SEO-junk now
> [d/ru] Update d-ru.html.markdown

- zh-tw/javascript-tw.html.markdown
> [javascript/zh-tw] translate

- zh-tw/javascript-tw.html.markdown
- zh-tw/typescript-tw.html.markdown
> [typescript/zh-tw] translate

- bg-bg/perl-bg.html.markdown
- ca-es/go-ca.html.markdown
- ca-es/groovy-ca.html.markdown
- cs-cz/go.html.markdown
- cue.html.markdown
- es-es/go-es.html.markdown
- es-es/perl-es.html.markdown
- es-es/raku-es.html.markdown
- fi-fi/go-fi.html.markdown
- fr-fr/go-fr.html.markdown
- fr-fr/perl-fr.html.markdown
- go.html.markdown
- it-it/go-it.html.markdown
- ko-kr/go-kr.html.markdown
- perl.html.markdown
- pl-pl/perl-pl.html.markdown
- pt-br/go-pt.html.markdown
- pt-br/perl-pt.html.markdown
- red.html.markdown
- sing.html.markdown
- tr-tr/c-tr.html.markdown
- tr-tr/ruby-tr.html.markdown
- uk-ua/go-ua.html.markdown
- zh-cn/java-cn.html.markdown
- zh-cn/javascript-cn.html.markdown
- zh-cn/perl-cn.html.markdown
- zh-cn/red-cn.html.markdown
- zh-tw/javascript-tw.html.markdown
- zh-tw/perl-tw.html.markdown
> Remove "name:" from frontmatter

- CONTRIBUTING.markdown
Hi.
Of all the changes, the one I’d most recommend keeping is removal of `then` duplication.
<br>
<br>
Additionally
- installing bundler could be happier as a part of Ruby installation
- since repo nesting is a bit unusual, it could get more emphasis
Since macOS ships with Ruby, there's a potential to remove Ruby installation part. However, because it's [adviced](https://www.freecodecamp.org/news/do-not-use-mac-system-ruby-do-this-instead/) not to install gems on the system Ruby, better to keep that part of docs.
<br>
> docs: edit contributing, how to build

- qsharp.html.markdown
- [N/A] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
The Q# language has evolved a bit since this example was last updated. This PR updates the example code to compile in the modern compiler, runs the canonical formatter on it, updates the syntax highlighting to the now-supported `qsharp` syntax highlighter, and updates the references to the latest content we've published.
> [qsharp/en-us] Update qsharp example

- es-es/javascript-es.html.markdown
Update javascript-es.html.markdown
If you say cada x tiempo it's mean that the function repeats every 5 seconds, and setTimeOut only runs one time after x milliseconds
- [ x] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/mast …
> [javascript/es]

- janet.md
- [ ✓] I solemnly swear that this is all original content of which I am the original author
- [ ✓] Pull request title is prepended with `[language/lang-code]` (example `[python/fr]` or `[java/en]`)
- [✓ ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [✓ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
Janet for Mortals is a great book with a built in repl for testing/learning.
> [janet/en] Adds external ebook link for further reading.

- zh-cn/nix.md
> [nix/zh-cn] Add translation

- es/python.md
updating operations
- [xx] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.md)
> [python/es] include module and pow

- typescript.md
\
Removes the implication that `for ... in` iterates over numerical keys of the array
> [typescript/en] For ... in iterates over all enumerable *string* properties

- uk-ua/typescript-ua.html.markdown
- [+] I solemnly swear that this is all original content of which I am the original author
- [+] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [+] Pull request touches only one file (or a set of logically related files with similar changes made)
- [+] Yes, I have double-checked quotes and field names!
> [typescript/uk-ua] Added ukranian translation

- c++.md
> [C++/en] Typo

- nix.md
Just a simple change from the term Antiquotation to String Interpolation as it appears on [nix.dev](https://nix.dev/tutorials/nix-language#string-interpolation)
> [nix/en] update to string interpolation

- de/csharp.md
> [c#/de] typos

- de/clojure.md
> [clojure/de] Balance parens

- fr/clojure.md
> [clojure/fr] Balance parens

- ms/clojure.md
> [clojure/ms] Balance parens

- zig.md
idea from https://www.reddit.com/r/Zig/comments/1ivzd4a/comment/meb8rvq/
> [language/zig] simpler multidimensional arrays

- fr/bash.md
> [bash/fr] Fix typos

- uxntal.md
`#30` (hex) = 48 (dec) = "0", so that's where the loop starts.
cc @neauoire (original author) 
- ~~[ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.md)~~
> uxnta/enl: Fix comment about what exactly is printed

- csv.html.markdown
> [csv/en] New language CSV

- it/c.md
- [ X] I solemnly swear that this is all original content of which I am the original author
- [ X] Pull request title is prepended with `[language/lang-code]` (example `[python/fr]` for Python in French or `[java]` for multiple Java translations)
- [ X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.md)
> [c/it] adding Italian translation of C file

- tr/git.md
> [git/tr] Fixes a confusion between regex and glob

- bash.md
> [bash/en] Added -z and -n string conditional operators

- python.md
> [python/en] Match/Case Statement 

- solidity.md
This came with many changes, including but not limited to:
- Added SPDX license identifiers - compilers throw a warning otherwise
- Removed outdated overflow warnings - Solidity 0.8+ has built-in overflow/underflow protection, making manual SafeMath checks unnecessary
- Updated msg.sender casting to payable(msg.sender) - required in 0.8+ for type safety
- Deprecated selfdestruct function with warning about EIP-6780 changes - reflects current security best practices
- Removed deprecated var keyword - replaced with explicit type declarations
- Removed outdated testnet section - Kovan testnet is deprecated (and testnet funds are VERY hard to get these days)
- Added modern development tools - Foundry, Cyfrin Updraft
- Removed deprecated tools - Superblocks Lab, EthFiddle, Truffle
- Updated …
> feat: refactored for 0.8.19 of solidity

- es/csv.md
> [csv/es] Add Spanish translation for CSV

- odin.md
> [odin/en] Add Odin.md

- zh-cn/c.md
> [c/zh-cn] Add the missing semicolons

- odin.md
Related issue: https://github.com/adambard/learnxinyminutes-docs/issues/5370
> [odin/en] Fix various mistakes and clarify verbiage
