adambard/learnxinyminutes-docs

scala.html.markdown

Scala compiler fails to infer the return type of the function when there's an explicit return statement used in the function

[scala] Fixed function return type

---

ja-jp/julia-jp.html.markdown

Sorry, I missed writing `lang: ja-jp` in #894, and made a new Julia language tree in the top page.

[julia/ja] Added missing `lang: ja-jp`

---

swift.html.markdown

Without going into too much detail, mention optional chaining so it's
not confusing that there is a question mark suffix (it's not currently
mentioned anywhere on the page).

Explain Optional Chaining

---

asymptotic-notation.html.markdown

I gave this a re-read through but would definitely appreciate several more sets of eyes reading over it....
Is this clear?
Not enough explanation? Too much?
I worry this is too short to actually grasp the concept, but I think it's enough to get a basic understanding?
Once this gets cleared/merged I plan on writing up a doc on Analyzing Algorithms (big oh notation application https://github.com/adambard/learnxinyminutes-docs/issues/526#issuecomment-41224568).

asymptotic notation rough draft

---

ocaml.html.markdown

Change the example to a meaningful and self-contained example of mutually recursive functions.
And fix a typo.

[ocaml/en] Change the example of mutually recursive functions

---

css.html.markdown

[attr~='foo'] will not select <el attr="foobar">, it will only select <el attr="bar foo baz">
Also added definition for [attr|='pre'] style selector
Refs: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors, http://jsfiddle.net/awalGarg/72k3ptsk/

[css/en] corrected definition of ~ selector, added |

---

ru-ru/lua-ru.html.markdown

I'm not exactly familiar with LearnXinYMinutes-site parser. But if we replace the lowercase letter 'l' for a capital 'L', ru version of Lua is displayed on the main page. Please check this.

[lua/ru] a probable solution #957

---

hack.html.markdown

I had assumed a relative link to another markdown file in this project would work, but it renders as:
http://learnxinyminutes.com/docs/hack/php.html.markdown
instead of the desired:
http://learnxinyminutes.com/docs/php/
I've replaced this relative link with an absolute link to where the target page is located on the published site. This commit also fixes a typo in markdown syntax at the end of the document.
If there's an alternative way you'd prefer for this internal link to work, let me know.

[hack/en] Fix link to other learnxinyminutes article

---

javascript.html.markdown

Added a semicolon to conform with statement at top of guide:
// Because those cases can cause unexpected results, we'll keep on using
// semicolons in this guide.

[Javascript/en] Add semicolon to maximine consistency.

---

haskell.html.markdown

This way, it is clear what [1..] !! 999 means later on.

Moved explanation of indexing into a list earlier

---

perl6.html.markdown

It seems "when" should be replace by "given" at the end of the comment line.

Perl6, minor change in comments

---

asymptotic-notation.html.markdown

Everywhere I see it online references it as 'Big-O' or 'Big O'. Not sure why my books use Big-Oh. Don't want to cause any confusion with 'Big-Oh', so I renamed it all.

Renamed Big-Oh to more prevalent name, Big-O.

---

typescript.html.markdown

Cleaned up mixed tabs/spaces
Wrapped lines at 80 characters
Fixed incorrect comment regarding property name
I took some liberty in cleaning things up while I was fixing #990 (fixed [here](https://github.com/NPrescott/learnxinyminutes-docs/commit/2ae3d41c2749645fec4748c764ccd5c9405424e5#diff-2a430f897f1d70dad08d5561446c10caR66)). I modified the spacing after `//` to be more in line with [Microsoft's examples](https://github.com/Microsoft/TypeScriptSamples).

[typescript/en] Fix formatting, close #990

---

perl6.html.markdown

A curly bracket is facing the wrong direction. Small but important.

Minor typo: fixed curly bracket direction (} -> {)

---

haskell.html.markdown

The right side of '$' is evaluated first, then the result is passed to the left side

Update haskell.html.markdown. Wrong explanation about '$' operator

---

c.html.markdown

0x0f is of type int, for 32-bit int the result is 0xfffffff0.
31'st bit is the sign bit of a 32-bit wide int.

c.html: fix #1021 (bitwise negation and shifting into the sign bit)

---

perl6.html.markdown

($_.chars > 50) ~~ True : this is always True.

Update perl6.html.markdown // when and smartmatch

---

clojure-macros.html.markdown

Just correcting the spelling of the word 'arithmetic' in a comment.

Fixed spelling of 'arithmetic' in Clojure Macros tutorial.

---

common-lisp.html.markdown

Earlier version was incorrect, as it only executed `body` once and then terminated, like an if statement instead.

fix the while macro for Common Lisp

---

c++.html.markdown

Neither gcc nor clang accept void main. Remove this bad information. Tested as follows:
$ cat 045.cpp
void main()
{
}
$ g++ 045.cpp
045.cpp:1:11: error: ‘::main’ must return ‘int’
void main()
^
$ clang++ 045.cpp
045.cpp:1:1: error: 'main' must return 'int'
void main()
^~~~
int
1 error generated.
$ g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
$ clang++ --version
Ubuntu clang version 3.4.2-3ubuntu2~xedgers (tags/RELEASE_34/dot2-final) (based on LLVM 3.4.2)

Neither gcc nor clang accept void main.

---

bash.html.markdown

ALL_CAPS variable names are traditionally "reserved" for use by the
shell/system.
(People often try to use PATH for things locally and then wonder why their
commands all stop working for example.)

[bash/en] Don't use ALL_CAPS variable names.

---

perl6.html.markdown

Also mention MoarVM before JVM.

[Perl 6] tweak. Parrot desupported on Rakudo.

---

rust.html.markdown

I'm updating the introductory information to reflect the current situation after the release of Rust 1.0 today. I haven't yet checked if this release makes any change in the rest of the document needed due to changes in the language.
More information on the Rust 1.0 release here:
http://blog.rust-lang.org/2015/05/15/Rust-1.0.html

Updating rust.html.markdown for Rust 1.0

---

erlang.html.markdown

* Add missing square brackets in example of pattern matching on lists
* Keep lines under 80 characters
* Hiphenate complex modifiers (e.g. "pattern-matching operation")
* Consistently proper case the language name
* Improve punctuation in comments
* Properly format Markdown inline code
* Tense changes (where appropriate)

[erlang/en] Various (mostly cosmetic) improvements

---

elisp.html.markdown

Now the regular expression is back to what it was and align with how it is in
other languages. Also it aligns with the commented description of the regular
expression, (`The regular expression is "Bonjour \\(.+\\)!" and it reads:`)

editorial revert of a change, remove trailing whitespace

---

compojure.html.markdown

Using strings doesn't work for the POST/PUT examples here, changing them to keywords fixes this

Use keywords in POST/PUT examples

---

c++.html.markdown

Removed the `void` return type from the Dog class constructor and destructor, since constructors and destructors do not have return types. Changed the call to `printDog` to just `print`, matching what was declared in the class. Also added a few missing semicolons.

[c++/en] Fix a few coding errors.

---

c++.html.markdown

Made the template example class Box have a public member function so it works when that function is called later on. Also removed the string arguments from the std::exception constructors, because std::exception constructors only either take no argurments or another std::exception object.

[c++/en] Make code compileable.

---

groovy.html.markdown

Was pointing to Codehaus, now defunct.

Corrected link to Groovy documentatin

---

rust.html.markdown

Now that Rust is stable at 1.0 saying "in-development" might not be appropriate any more.

Remove in-development from Rust's description

---

python3.html.markdown

Fixes issue #1148. The reasoning is well explained by the issue.
One can also refer to the [docs], showing it is more idiomatic to use `next()`.
[docs]: https://www.python.org/dev/peps/pep-3114/#double-underscore-methods-and-built-in-functions

[python3/en] Use `next()` instead of `__next__()`

---

tr-tr/csharp-tr.html.markdown

Both were set to LearnCSharp.cs, so the live site has been serving the Turkish version for English.

Fix 'filename' collision between csharp{,-tr}.html.markdown

---

chapel.html.markdown

Added sync, single and atomic variables.
Added reductions and scans.
Because max/minloc require the values and indices to be in a zippered iterator, I included a demonstration of zippered iterators along with the previous iterator example. 
Further, made a number of spelling, grammar, wording, punctuation changes, and corrected/clarified some erroneous/misleading comments (mainly things about consts and params)
Included the `--set` compiler option in the Notable arguments 'section'.

Chapel: Sync, atomics, reductions, scans, zippered iterators

---

swift.html.markdown

In Swift 2, println will no longer work. Changed all println's to print, for compatibility with both Swift 2 and Swift 1.2.

Println deprecated in Swift 2, added name

---

chapel.html.markdown

This is quite the doozie.
Added modules and main() proc.
Added range/domain/array slicing.
Added array assignment (which is part of array slicing) and loop expressions, which necessitated a deeper dive into zipped iterators to explain why some expressions would work, and why some wouldn't.
Added a fix because `<THESE THINGS>` were missing from the Notable arguments section.
A small change was made in one or two places to keep within the 80 column specifications.

[Chapel] Modules, main(), range/domain/array slicing and array assignment, loop expressions, zipped iterators

---

red.html.markdown

Change the chat room reference from Stack Overflow chat to Gitter.im, and add a link to the "Red" Stack Overflow tag.

update "further reading" links

---

perl6.html.markdown

0 is not falsey for a long time. For example, see this blog post: https://p6weekly.wordpress.com/2015/04/13/2015-15-we-figured-out-the-truth-about-0/
> Something that may have surprised a lot of people (myself included) was that Perl 6 claims that the truth value of “0” ought to be False. That is no longer the case, and so the rule for the truth value of strings is now just “does it have any characters in it?”. I think that’s more sensible.

In perl6, 0 is not falsey anymore

---

tcl.html.markdown

Github's syntax-highlighting has an error in the Tcl syntax-parser causing the rendering of the page to fail about one third in.
See the following screenshot:
This commit bypasses this rendering-error by resetting the syntax highlighting after the error has occurred.

Tcl. Fix mid-page rendering error

---

python3.html.markdown

This fixes two SyntaxErrors caused by invalid syntax of the print() function.

[Python3/en] Corrected Python3 print() function

---

csharp.html.markdown

It should be made clear that the part before the ternary operator is
indeed a condition, most often created as some comparison expression.

[csharp/en] Put demonstrative condition into ternary expression

---

de-de/csharp-de.html.markdown
fr-fr/csharp-fr.html.markdown
tr-tr/csharp-tr.html.markdown
zh-cn/csharp-cn.html.markdown

It should be made clear that the part before the ternary operator is
indeed a condition, most often created as some comparison expression.
the same change for the English version has just been merged (see closed issue  #1333)

[csharp/de,fr,tr,cn] Put demonstrative condition into ternary expression

---

markdown.html.markdown

Line 163 was missing a character to denote the HTML comment (shown as `<---` instead of `<!---`), which was causing everything subsequently to be rendered as code block, as the triple back tick wasn't being escaped as part of a comment

markdown example: fixed missing ! to create an actual comment

---

ruby-ecosystem.html.markdown

Ruby 1.9.3 reached end of life in Feb 2015 as is stated in https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/ 
Is good to anyone to know that 2.x.x are the only rubies which get official security patches

[ruby-ecosystem/en] Ruby 1.9.x is also retired

---

swift.html.markdown

Original link directs to page that can't be found. Changed to represent new location of the Apple Developer tutorial on swift.

[swift/en] Updated link to correct page

---

nl-nl/brainfuck-nl.html.markdown

The Dutch notation for large numbers is with a `.` instead of a `,`

[brainfuck/nl] Fix dutch notation for large numbers

---

javascript.html.markdown

[javascript/en] Added for/in loop JavaScript

---

perl6.html.markdown

the output for this example of the ff operator is wrong. This PR fixes it

[perl6] fix the output of ff example

---

fr-fr/scala.html.markdown
scala.html.markdown

The Scala tutorials had some small bugs, namely:
* Attempting to use an immutable variable `x` to control a loop;
* Uncommented code that would not compile, as it's not valid scala;
* Undefined lists and case classes;
* Two filenames;
This errors are also fixed on the pt-pt version (PR #1316).

Fix compile errors of the English and French Scala tutorials

---

pt-pt/scala-pt.html.markdown

This PR adds a Portuguese translation of the Scala tutorial.
I tested the code and it seems to be working as expected. This is my first pull request for this project though, so I might have missed something from the guidelines (eg. do I need to include the code in a separate `learn-pt.scala` file somewhere, or is it automagically generated?).

Add pt-pt translation for Scala tutorial

---

csharp.html.markdown

Clarified that the base class name must be the first thing listed

Added detail on C# single inheritance

---

c++.html.markdown

Clarified that private members are inherited but are not directly
accessible

[C++/en] Small inheritance clarification

---

csharp.html.markdown

Just a small fix to the setter example and I altered the word "yields" to "returns" due to "yield" being a keyword which might confuse.
There are now a ton of warnings, but after installing entity framework the code as it stands does compile! :)

Fixed the custom indexer example (setter return type is void)

---

fr-fr/haml-fr.html.markdown

Header configuration was missing `lang` field.

[haml/fr] Add lang to header

---

json.html.markdown

Original version indicated that commas are placed before _values_ in JSON, which is incorrect.

[json/en] Fixed incorrect information about commas in JSON doc

---

python.html.markdown

Add fact that Python 2 is reaching end of life. 
And note that you can use `__future__` to add Python 2 and 3 compatible code.

Update Python 2 vs Python 3

---

xml.html.markdown

In latter examples, some <title> tags had spaces near the end of the opening tag (possibly because later examples omit the 'lang' attribute of it)

[xml/en] Superfluous spaces removed in some tags in 'XML'

---

c.html.markdown

with obligatory conventional warning

[c/en] clarify that args' names are not required in proto

---

c.html.markdown

```
int foo () {
printf("bar\n");
int x; // this is not valid in C89+
}
```

[c/en] clarify common tripping point of newbies

---

latex.html.markdown

I've fixed some little typos in this article. Maybe the most important is to reference everywhere LaTeX as "LaTeX" (neither "latex" nor "Latex"), like as the beginning of the article. It's a little bit weird to read it referenced in three different ways.

[latex/en] Fix some typos in LaTeX article

---

perl6.html.markdown

The project main page lists only Rakudo as a compiler.

Removed references to compilers other than the Rakudo.

---

README.markdown
latex.html.markdown

Corrects "passes master" to "passes muster" in the README. Minor typo.

[README] Fix typo in README

---

it-it/brainfuck-it.html.markdown

The Italian translation for brainfuck had a lot of typos and some syntax errors, which I should have fixed now.
I also made the description of the example programs easier to read.

[brainfuck/it] Fixed typos and syntax errors

---

csharp.html.markdown
elixir.html.markdown

I tried clarifying that any parameter passed in as an out parameter will hold the value assigned to it outside of the scope of the function.
I noticed weird spacing issues after my commit, so I fixed them.

Added information about out parameters in C#

---

git.html.markdown

While translating git.html.markdown to Italian, I found a mistake: `git pull` does not default to `git pull origin master`. By default, it updates the current branch by merging changes from its remote-tracking branch.

[git/en] Fixed 'git pull' documentation

---

git.html.markdown

The 'git push' documentation had the same problem of the 'git pull' one I just fixed.

[git/en] Fixed 'git push' documentation

---

php.html.markdown

There was no reference to late static binding in the document, so added a working example. Let me know if this needs work.

[php/en] Adds late static binding

---

julia.html.markdown

Julia supports underscores at the beginning of a variable name now. It also supports a subset of Unicode code points for the first character, and additional code points for subsequent characters.
A full explanation of all available code points was excluded as it is quite complicated and doesn't add much value in the X in Y context.
closes #516

Update Julia variable names

---

java.html.markdown
xml.html.markdown

Fixed a few minor typos and refactored the wording of Map definition so it did not plagarize JavaDocs

Typo fixes and refactor description of Java Map

---

python.html.markdown

Adding documentation on C's '?:' ternary operator equivalent in Python. 
Since, a lot of people from C/C++/Java might use this documentation, they would look for a ternary operator equivalent in Python. 
This was not mentioned explicitly, even though ternary operator is used in the documentation.
What do you think? @levibostian, @adambard. Please let me know. Thanks.

[python/en] Adding documentation on ternary operator

---

haskell.html.markdown

The example: (5 + 10) * 5, might cause a slight confusion regarding which 5 is the function argument. This update should make it very straightforward.

Modify the function composition example to avoid two 5's

---

php.html.markdown

Somebody beefed a closing on the 'Late Static Binding' Comment block, causing the next 18 or so lines to be included in the comment instead of parsed for syntax properly.

[php/en] Un-beef a comment block closing

---

javascript.html.markdown

As discussed in issue #1623, the extra "feedback" section has been removed. Furthermore, I went and fixed the markdown formatting of the links.
I did not add myself as a contributor, as I merely worked on formatting. My attribution lies within the commit history!

[js/en] Remove "feedback", fix link markdown

---

haskell.html.markdown

- Use a finite list, as infinite lists are not introduced yet
- Use a list starting from 1 instead of 0, to make it obvious that
the element returned comes from the list (and is not the second
argument to !!).

[haskell/en]: Fix !! operator

---

python.html.markdown

calling li.index(2) with li as [1, 2, 3, 4, 5, 6] will return 1 not 3

[python] Minor correction

---

objective-c.html.markdown

As the title. Covers the basic case.

[Objective-C/en] Adds description of how to define generic classes in Xcode 7.0

---

objective-c.html.markdown

`#pragma mark` is very useful and widely recommended to "abuse" it for method/variable grouping since it improves readability.

Added pragma mark information

---

python.html.markdown

String templates doesn't need to have a number of keyword to format.

Add one more string formatting example

---

de-de/haskell-de.html.markdown
de-de/yaml-de.html.markdown

Replaced ae/oe/ue with ä/ö/ü where appropriate.
I did a "grep" in the de-de directory, i've only found
problems in haskell and yaml files.

[haskell/de] [yaml/de] Fix umlauts

---

ruby.html.markdown

As per these two merged PRs ([#1](https://github.com/adambard/learnxinyminutes-docs/pull/1908), [#2](https://github.com/adambard/learnxinyminutes-docs/pull/1909)), adds Jake Faris as a contributor to the Ruby file.

[Ruby] Adds JF to contributors

---

fr-fr/markdown.html.markdown

Currently, the file name causes the French version to override the original one.

[markdown/fr] Corrects the filename

---

python3.html.markdown

`math.sqrt(16)` returns `4.0` instead of `4`

[python3/en] Correct math.sqrt(16)

---

julia.html.markdown

A small typo mistake "arguements" -> "arguments"

[julia/en] Fix a typo is julia.html.markdown

---

perl6.html.markdown

I made this PR based on this conversation: http://irclog.perlgeek.de/perl6/2015-11-17#i_11554028 but when I tried to come up with a shorter example, I couldn't reproduce the `$!` not being set inside the `CATCH`, so now I'm unsure whether this PR is correct.
I'll leave it up to you to see whether the correction is needed.

Perl6: $! is not available inside the CATCH{} (Possibly)

---

ruby.html.markdown

1. Replace `Hash#has_key?` with `Hash#key?`
2. Replace `Hash#has_value?` with `Hash#value?`
As per the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#hash-key), `Hash#key?` and `Hash#value?` should be preferred to `Hash#has_key?` and `Hash#has_value?`.

[ruby/en] Replace Hash#has_key? with Hash#key?

---

csharp.html.markdown

Clarified grammar in LearnCSharp comment about naming files relative to the classes they contain. Otherwise the two comment lines blended together and were a little confusing.

[C#/en] Grammar/clarity update in comments about File Naming

---

erlang.html.markdown

Replaced 'or' with a semicolons since the paragraph above is talking about using semicolons

[erlang/en] Replaced 'or' with a semicolons

---

yaml.html.markdown

Because some YAML parser will always assume that 1 is boolean for true.

Add a note regarding string value of "1"

---

powershell.html.markdown

apparently ````powershell` does not render a code block on the .com website
so I've removed the 'powershell' part

PowerShell/en: poor website render

---

swift.html.markdown

'T()' is initialisation/creation, 'x as T' is casting

[swift/en] Correct "Casting" mention in swift markdown

---

matlab.html.markdown

i have fixed some typing mistakes two mistakes were in the same line and in other mistake the name of the function is written wrongly in the comment.

[matlab/en] fixed typo mistakes

---

haskell.html.markdown

Current text states that Haskell is "easy" to install. Unfortunately it isn't, much of the time. I removed this boosterism. Secondly, beginners need to know that there are two commonly used options for installing Haskell; especially because the newer, Stack, produces a working dev environment more reliably.

[Haskell] Updating dev environment installation info

---

coldfusion.html.markdown

The pre block was already inside a pre/code block in the rendered page, making it harder to read as they weren't being converted to the corresponding brackets (< or >).
Here's what I was seeing in the rendered page:

ColdFusion replaced &lt; and &gt; in pre block

---

c.html.markdown

Another pitfall, as not all languages have fall-through in switches.

[C/en] Added tidbit about fall-though in switch statements.

---

csharp.html.markdown

over using "extension functions", it's more accurate.

[C#/en] Fix to "extension methods"

---

cs-cz/markdown.html.markdown

I haven't tested this patch, but it seems that the missing parameter is causing 'markdown' to be displayed twice on the front page.
Thanks for awesome work btw!

[markdown/cz] Fix missing 'lang' in front matter

---

de-de/latex-de.html.markdown

Fix a sentence, added a command to be able to define multiline comment blocks. Additionally, make use of the \LaTeX command to correctly show the LaTeX logo.

[latex-de] Corrections and improvements to the german LaTeX document

---

perl6.html.markdown

The comments state that Foo::Bar::inc in the package variable example should increase $Foo::Bar::n and then print it.
This did not happen, as `say ++$n;` was placed outside the block of the sub Foo::Bar::inc.
The commit puts `say ++$n;` inside the block of Foo::Bar::inc.

[perl 6] changed code output to as stated in comments

---

perl6.html.markdown

Corrected spelling of ‘subroutine’ as described in issue #2075

Fix typo referenced in Issue #2075

---

swift.html.markdown

As Xcode switched to Markdown syntax, I've updated it.
Based on http://nshipster.com/swift-documentation/

[swift/en] Updated documentation syntax - small fix

---

swift.html.markdown

Documentation syntax is no longer reStructuredText,
It's "Swift-flavored version of Markdown"
http://nshipster.com/swift-documentation/

[Swift/en] Updated comment on documentation of Swift functions

---

swift.html.markdown

this line 
let weak = "keyword"; let override = "another keyword" // statements can be separated by a semi-colon
show off semicolon use. But after that semicolon is not used, so I removed inconsistency.

[Swift/en] Deleted semicolon to be consistent - Small Fix

---

haskell.html.markdown

- Added the :i command, as i feel that it is as useful as :t.
- Added another example for :t, hopefully showcasing it's flexibility
- For consistency, changed the name of (.) from function to operator
(as is already the case with ($)), and added a short remark in the
GHCi section that (most) operators are also functions.

[haskell/en] Extended section on GHCi (discussion?)

---

ruby.html.markdown

For Ruby, add one note on destructuring assignment (`him, her = ["Duchovny", "Anderson"]`) and one on bang and boolean naming conventions.

[Ruby] Naming conventions and destructuring assignment

---

haskell.html.markdown

I just noted that the example claiming that (add 10) is the same as (+10) was wrong. (A detail - it should be (10+) to match the argument order.) Then I just continued down making a few similar fixes and terminology updates. 
Kind regards,
Patrik
PS. I've been teaching [Advanced Functional Programming](http://www.cse.chalmers.se/edu/course/afp/) (in Haskell) for a few years at Chalmers.

Some minor fixes

---

python3.html.markdown

Adding documentation on C's '?:' ternary operator equivalent in Python 3.
This is similar to the PR #1560, which was about adding ternary operator documentation in Python 2.7.
Please review this. @levibostian. Thanks.

[python3/en] Adding documentation on ternary operator

---

groovy.html.markdown

Let's use the correct term instead of the tongue-in-cheek term denoting the same concept.

memoize not memorize

---

java.html.markdown

Introducing this disrupts the flow a little bit to think, if specifying `new boolean[] ` required when intializing.

new boolean[]  not really required when initializing.

---

elixir.html.markdown

Just fixing a broken link but to an important learning resource.

Fixing broken link to Elixir's Getting Started documentation

---

ko-kr/erlang-kr.html.markdown

This modification adds Korean translation for Erlang.
I have added Korean translation `Programming Erlang` to `References`.

[erlang/ko-kr] Adds Korean translation for Erlang

---

elixir.html.markdown

In Elixir, a variable is only bound within the scope where it is declared.
In particular, a variable matched within a `case` statement will not be bound outside of the statement, see [official tutorial](http://elixir-lang.org/getting-started/case-cond-and-if.html#case).

[exlixir/en] Unclear statement on variable scope

---

python.html.markdown
python3.html.markdown

Just a small note on importing modules for python that can save some debugging time should you have a file with a generic name in a multi-file project.

[python/en] Add note about Python Module Order of Import

---

hy.html.markdown

Added some more recent hy changes (class syntax, `cut` instead of slice), as well as some missing operators (`->` and `->>`) and function declarations (using `&rest` and `&kwargs` along with `apply`).
Also changed the code block syntax to hy since github recognises it.

[hy] Updating, elaborating and cleaning some rust

---

csharp.html.markdown

Just an expansion of the XML documentation example, the <param> tag can be very useful in Visual Studio, especially.

Expanded XML Doc example

---

latex.html.markdown

Simply corrects a typo in a comment on the LaTeX table

[LaTeX/en] Typo: table columns are separated by '&'

---

perl6.html.markdown

The name of the variable used is $val, but the code calls say $rand. This pull request corrects that.

[perl6/en] Fixed instance where wrong variable name was used

---

c.html.markdown

This is a fix for the English C page, which used two variables both named "size".  I don't anticipate this happening too often, but if someone were to copy and paste the entire file and try to compile it, an error will spring up.  To ease this burden, I changed one of the variables to "array_size", as the role of the variable was to demonstrate variable length arrays based on user input.

[c/en] issue 2205: Change variable 'size' to 'array_size'

---

latex.html.markdown

Using the $ sign for invite command in the `verbatim` environment messes with syntax highlighting, which stays in math mode for the rest of the document. Using > is an easy fix.

[latex/en] Replace invite sign $ by > in compilation example

---

perl.html.markdown

Primarily formatting changes to prevent weird wrapping in some browsers. Replaced $a with $x in regex examples, since $a is a reserved global variable (for sort) so it's not good to use in examples.

[perl/en] Fix line formatting and use $x instead of $a

---

tcl.html.markdown

Make it exactly the same as the block before, but without braces.

[tcl/en] tcl: fix error in no-braces example

---

pt-br/c++-pt.html.markdown

I only fix `reuturn` replacing by `return`.

[c++/pt-br] Fix some typos

---

go.html.markdown

Corrected closure example that referenced assigning x to e^10, which does not happen in this iteration. Set x to a value large enough to make the comments hold true in the closure example.

[go/en] Updated variable references

---

php.html.markdown

The '$$' before the braces was a bit confusing. I added a couple lines that show that you have options on where the '$' goes when it comes to curly braces in strings.

Change curly braces statement

---

scala.html.markdown

[scala/en] Add example of an int is divided by a double

---

rust.html.markdown

Small tweak to get the comment bit to be updated per https://doc.rust-lang.org/book/comments.html.
`/* */` comments no longer exist.
Multiline comments just use `//` on each line, and the `///` comments are for documentation (which can include markdown)

[rust/en] Updating comment examples

---

tmux.html.markdown

These options are no longer valid in recent versions of tmux. See https://github.com/tmux/tmux/issues/230.

Remove obsolete utf-8 options.

---

elisp.html.markdown

This fixes a tiny typo in elisp article.
It says: _Some function are interactive_
It should say: _Some functions are interactive_

[elisp/en] Fix tiny typo

---

zh-cn/go-cn.html.markdown

---
zh-cn/go-cn.html.markdown | 2 +-
1 file changed, 1 insertion(+), 1 deletion(-)

go: [zh-cn] fix a typo.

---

cs-cz/javascript.html.markdown

I noticed that the modulo division example was missing in the czech version so I added it.

added missing modulo division

---

cs-cz/javascript.html.markdown

I've added some more javascript examples that were missing in the czech version.

added missing js examples for czech translation

---

python3.html.markdown

There were several resources here that teach Python 2, but not Python 3. I removed them so that a reader will only see resources that apply to Python 3.

[python3/en] Remove Python 2 resources

---

id-id/markdown.html.markdown
it-it/rust-it.html.markdown
pt-br/elixir.html.markdown

These tutorials are appearing as separate entries rather than as translations.

adding missing lang entries to headers for 3 tutorials

---

es-es/asymptotic-notation-es.html.markdown

I'm modifying the "asymptotic-notation-es" file because the material from the link is in spanish.
Resource Link added: material elaborated by teachers of the course "Programación 3" (Algorithms and Data Structures) with examples about calculating the order of an algorithm and other topics in the context of asymptotic notation.
This material is publicly listed here: https://eva.fing.edu.uy/pluginfile.php/95278/mod_resource/content/0/Apuntes%20sobre%20An%C3%A1lisis%20de%20Algoritmos.pdf but I uploaded it to Scribd because I know that the link could eventually change since it's hosted in a moodle platform and now and then the teachers change the location of the files.

[asymptotic-notation/es] add new resource link

---

c.html.markdown

To avoid using the concept pointer before it has been introduced,
previously it is changed to array.
But as @geoffliu pointed out,
array initialization using string literals is not introduced either.
So this commit uses neither pointer nor array.
Discussing `i++` and `++i` does not need to involve pointer or array.
---
c.html.markdown | 6 ++----
1 file changed, 2 insertions(+), 4 deletions(-)

c: init array with string literals not introduced.

---

bash.html.markdown

Link pointed to a book which was not released. Fixes #2372.

[bash/en] Remove link unavailable resource (#2372)

---

python3.html.markdown

The python3 equivalent of 'A Crash Course in Python for Scientists' has been added.       
[Source](https://www.reddit.com/r/IPython/comments/1hkqx4/crash_course_in_python_for_scientists/cavmopr)

[python3/en] Add 'A Crash Course in Python for Scientists'

---

de-de/rust-de.html.markdown
fr-fr/rust-fr.html.markdown
it-it/rust-it.html.markdown
rust.html.markdown
zh-cn/rust-cn.html.markdown

[rust/de] [rust/en] [rust/es] [rust/fr] [rust/cn] Fix comment in Rust docs: box -> mine

---

de-de/swift-de.html.markdown
es-es/swift-es.html.markdown
pt-br/swift-pt.html.markdown
pt-pt/swift.html.markdown
ru-ru/swift-ru.html.markdown
swift.html.markdown
zh-cn/swift-cn.html.markdown

[swift/all] Update Swift pre-decrement syntax to match v3.0

---

rust-pt.html.markdown

Added a translation of Rust from EN to PT_BR.

[rust/pt-br] initial translation

---

elixir.html.markdown

This PR is meant to address issue #2334.

[elixir/en] Adds elixir documentation on the pipe operator.

---

pt-br/c-pt.html.markdown

In translation for pt_br, has a mistake when written #define.

[c/pt_br]Fix correct name #define

---

perl6.html.markdown

Perl6: Explain that Integers Can't be Passed and Modified in Sub's Even If Using `is rw´

Perl6: Explain that Integers Can't be Passed and Modified in Sub's Even If Using `is rw´

---

perl6.html.markdown

Add many more smartmatch examples. Make the ternary operator clearer and add a code example for it. Make the section for && and || have a working code example and show the output it gives.
If this is all good so far I will keep making changes.  Let me know what you think.

Perl6: Add many more smartmatch examples. Make the ternary operator clearer

---

pt-br/clojure-macros-pt.html.markdown

Links were positioned inside a code block, preventing markdown
to parse links to HTML version

[clojure-macros/pt_br] Fixing references links positioning

---

ru-ru/markdown-ru.html.markdown
ru-ru/typescript-ru.html.markdown
zh-cn/vim-cn.html.markdown

Fix tutorials not generating for the following reasons:
* Missing quotes
* Missing brackets
* Fullwidth commas instead of normal commas

Fix for the three tutorials with broken YAML markup, causing them not to be accessible at all or show up in the index

---

php.html.markdown

This is a minor patch and updates English PHP language code style according to the [PSR-2](http://www.php-fig.org/psr/psr-2/) (which is also mentioned in the document so far). In case anything else needs to be done or it is insufficient to be merged, let me know. I'll gladly send more updates, but I would rather do that in smaller steps over the next pull requests, to be more easily manageable.
Thank you for considering merging it.
Kind regards.

[php/en] Normalize PHP code style a bit according to PSR-2

---

c++.html.markdown

Space should be removed.
before:
// concatenated_tuple becomes = (10, 'A', 1e9, 15, 11, 'A' ,3.14141)
after:
// concatenated_tuple becomes = (10, 'A', 1e9, 15, 11, 'A', 3.14141)
Typo initialize is correct form.
before:
map<char, int> mymap;  // Will initalize the map with key as char and value as int
after:
map<char, int> mymap;  // Will initialize the map with key as char and value as int
Typo corresponding  is correct form.
before:
// To find the value correponsing to a key
after:
// To find the value corresponding to a key

c++/en typo, formatting fixes

---

c.html.markdown

C should be capitalized.
Before:
// there is no Boolean type in c. We use ints instead.
After:
// there is no Boolean type in C. We use ints instead.
Before:
Header files are an important part of c as they allow for the connection of c
After:
Header files are an important part of C as they allow for the connection of C
Before:
Header files are syntactically similar to c source files but reside in ".h"
After:
Header files are syntactically similar to C source files but reside in ".h"
Before:
files. They can be included in your c source file by using the precompiler
After:
files. They can be included in your C source file by using the precompiler
Before:
as the c file.
After:
as the C file.
Before:
/* should instead be put in a c file.                                       */
After:
/* …

C/en typo, formatting fixes

---

angularjs.html.markdown

The last three of the above "tasks" don't seem to apply, this is a documentation change, specifically to an existing entry.
There looked to be some confused markdown usage; this has been corrected. For instance, in the first paragraph of the "What You Should Already Know", the list looks okay in the source markdown file on GitHub, but the rendered html page displayed the list items inline with the asterisk. There were a couple other locations, the section on filters and the footer, with resource links, where bolding an attempt at bolding some key words wasn't completed; the ones in the footer had a list of resources, but weren't actually rendered lists, converted.
Example, before, rendered html on live site:

fixes bullet/list issues in AngularJS markdown

---

scala.html.markdown

implicts -> implicits
Implicts is a real word synonymous with implies, but in this case the word should have been "implicits," as in implicit values. 
Also changed "favourite" -> "favorite" (US spelling) for consistency since the default language option seems to be "en-us."

[scala/en] Fixed confusing typo

---

go.html.markdown

A coworker asked about reasons to use the underscore variable placeholder, so I decided to add some examples:
- Example of using underscore to discard the error
- Example of using underscore to loop over values of a slice
- Incidentally, example of writing to a file

[go] added practical examples for the underscore

---

red.html.markdown

Changing the formatting of comments so that lines are always less than 80 characters. 
In fact, I erred on the side of caution so that comments are normally only go to around 76-77 chars.

[red/en] changing the formatting of comments so that lines are always <80chars.

---

solidity.html.markdown

http://solidity.readthedocs.io/en/develop/style-guide.html#contract-and-library-names

[solidity/en] solidity contract name convention CamelCase to CapWords

---

erlang.html.markdown

It updates an old link, and changes the way the URL is formated.
It shouldn't be markdown style as it's inside a comment

Update Guard Sequences link and change format

---

erlang.html.markdown

it uses a named id, not a number

[erlang] Update guard sequences URL to use named id

---

forth.html.markdown

Simple commit to fix the broken syntax highlighting for the english `forth` guide.

[forth/en] Use forth syntax highlighting

---

perl.html.markdown

- [-] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [-] Yes, I have double-checked quotes and field names!

[perl/en] how to write to files

---

swift.html.markdown

[swift\en] Added nil-coalescing operator

---

elisp.html.markdown

Used https://github.com/adambard/learnxinyminutes-docs/blob/f835be4f02a6a855d4ade9f296fa29aaa71b647e/common-lisp.html.markdown as reference.

Brief explanation about ' (quote)

---

it-it/logtalk-it.html.markdown

[logtalk/it-it] Enable syntax coloring for code blocks

---

python3.html.markdown

Under section 6. Classes, the "getter" examples should return "Ian: 42" and "Joel: 0" respectively instead of integers, since they're wrapped in calls to "say". Here's what's the page said originally:
```
i.say(i.age)                    # => 42
j.say(j.age)                    # => 0
```
Hope this helps!

[python3/en] Fix two "getter" output examples

---

logtalk.html.markdown

[logtalk/en] fix typo in example code

---

it-it/logtalk-it.html.markdown

[logtalk/it-it] fix typo in example code

---

python3.html.markdown

A fix on static method section (around line 728).
Specifically, i.grunt() should raise an error since grunt() is a static method and 'i' is an instance of the class.
- [ X] I solemnly swear that this is all original content of which I am the original author
- [ X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ X] Yes, I have double-checked quotes and field names!

[python3/en] Updated mistake in Python3/en tutorial

---

purescript.html.markdown

https://github.com/purescript/purescript/wiki/Differences-from-Haskell
...says:
> Since 0.9.1, the Prelude library does not contain (++) as a second alias for append / (<>) (mappend in Haskell) anymore.
So:
```
-- Concatenate
"such " ++ "amaze" -- "such amaze"
```
...should read:
```
-- Concatenate
"such " <> "amaze" -- "such amaze"
```

Updating the PureScript string concatenation.

---

Gemfile.lock

Makes sure the tests are ran with a working charlock_holmes gem
e.g. prevents this from happening:
https://github.com/brianmario/charlock_holmes/issues/78
-  Pull request title is prepended with `[language/lang-code]`
- If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- Yes, I have double-checked quotes and field names!

Adds Gemfile.lock to lock charlock_holmes gem

---

chapel.html.markdown

The Chapel repository includes variant of this 'language tour', which
was recently modified in various ways:
- the overwhelming majority of the diff involves style and formatting changes to
more closely mimic the style of other examples in the Chapel repo.
- Additional examples of where-clauses and generics
- fixes an incorrect example of a reversed range
- improvements to comments

[chapel/en] Style and example changes for Chapel

---

racket.html.markdown

Per #2714 , 
Fixed incorrect name in mutable struct access and setting examples.

[racket/en] Fix Incorrect Names in Mutable Struct Examples (per Issue #2714)

---

perl.html.markdown

It's unnecessary to use double quotes for strings with no variables or escape codes. Also explains an example of variable interpolation in a string.

[perl/en] Use more single quotes and explain single vs double quotes

---

zfs.html.markdown

This commit will fix the incorrect bullet point markdown to allow proper html
generation. The markdown should have a linebreak before the first item of
the list. 
The bullet pointed list currently looks like this:
The bullet points are not generated and everything is displayed inline.
-----

[zfs/en] Fix bullet points

---

shutit.html.markdown

- [ x Pull request title is prepended with `[language/lang-code]`

[shutit/en] tweaks for prompt in outputs and backslash escaping

---

javascript.html.markdown

This PR contains a commit fixing a typo within the prototype section.  Specifically, a printed version of a variable should be 43, not 42.

[Javascript/en]Corrects typo in prototype section.

---

php.html.markdown

There is unnecessary semicolon after while loop.

[PHP/en]Fix small typo in PHP English tutorial

---

python3.html.markdown

'filled_set' was not defined before attempting to add to it, resulting in a NameError. 
Alternative would be to use 'some_set' for all examples and change each instance of 'filled_set' to 'some_set' across lines 348, 352, 355, 370, 371.

[python3/en] Fix Typo python3.html.markdown

---

go.html.markdown

more clear explanation why interface is consider defined without specifically declaring it (like in other languages `pair implement Stringer`)
- [ x] Yes, I have double-checked quotes …

[go/en] more clear explanation for interface

---

de-de/scala-de.html.markdown

Backport changes made to English translation explaining trait keywords. See #2760
docs/blob/master/CONTRIBUTING.markdown)

[scala/de] Backport traits keyword explanation

---

json.html.markdown

I *think* this fixes a broken bullet list on the JSON article. :)

[json/en] add carriage return to fix broken bullet list

---

standard-ml.html.markdown

The REPL complains as follows on specifying the deleted line
```
fun say Red   = "You are red!"
=   | say Green = "You are green!"
=   | say Blue  = "You are blue!"
=   | say _     = raise Fail "Unknown color";
stdIn:171.5-174.43 Error: match redundant
Red => ...
Green => ...
Blue => ...
-->   _ => ...
```

[standard-ml/en] Redundancy is not permitted in pattern matching

---

c++.html.markdown

fixed errors:
- "vector_name" and "Vector_name" (different case) would have resulted in a compile time error, now: "my_vector"
enhancements:
- typedef for consistency
- two push_backs to show its purpose
- both iteration types now have a working execution block (both output the vector's content)
- the first "classic loop" now also shows the operator [], which therefor is removed from below
- include and for with a white spaces for readability

[c++/en] container -> vector

---

ru-ru/.directory

This is a clutter left by [Dolphin file manager](https://userbase.kde.org/Dolphin) which has no use here.

[ru/all] Remove Dolphin's clutter from the repository

---

asciidoc.html.markdown
de-de/asciidoc-de.html.markdown
id-id/asciidoc-id.html.markdown
pt-br/asciidoc-pt.html.markdown

[asciidoc/en,de,is,pt] Fixed wrong section titles in AsciiDoc

---

perl6.html.markdown

Fixed the meta note for #2271, but realized it addressed formatting that was changed in an earlier commit, and that other commits left inconsistent formatting of comments throughout. Attempted to reformat for consistency and to maintain 80 column lines.

[perl6/en] Formatting consistency

---

zfs.html.markdown

Really simple markdown fix for #2313, where unordered lists require a blank line to precede bullet items.

[zfs/en] Fix for unordered lists not rendering properly

---

c.html.markdown

The goto example stops when the sum of the two integers is 150. This happens when the first variable is 51 and the second one is 99 (the current file says i = 52, j = 99, which is obviously 151). The existing online versions further confirms this.

[c/en] Correct off-by-one error

---

chapel.html.markdown

+ Chapel is now version 1.16.0
+ The syntax highlighter does *not* like single quotes `'` mixed with double quotes `"`. I have removed what appear to be the worst offenders.

[chapel/en] Chapel version update, mixed quotes

---

clojure-macros.html.markdown

Remove unnecessary closing parenthesis from inline-2 macro.

[clojure-macros/en] Fix typo

---

bash.html.markdown

Using echo with ' ' means that the variable won't be expanded, so it should print the literal $Variable instead of some string.
- [ x ] I solemnly swear that this is all original content of which I am the original author
- [ x ] Pull request title is prepended with `[language/lang-code]`
- [ x ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ x ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ x ] Yes, I have double-checked quotes and field names!

[bash/en] Edited output on line 59

---

it-it/html-it.html.markdown

The missing declaration caused the Italian version show up as a duplicate HTML article on the live site, becoming the parent of every further translation. Same basic issue as [PR#2573](https://github.com/adambard/learnxinyminutes-docs/issues/2573).

[html/it] add missing lang declaration to html-it

---

dynamic-programming.html.markdown

The issue this fixes can be seen at the live [Dynamic Programming page](https://learnxinyminutes.com/docs/dynamic-programming/), the unescaped underscores are picked up as markdown formatting in the word `largest_sequences_so_far`, making it appear as largest _sequences_ so_far

[dynamic-programming/en] add backticks to escape markdown formatting characters

---

edn.html.markdown

EDN symbols do not start with a # character
here's the relevant spec on the canonical edn github readme: https://github.com/edn-format/edn#symbols

[edn] Fix incorrect format for EDN symbols

---

edn.html.markdown

- Change Clojure code to eliminate errors and to match commented output
> Change edn/read-string to clojure.edn/read-string (no _require_ in text)
> Change map->menu-item to map->MenuItem to match defrecord and output
- Modify the text to make it easier to understand the given example

[edn/en] Improve the "Tagged Elements" section

---

chapel.html.markdown

Chapel changed their home site from chapel.cray.com to chapel-lang.org.
All chapel links are changed, have been tested, and currently work.
All links were tested as well, and all currently work.
Also, I changed my (Ian J. Bertolacci) collaborators link to my new institution.

[chapel/en] Update links

---

cs-cz/elm.html.markdown
elm.html.markdown
pt-br/elm-pt.html.markdown

Elm has no longer functions `fst` and `snd` to access tuple values and they're no longer part of the Basics. Instead `Tuple` functions `first` and `second` have to be used. The change is documented in the [upgrade-docs/0.18.md](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md#renamed-functions-in-core)
Change made in en, cs-cz and pt-br (all currently existing elm files).

[elm] Update code to access tuples

---

solidity.html.markdown

Adds reference to the free resource EthFiddle, which is the JsFiddle for Solidity. Compilable, interactive, shareable and embeddable playground for Solidity.

[solidity/en] Add Ethfiddle to solidity docs

---

go.html.markdown

Small typo in command line command

[go/en] Small typo

---

zh-cn/kotlin-cn.html.markdown

Change the expression of some sentences to be more idiomatically for Chinese.

[kotlin/zh-cn] More idiomatically

---

yaml.html.markdown

Greetings,
I'm one of the creators of the YAML language. This doc page is already really good. I hope this PR can make it better.
Note: I programmatically checked the validity of the YAML.
From the commit msg:
* YAML allows literal tabs in content, but not indentation.
* Two space indent always preferred.
* Note: YAML dumpers always use 2 space by default.
* '- ...' doesn't need extra indentation.
* Note: YAML dumpers don't use extra indentation.
* There was no mention of single quoted strings. They are preferred
and should be used except when double quote semantics are actually
required. (Best practice).
* Add flow form example for sets: `{a, b, c}`
* Show collapsed form of seq-in-seq: `- - - foo`.

[yaml/en] Use preferred style; add missing uses

---

pythonstatcomp.html.markdown

IPython still exists, but the notebooks have been spun off into their own project called Jupyter. This file change:
* updates the pip install queue so that Jupyter gets installed
* removes the vague "get set up with IPython" (pip will install IPython with Jupyter), and
* replaced the suggestion to work in "the IPython notebook" with "a Jupyter notebook".

[pythonstatcomp/en] IPython notebooks are Jupyter notebooks now

---

prolog.html.markdown

Fixed typo in expected result, changed 'deterministic' jargon to its full name

[prolog/en] Fixed typo and changed jargon to its full name

---

de-de/make-de.html.markdown
make.html.markdown

Fix for wrong use of parenthesis: You can't mix curly and plain braces in Make:
$ make test
makefile:2: *** Nicht abgeschlossene Variablenreferenz.  Schluss.
$ 
Please note that the files had 99% `\r\n` line endings, so I also corrected the missing `\r\n` endings for lines that were added with `\n` only by other authors.

[make/en || de] Fix for wrong/mixed parenthesis usage.

---

nim.html.markdown

This pull request:
- Fixes the multiline Nim comment affecting the rest of the markdown preview. (#3031)
- Removes the commentary on indentation. Since these guides target intermediate to experienced programmers, they should already know that comments can be formatted however one pleases.
- Clarifies that although Nim supports nested comments, not all programming languages do.

[nim/en] Fix the multiline Nim comment (#3031)

---

toml.html.markdown

Enhances the TOML documnetation by adding a clarifying example to the `Datetime` section using an RFC 3339/ISO 8601 offset, and clarifies and grammaticalizes the surrounding text.

[toml/en] add clarifying example and text for date/time offsets

---

python3.html.markdown

Literal string interpolation is new in python 3.6 [pep-0498](https://www.python.org/dev/peps/pep-0498/)

[python3/en] added example for f-string

---

chapel.html.markdown

Changes:
+ Made version agnostic. Chapel has a twice yearly release (this year there were 3), and making changes here every time it does is just unnecessary. Makes it more difficult to do the build code, as you can no longer copy commands. I thought about using `chapel-*`, but thought that was poor form.
+ Removed a testing marker that made it's way into the tutorial.
+ Removed 'unnecessary' trailing white space (Atom).
+ Added Gitter chat as way to interact with developers.
+ Points users to official documentation describing compiler build process.

[chapel/en] Chapel versioning

---

bash.html.markdown

Maybe just a zsh quirk? 
➜  ~ echo ${Variable:0:Length} 
zsh: unrecognized modifier

missing $ on line 77 - $Length

---

javascript.html.markdown

The annoted version by Gordon Zhu, of the book "Eloquent Javascript" by Marijn Haverbeke, is not available anymore. Therefore I deleted the link to it.
I suggest to insert a new link pointing to the new material (https://watchandcode.com/courses/practical-javascript) on Javascript by Gordon Zhu, since I think it's very valuable content. I can make it myself, with another pull request, by I'll wait for the administrator permission.

[javascript/en-us] Delete broken link to Eloquent Javascript - The Annotated Version

---

scala.html.markdown

Solves #2724 
Previously the `return z` didn't actually have any effect on the output, since the outer function just returned the anon function's result directly. Updated to make the outer function do something with the return value to demonstrate the difference. Also renamed functions to make what they're doing easier to follow, and added a couple examples of behavior with accompanying explanations.

[scala/en] Make return value example actually demonstrate issue

---

zh-cn/typescript-cn.html.markdown

- Add space between chinese and english words to make content more readable.
- Add some new content about `const` updated by [typescript/en] .
- Change from `var` to `let` to make code more TypeScript.
- Change string double quotation  to single quotation.
- Fix some ambiguous translation.

[typescript/zh-cn] Fix space style and little content

---

ruby.html.markdown

This fixes a small typo in the ruby documentation ("Tt"-->"It").

[ruby/en] Fix typo for ruby

---

tcl.html.markdown

Tcl is moving from tcl.tk to tcl-lang.org (I have first-hand knowledge)

[Tcl/en] update tcl hyperlinks

---

latex.html.markdown

This fixes basic LaTeX mistakes:
- paragraphs are separated by empty lines, never by `\\`
- In case a LaTeX command is invoked without parameters, the correct syntax is `\command{}` and not `\command \hspace{1pt}`, because the space between words is not always 1pt, but can vary
- fix spacing after "etc." (huge mistake often made)

[latex/en-en] Fix paragraph separation, inter-word space, add microtype package

---

racket.html.markdown

This is really a minor issue.
Index number for the `Functions` sections is numbered `3.` -- just like the `Structs and Collections` section before it.
This fixes section numbering for `Functions` and all subsequent sections.

[racket/en] Fix section numbering

---

c++.html.markdown

Probably it was its original place, just after templates are introduced,
and before first usage of container types.

[C++/en] Move section about containers to its logical place

---

ocaml.html.markdown

[ocaml/en] Fix typo

---

latex.html.markdown

[latex/en] Fix comment on using \ after abbreviations

---

julia.html.markdown

This is a better order I think.
Show the normal way to print before showing the use of the `Printf` stdlib.
Also finish doing string examples before moving on to printing

[julia/en] tweak order of string functions / print functions

---

powershell.html.markdown

There was a stray backslash in the powershell page. The Spanish version didn't have this issue.

[powershell/en] Fix typo in powershell page

---

cs-cz/python3.html.markdown
de-de/python-de.html.markdown
de-de/python3-de.html.markdown
es-es/python-es.html.markdown
fr-fr/python-fr.html.markdown
hu-hu/python-hu.html.markdown
it-it/python-it.html.markdown
ko-kr/python-kr.html.markdown
pl-pl/python-pl.html.markdown
pt-br/python-pt.html.markdown
pt-br/python3-pt.html.markdown
python.html.markdown
ro-ro/python-ro.html.markdown
ru-ru/python-ru.html.markdown
tr-tr/python-tr.html.markdown
uk-ua/python-ua.html.markdown
zh-cn/python-cn.html.markdown
zh-tw/python-tw.html.markdown

Both in Python 2.7.10 and Python 3.6.5, math.sqrt() returns a float and not int. It seems like a tiny thing but sometimes may lead up to bigger confusions. For example: https://stackoverflow.com/questions/54474037/why-are-the-following-codes-giving-me-different-output-square-root-big-numbers/54475501#54475501

[python/all] Type correction for the output of math.sqrt()

---

crystal.html.markdown

Sources for the change:
https://crystal-lang.org/api/0.27.2/UInt128.html
https://crystal-lang.org/api/0.27.2/Int128.html

[crystal/en] Add new Int128 and UInt128 types

---

julia.html.markdown

Something that may trip users coming from a Python background as per https://discourse.julialang.org/t/julia-messes-up-integer-exponents/20773

[julia/en] Add note about integer overflow

---

haxe.html.markdown

The file looked too messy with many less-than-4-line comments block-commented. Also made some uniformity formatting cleanups (such as numbers of blank lines). Maybe most importantly, shortened or reformatted long lines that were breaking in the final html page making things look too messy as well.
Also added missing Haxe targets at the top of the doc (Python, Lua, HashLink).

[Haxe/en] whitespace and uniformity cleanups

---

CONTRIBUTING.markdown
awk.html.markdown
cmake.html.markdown
de-de/make-de.html.markdown
es-es/awk-es.html.markdown
es-es/pythonstatcomp-es.html.markdown
fr-fr/awk-fr.html.markdown
fr-fr/make-fr.html.markdown
make.html.markdown
pt-br/awk-pt.html.markdown
pt-br/cmake-pt.html.markdown
pt-br/make-pt.html.markdown
tcsh.html.markdown
zh-cn/awk-cn.html.markdown
zh-cn/make-cn.html.markdown

Move the following articles:
- awk _(main, es-es, fr-fr, pt-br, zh-cn)_
- cmake _(main, pt-br)_
- make _(main, de-de, fr-fr, pt-br, zh-cn)_
- tcsh _(main)_
- Statistical Computing with Python _(es-es)_
... to the "tools" category.
Bonus: the ES translation of "Statistical Computing with Python" didn't show up on the homepage because "Computing" was written with a lowercase "C" whereas it's a capital C in the english article -- fixed this.

[Global] Update tools category

---

elisp.html.markdown

https://www.gnu.org/software/emacs/manual/html_node/elisp/nil-and-t.html

[elisp/en] t evaluates to itself, so it doesn't need to be quoted

---

standard-ml.html.markdown

How to declare a new value of the temp custom datatype which can be either C (Celsius) or F (Fahrenheit) is not obvious for an intermediate programmer with no SML experience. I think it would be better to demonstrate the declaration of such a value.
I solemnly swear that this is all original content of which I am the original author

[SML/en] Added a comment to better demonstrate custom datatypes.

---

chapel.html.markdown

Constructors have been deprecated as of Chapel 1.18

Updated initialiser

---

perl.html.markdown

The variable `max` was not declared before use in demonstrating how for loops work over ranges.  It has been added on line 155 and set to a value of 5

[perl5/en] Fixed variable not declared before use.

---

zh-cn/make-cn.html.markdown

> \# This rule will only run if file0.txt is newer than file1.txt.
Here translated into Chinese is "file0.txt 比 file1.txt 新"

[make/zh-cn] fix: typo

---

fsharp.html.markdown

Updated the pattern matching for lists to show how to get head of a list when you don't care how many other elements are in the list.

(fsharp/en) List Pattern Matching first element of "many"

---

vyper.html.markdown

Multidimensional array syntax was wrong, now fixed
- [ √ ] I solemnly swear that this is all original content of which I am the original author
- [ √ ] Pull request title is prepended with `[language/lang-code]`
- [ √ ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ √ ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ √ ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ √ ] Yes, I have double-checked quotes and field names!

[vyper/en] Update vyper.html.markdown

---

wolfram.html.markdown

"Puce -> 3.5" was added to myHash before Keys[mhHash] and Values[myHash]

[wolfram\en] Correct output

---

perl6.html.markdown

The postfix ++ operator increments its argument but returns its old value. In the document, after incrementing a container with value 42, it said it would output 43. However it outputs 42.
https://docs.perl6.org/language/operators#postfix_++

[perl6/en] Fixed output 

---

yaml.html.markdown

I was a bit confused whether I needed to manually encode utf-8/16/32 characters in yaml. This site states only ascii is supported:
https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#yaml-supports-only-plain-ascii
Linters / validators like listed below however don't mark yaml with utf-8/16/32 characters as invalid.
http://www.yamllint.com/
https://yamlvalidator.com/
The following stack overflow states that the encoding is done at the file level and is transparent to the YAML and its parsing.
https://stackoverflow.com/a/648335/1544200
In a personal project I've found no issues when including utf-8/16/32 characters like æ, ² directly in yaml. 
So I'm not sure... I hope we can add something to the yaml examples that can clarify this.

[yaml/en] UTF-8/16/32 characters need to be encoded

---

swift.html.markdown

The renderer on the website doesn't recognize Swift multi-line strings, so a bunch of the file was treated as a string literal. This adds another " in the multi-line string to balance it out

[Swift/en] Fix quoted multi-line string

---

typescript.html.markdown

The input list is of int[] [@line236](https://github.com/adambard/learnxinyminutes-docs/blame/master/typescript.html.markdown#L236]) but the output of its shown is in string [@line238](https://github.com/adambard/learnxinyminutes-docs/blame/master/typescript.html.markdown#L238]). same thing happens at [@line244](https://github.com/adambard/learnxinyminutes-docs/blame/master/typescript.html.markdown#L244])

[typescript/en] Fixed int array output which was shown as string

---

tmux.html.markdown

To enter copy mode we use `[` and not `]`.

[tmux/en] Fix keybinding

---

nix.html.markdown

- nix-repl now deprecated, Nix 2 has `nix repl`
- nix now also has floats and float-integer arithmetic
- add note about immutable sets' attributes being un-redefinable
- descendant sets can now have attributes added to them

[nix/en] Updates for Nix 2.2.0

---

rust.html.markdown

This PR contains 2 small fixes:
1. Explanation of string slices:
Slices (string slices included) are not backed by two pointers but a pointer and a length. I also found this comment to be misleading: "[a slice] doesn’t actually contain the contents of a string, just a pointer to the begin[ning]". That is not a special or defining characteristic of a string slice. `String`s also just contain a pointer to the data, a length and a capacity. The real difference lies in ownership, but it's too early for that explanation.  
Apart from the factual content, it's extraneous detail so I shortened the comment.
2. Lifetime system
The lifetime system is no longer bound to scopes. I've updated the explanation. Several of the examples that are commented out and are supposed to cause compile errors no …

[Rust/en] minor fixes to string slices and borrow system

---

typescript.html.markdown

Found a small error in the TS documentation.  There was an extra space causing the markdown link rendering to be incorrect!

[typescript/en] Fix playground link

---

reason.html.markdown

the type of secondTrip should be Trips.trainJourney, not Trips.firstTrip.
trainJourney is a proper type, whereas firstTrip is a variable
- [*] Yes, I have double-checked quotes and field …

[language/reason] fix typo

---

haxe.html.markdown

Although Haxe has a great JS target, it has many other targets as well, and is certainly a general-purpose language, and not strictly web-oriented.

[Haxe/en] general-purpose, not specifically web-oriented

---

ruby.html.markdown

[ruby/en] Fix typo in ruby.html.markdown

---

uk-ua/cypher-ua.html.markdown
uk-ua/go-ua.html.markdown

Wasn't sure how to prepend this PR as it affects multiple programming languages, and concerns multiple world languages
Attempted to download the Go source code at https://learnxinyminutes.com/docs/go/ earlier, and noticed that the source code file was in Ukrainian instead of English. Fixed in a commit and then noticed that Cypher had the same incorrect filename, and sure enough downloading the Cypher source code at https://learnxinyminutes.com/docs/cypher/ downloads the Ukrainian version instead of English.

[Go,Cypher/en-us,uk-ua] Fix Cypher and Go source code download as uk-ua language

---

python3.html.markdown

problem:
assigning a list of animals to the list variable overwrites the list function, so that later in line 531 the list function is not available and raises a Type Error:
```
In [133]: list(filled_dict.keys())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-133-a2c520b90051> in <module>
----> 1 list(filled_dict.keys())
TypeError: 'list' object is not callable
```
solution:
use another variable name instead of list

[python/en] don't overwrite list function

---

latex.html.markdown

On line 144, it was _per_, instead of _pre_

[latex/en] Minor spelling mistake corrected

---

sass.html.markdown

SUPER minor change!
The SASS documentation says:
>Sass has two different syntax options to choose from. SCSS, which has the same syntax as CSS but with the added features of Sass. Or Sass (the original syntax), which uses indentation rather than curly braces and semicolons. This tutorial is written using SCSS.
However, the markdown codeblock was using `sass` for the syntax highlighting.  This caused all the `;` to be marked as errors.  This change changes the highlighting to `scss` so there are no errors in the formatting.

[en/sass] Update Sass Example to use proper syntax highlighting

---

coq.html.markdown

Many lines exceed the 80 character limit that makes the code wrap around
on the website.  This mainly addresses comments. The comment style has
been preserved.  For the code lines that exceeded 80 characters, I have
not adhered to any style.
@philzook58 (being the author): You're welcome to review this, if you like.
I don't think I've changed anything of significance.

[coq/en] Fix code width

---

swift.html.markdown

Thanks for this valuable resource! I noticed that the return value of the `findIndex` function should have been an `Optional` — this PR makes that change.

[swift/en] Return value of `findIndex` is `Optional<Int>`

---

smalltalk.html.markdown

• Under Simple syntax, it referred to a unary message as “a single string”. I think it would be clearer and more accurate to describe it as “a single symbol”.  Calling it a string may leave people confused with actual strings (i.e. instance of String class). Furthermore, message selectors are actually Symbol instances.
• Fixed the formatting of the bullet-point list of messages.
• Fixed the formatting of the example code, and set highlighting to smalltalk language.
• Under Assignment, many of the examples are actually access and assignment. You could simplify the list down to just the first 6 (i.e. up to and including x := Object new). The rest can go in a section further down which is about interesting base access methods. Even the Object new example isn’t really necessary, but it helps …

[smalltalk/en] Made some improvements

---

de-de/make-de.html.markdown

I have fixed some typos and comma errors in make

[make/de-de] Fixed typos and comma errors

---

standard-ml.html.markdown

The homepages for @sshine and @davidpdrsn were broken.
Add "Further reading" link to Exercism.io's SML track.

[standard-ml/en] Fix broken author homepage links, add Exercism.io link

---

typescript.html.markdown

This will overcome TSError:2362 : "The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type"

Typsecript/ts - Update typescript.html.markdown

---

toml.html.markdown

Switching between json code block and toml code block caused it to render improperly. Fixed.

[toml/en] Fix code snippet formatting

---

mips.html.markdown

Some lines were greater than 80 characters long, which causes some unaligned wrapping of comments on the website. This PR reduces all lines' length to a maximum of 80.
- [N/A] I solemnly swear that this is all original content of which I am the original author
- [N/A] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [N/A] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)

[MIPS Assembly/en] fixing line length

---

rust.html.markdown

The `get_bar` method consumes `self`. The name is misleading and does not respect the language naming convention.
This PR renames it to `into_bar` and provides `bar` (a getter) and `bar_mut` (to get a mutable reference).

[rust/en] Change misleading method and add two other methods

---

wasm.html.markdown

The second comment probably got to the actual expression by mistake. Commented expression is wrong as it should be, but the other one is fine.

[wasm/en] Remove wrong comment

---

crystal.html.markdown

I have fixed a small typo and changed the reference url to https.

[crystal/en] Fixed typo and reference url

---

groovy.html.markdown

Changed _"mthod"_ to _"method"_.

[groovy/en] Small typo fix in Groovy document

---

raku.html.markdown

- [Y] I solemnly swear that this is all original content of which I am the original author
- [Y] Pull request title is prepended with `[language/lang-code]`
- [ Y] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ Y] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ Y] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [Y] Yes, I have double-checked quotes and field names!

[Raku/en] Fix some typos for the Raku page

---

raku.html.markdown

[raku/en] Fix typos in raku.html.markdown

---

moonscript.html.markdown

This is a very minor edit, so I didn’t keep the checklist here. The original line results in a runtime error in Lua after transpiling, as the variable `i` doesn’t exist.

[MoonScript/en] Fix reference to an undefined variable

---

rst.html.markdown

There were two issues here:
* The non-inline link was used incorrectly, and should have a colon after the specifier. 
* A compile error was generated from having a non-escaped `*`.
These can be verified by running `rst2html`:
```sh
$ rst2html.py ./restructuredtext.rst tmp.html
./restructuredtext.rst:24: (WARNING/2) Inline emphasis start-string without end-string.
./restructuredtext.rst:59: (WARNING/2) malformed hyperlink target.
```
After adding the colon and escape:
```sh
$ rst2html.py ./restructuredtext.rst tmp.html
```
I've also added a sentence on escaping.

[RST/en] Fix compile errors from link and escaping

---

p5.html.markdown

The URL had a quote on the end, redirecting the user to processing.org%22, instead of processing.org.

[p5/en] Fixed a wrong URL

---

python.html.markdown

'T' was apparently mistaken by someone for True, so this is a minor edit to use a different example to make sure that doesn't happen again.

[python/en] Change string access example for clarity

---

el-gr/vim-gr.html.markdown

This refers to #3946 
I've not marked the title with `[language/lang-code]` so as to make clear it's a meta issue.
I built the project and can confirm this fixes the issue:
There's now only one vim entry:
and the `el-gr` button now exists.
Both `vim`  and `el-gr` now link to the right places.
And the language of the whole page now matches the selected(greek) langugage:

Fixed duplicate vim entry and page language mismatch

---

scala.html.markdown

Add an example to clarify that the `return` keyword only returns from the inner-most `def` that surrounds it not the output of the lambda function.

[scala/en] - clarify `return` keyword usage

---

nix.html.markdown

[nix/en] Fix typo in nix documentation

---

nim.html.markdown

Semicolons for types are supposed to be directly after the variable name.

[nim/en]: Fix syntax issue

---

python.html.markdown

***
the existing page has a demo for `if` expressions that :
- returns a string when expression resolves to `True`
- returns a number when expression resolves to `False`
this reduces readability and looks ambiguous
i propose that both resolutions return strings which are contradictory in their meaning – *yay* and *nay*

[python/en] improved demo of `if` expression

---

qsharp.html.markdown

Q# does not support multi-line comments, so that mention can be misleading.

[qsharp/en] Remove mention of multi-line comments

---

ru-ru/pascal-ru.html.markdown

---
fixes doubled entry for Pascal on homepage
added the human language code in the YAML Frontmatter of [Pascal-ru][1]
[1]: https://github.com/adambard/learnxinyminutes-docs/blob/master/ru-ru/pascal-ru.html.markdown

[pascal/ru][homepage] added (human) lang to pascal-ru

---

set-theory.html.markdown

This pull request attempts to fix major inconsistencies and some incorrect information. It also streamlines the article by rearranging and/or removing stubs of information.
- Replaced `v` and `^` set operators with cup and cap, respectively;
- Removed history section as the information was not necessarily accurate;
- Expanded symbols section by splitting it into operators and qualifiers;
- Renamed "builtin sets" to "canonical sets";
- Replaced Latin alphabet symbols for canonical sets with their Blackboard bold variants (see: https://en.wikipedia.org/wiki/Blackboard_bold);
- Rewrote set relations section to streamline information;
- Rewrote examples in set operations section to make meaning more clear;
- Removed generalized operations section, as the original author was clearly trying to …

[set-theory/en] Update set-theory.html.markdown

---

elixir.html.markdown

As per Elixir docs, `Agent.start_link/1` returns `{:ok, my_agent}`, so let's pattern match against that. https://hexdocs.pm/elixir/1.8.2/Agent.html#start_link/2-examples

[elixir/en] Use correct pattern matching for Elixir

---

zh-cn/yaml-cn.html.markdown

---
以下是译注，以供reviewer参考：
1. 原文为'syntactically significant newlines and indentation'，原译为“语法显著换行符和缩进”。
个人认为，significant在此处应为“有意义的”，而非“显著的”。联系上下文，此处应指YAML的换行和缩进具有语法含义，而非在语法上显著（虽然确实很醒目）。
故译为“在语法上有意义的换行符和缩进”。
2. 原文为'UTF-8/16/32 characters need to be encoded'，原译为“UTF-8/16/32 字符需要被转义”。个人认为，“转义”应为escape，并且虽然`\u`本身是一个转义字符，但目的是为了表明编码。
故译为“UTF-8/16/32字符需要指明编码”。
3. “字面量块”即'literal block'，此处取literal的“字面”之意。
从下文也可以看到，字面量块会保留原字符串，包括换行等特殊字符；而折叠块会把原字符串的每一行用空格分隔，然后合并到同一行。
4. 原文为'The regexp << is called Merge Key Language-Independent Type.'。若regexp直译为正则表达式，似有不妥，故在尽量保留含义的基础上有所省略。

[yaml/zh-cn] retranslate some content

---

de-de/vim-de.html.markdown

the yaml syntax is broken at line 4
possible reason for CI test fail
possibly fixes #4000 
***

[vim/de] fix syntax on yaml frontmatter

---

c++.html.markdown

Fixes one issue mentioned in #3546. "\n" is an array of characters that requires a pointless loop behind the scenes, '\n' is just a character which does not.

[C++/en] Replace newline string with newline character

---

cobol.html.markdown

See https://duckduckgo.com/?t=canonical&q=IDENTIFICATION+DIVSION+COBOL&ia=web

[COBOL] Typo in cobol tutorial : DIVSION -> DIVISION

---

fr-fr/markdown-fr.html.markdown

partly resolves #3811
- code demo in the hyperliens section was not rendered in the built site
- resolution: converted from md \`\`\` syntax to plain html `<code>`
- **NB**: similar changes likely required for other translations (`zh-cn` and `it-it` as recorded in #3811)
- other minor improvements and corrections
---

[markdown/fr] fix unrendered md in markdown-fr

---

set-theory.html.markdown

Citations:
- JMoravitz (https://math.stackexchange.com/users/179297/jmoravitz), What is the cardinality of the set of the empty set?, URL (version: 2016-01-13): https://math.stackexchange.com/q/1610231
- Wikipedia contributors. (2020, September 25). Empty set. In Wikipedia, The Free Encyclopedia. Retrieved 06:50, September 29, 2020, from https://en.wikipedia.org/w/index.php?title=Empty_set&oldid=980302053

[set-theory/en] Correction: Cardinality of an empty set is 0

---

xml.html.markdown

under well-formedness and validation, the first line of comment within code blocks (line 104, 118, 133) should be written as text paragraph instead, otherwise anyone who simply copy-paste the code will not be able to preview the result, the original code block is now separated into three parts, each preceded by a single line of text paragraph for clarity, also the external dtd file had a typo in last commit (60a1a43) that should have been removed at the end (line 131)

[xml/en] copy edit and fix code typo

---

swift.html.markdown

It's a general good practice to mark classes as `final` unless they are designed to be subclassed.

Add a short note about `final` keyword

---

r.html.markdown

To whoever is reviewing this - I don't know your views on gender, but I think this change should be made because it makes life better for some people at zero cost to others. Our society is drenched in references to binary gender, and that causes pain for a lot of lgbtq people. Changing this example to something other than gender makes reading this document a painless experience for everyone, and might actually avoid convincing someone they don't belong in tech :)

Remove binary gender example from R

---

clojure.html.markdown

I wanted to show the result of the exemple on the -> macro but I changed it a bit to show this instead:
```clojure
user=> (as-> [1 2 3] input
#_=>   (map inc input);=> You can use last transform's output at the last position
#_=>   (nth input 2) ;=>  and at the second position, in the same expression
#_=>   (conj [4 5 6] input 8 9 10))
[4 5 6 4 8 9 10]
```
The old version was:
```clojure
user=> (as-> [1 2 3] input
#_=>   (map inc input);=> You can use last transform's output at the last position
#_=>   (nth input 2) ;=>  and at the second position, in the same expression
#_=>   (conj [4 5 6] input [8 9 10]))
[4 5 6 4 [8 9 10]]
```
I am not sure if it was intentional.
- [x ] Pull request title is …

[EN/Clojure] Fix the as-> macro exemple

---

cobol.html.markdown

Change "with start with a level number" to "starts with a level number"

[COBOL/en] Fix typo in the data item definition

---

zh-cn/go-cn.html.markdown

The original words is "hello world", the "你好世界" is the accurate and direct translation of it, see the Chinses version `hello_world` page of wikipedia: https://zh.wikipedia.org/wiki/Hello_World
The old "天坑欢迎你!" means "welcome to this big hole", and have negative meanings in Chinese slang. I think it's meaning should be "welcome to using this big fxxking shxt".
@vendethiel

[go/zh-cn] Remove negative and inaccurate translation

---

kotlin.html.markdown

This is just a tiny issue: the values of fooCopy -- `1 100 4` -- were used instead of fooData's on line 183.

[kotlin/en] fooData was mistaken for fooCopy in a comment

---

coq.html.markdown

Line 475 has an extra "prove" in a comment so removed it

[coq/en] remove extra "prove" from comment

---

coq.html.markdown

Suggested correction to make_inc and inc_2 as having `nat` types rather than `int`.

[coq/en] Update coq.html.markdown

---

de-de/nix-de.html.markdown

Unify further reading references.
Nix Manuel, Fisher example, Potter Cookbook, and Martinez Intro.
All live links.

[nix/de-de] Unify Further Reading Links

---

sv-se/nix-sv.html.markdown

Replace dead `Susan Potter` link and replace with `Rommel Martinez` reference from `[nix/en]`.
Was unable to find archived version of Potter link. Using Nix Manual, Fisher example, and Martinez
intro as the three `Further Reading` references across translations.

[nix/sv-se] Update Further reading link for consistency

---

set-theory.html.markdown

[set-theory/en] use not equal ASCII symbol

---

zh-cn/mips-cn.html.markdown

Add translation for MIPS Assembly in zh-CN
The nomenclature strictly follows the translation agreements of Danghui Wang 王党辉, Jichang Kang 康继昌, and Jianfeng An 安建峰's translation version of "Computer Organization and Design: The Hardware/Software Interface" Fifth Edition published by China Machine Press

[mips/zh-cn] Add translation

---

de-de/ruby-de.html.markdown
fi-fi/ruby-fi.html.markdown
id-id/ruby-id.html.markdown
it-it/ruby-it.html.markdown
ruby.html.markdown
uk-ua/ruby-ua.html.markdown
zh-cn/ruby-cn.html.markdown

tryruby.org redirects to Pluralsight (probably an affiliate link?). I've replaced …

Replace tryruby.org with the proper link 

---

raku.html.markdown

The pygments highlighter does not recognize `==begin` and `==end`
without a newline before `==end`. For this reason it will never end the
comment. This resulted in 95% of the Raku document being highlighted as
a comment.
We replace most `=begin` and `=end` with standard quotes `#`. In some
places I retain `=begin` and `=end` when they are indented (this works
fine in pygments).

[Raku/en] Fix runaway comment for syntax highlighter

---

toml.html.markdown

The json code block renders fine in Github Flavored Markdown on Github, but not on the learnxinyminutes.com/docs/toml page. Because there isn't any syntax highlighting for this section anyway, I switched it to vanilla code block.
- [ na] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [na ] Yes, I have double-checked quotes and field names!

[toml/en] fix code not rendering

---

es-es/c++-es.html.markdown

The Spanish translation has some typos, so I have been fixing them.

[c++/es-es] Fix some typos for the C++ article (Spanish)

---

es-es/c++-es.html.markdown

This is a follow-up to #4233.
- Grammar errors
- Unecessary capital letters
I also added myself as a "translator".

[c++/es-es] Fix more typos

---

swift.html.markdown

[swift/en] fix typo about break statement in loop

---

qsharp.html.markdown

`q` is not defined, instead it should be `qs`.

[qsharp/en] Fix a variable name typo

---

de-de/rust-de.html.markdown
el-gr/rust-gr.html.markdown
es-es/rust-es.html.markdown
fr-fr/rust-fr.html.markdown
it-it/rust-it.html.markdown
pt-br/rust-pt.html.markdown
ru-ru/rust-ru.html.markdown
rust.html.markdown
uk-ua/rust-ua.html.markdown
zh-cn/rust-cn.html.markdown

As of [Rust 1.53.0](https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#intoiterator-for-arrays) arrays implement the IntoIterator trait, so you no longer need to call `.iter()` to iterate over the values of the array.

[rust/all] Remove .iter() on array example

---

lambda-calculus.html.markdown

See this math stackexchange Q/A for the reason why this caveat is important: https://math.stackexchange.com/questions/4304294/rules-for-converting-lambda-calculus-expressions-to-ski-combinator-calculus-expr.
(There may be other clearer ways of wording the caveat. It is also not necessary that the caveat be shown inline with the rules; an alternative is to use a footnote or to make a note below the rules.)
- [x ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [x ] Content changes are aimed at *intermediate to experienced programmers* (this …

[lambda-calculus/en] nit: Add caveat to rule 2. `λx.c = Kc`

---

lua.html.markdown

[lua/en] Lua: use of loadstring replaced with load; loadstring is deprecated.

---

texinfo.html.markdown

Remove syntax highlighting since it's not supported by pygments.
Hopefully, this will allow the page to appear on the website, instead of the current 404.

[texinfo/en] Fix syntax highlighting

---

latex.html.markdown

* Correct various minor typos
* Changed from using `\ ` to `~` for non-breaking spaces in the middle of sentences
* The table's column labels had Last and First names (respectively) swapped, compared to the corresponding contents of the table
* Made language of sentence about LuaTeX and XeLaTeX clearer

[latex/en] Correct typos & make minor improvements

---

dart.html.markdown

The current example is not working.
The code is slightly different from examples from other languages. I wanted to continue the initial thought and show that you can specify arguments and returned type.
An example without using a type indication is used in the following example.

[Dart/en] Fixed error in example2

---

vala.html.markdown

On line 486, replaced &i with &more.
While at it, on lines 497-503 I also transformed all the "here" hyperlinks to their most obvious replacements.

`[vala/en]`Small correction for vala.html.markdown

---

CHICKEN.html.markdown

This change adapt the instructions to CHICKEN 5.  Before it
covered CHICKEN 4, which is an outdated version.

[chicken/en]: adapt to CHICKEN 5

---

scala.html.markdown

- I only speak English and French, and the page for [scala/fr] is less complete that the one in English, without this typo. I'll try to extend it, but later.

[scala/en] typo in creation of a new object

---

go.html.markdown

Replace link to video in the Golang University 301 playlist with a link to the playlist itself to match what is used for GU101 and 102.

[go/en] Fix link to Golang University 301 playlist

---

ru-ru/swift-ru.html.markdown

[swift/ru] s/функционал/функциональность

---

r.html.markdown

A matrix is the special case of a two-dimensional ‘array’.  Since R 4.0.0, ‘inherits(m, "array")’ is true for a ‘matrix’ ‘m’, which makes class(mat) return "matrix" "array", not only "matrix" as before. Besides, the default value for stringsAsFactors in the data.frame function has been changed to FALSE since R 4.0.0

[r/en] Update content according to R 4.0.0

---

awk.html.markdown

The `gsub` example is incorrect: with pattern `"e+"`, one gets `"m.t m. at th. bar"`. To get  `"m..t m. at th. bar"` as documented, the pattern is just `"e"`. Otherwise we could keep "e+" but change the result.
Also removed an extra dot at the end of a sentence.

[awk/en] Update awk.html.markdown

---

es-es/awk-es.html.markdown

Edit is based on the correction in the English edition.[1]
[1] https://github.com/adambard/learnxinyminutes-docs/pull/4437

correct example of gsub in awk-es

---

fr-fr/awk-fr.html.markdown

- [] I solemnly swear that this is all original content of which I am the original author
A correction which accounts both for errors identified by reviewer @vendethiel[1] and some spot by a subsequent own lint.
[1] https://github.com/adambard/learnxinyminutes-docs/pull/4440

[AWK/fr] correction orthography

---

nim.html.markdown
rst.html.markdown

[nim/en] Fixed typo in comment by deleting extra apostrophe

[nim and rst/en] Fix typo in comment

---

typescript.html.markdown

Updated the link to the typescript spec.
Removed dead link to "Anders Hejlsberg - Introducing TypeScript on Channel 9" (I couldn't find a replacement. If there is one, please let me know!)
Finally, "Definitely Typed - repository for type definitions" just points to a dead page.
- [✅] I solemnly swear that this is all original content of which I am the original author
- [✅] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)
- [✅] Pull request touches only one file (or a set of logically related files with similar changes made)
- [✅] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [✅] If you've changed any part of the YAML Frontmatter, make sure …

[typescript/en] Update typescript "Further Reading" links

---

lua.html.markdown

The previous PDF location 404's on lua-users.org, so linking to the respective lua-users.org/wiki page instead (which includes working links to the PDFs on Thomas Lauer's website).

[lua/en] Update LuaShortReference link

---

c++.html.markdown

Make it immediately obvious what importing a namespace does, instead of just listing how to use fully qualified symbols.

[c++/en] Update C++ docs to improve clarity on namespace.

---

vim.html.markdown

`:wq` is not exactly equivalent to `:x`.  
```txt
*:x* *:xit*
:[range]x[it][!] [++opt] [file]
Like ":wq", but write only when changes have been
made.
When 'hidden' is set and there are more windows, the
current buffer becomes hidden, after writing the file.
```

[vim/en] Update vim.html.markdown

---

fr-fr/javascript-fr.html.markdown

The French translation added a paragraph to explain the difference between the `==` and `===` operators. However, in this paragraph, `===` was used twice. The example for `==` was using the wrong operator.

[javascript/fr-fr] Fix equality comparison example

---

rdf.html.markdown

The turtle parser that color codes the display didn't understand """ as a closing delimiter, so it turned the second half of the rendered https://learnxinyminutes.com/docs/rdf/ page red. I removed the `turtle` part at the beginning so that it would be a generic code display and not do that.

[rdf/en-en] Make color coding generic because too much was red

---

de-de/vim-de.html.markdown

Many lines in the code blocks included leading spaces not needed, these and
trailing spaces were removed.  An additional light edit (no remove/add of
features presented) to stay within the limit of 80 characters/line.

[vim/de] remove trailing/not needed leading spaces

---

c.html.markdown

When I was going through [Learn X = C](https://learnxinyminutes.com/docs/c/), I found that information about 'printf' is given,
but information about 'scanf' is missing. 
So, I added a simpler and easy to read information about 'scanf'.

[c/en] Added missing information about scanf in C

---

pt-br/awk-pt.html.markdown

Markdownlint indicated an overly long (reference) line edited accordingly.

[awk/pt-br] account for a suggest by markdownlint

---

set-theory.html.markdown

The vertical bar qualifier explanation is missing, but it's widely used interchangeably with the colon qualifier. Even it the text you use "|" so it should be explained as well.

[set-theory/en] Add the vertical bar qualifier explanation

---

rust.html.markdown

This just adds a comment showing what the output would be for one of the examples.
Most of the `println` examples on this page use this style of comment, but this example was missing one.

[rust/en] Add fibonacci example output comment

---

raku.html.markdown

https://en.wikipedia.org/wiki/Fat_comma

[raku/en] fixes typo: fat comman => fat comma

---

git.html.markdown

Code block wasn't rendering properly because there wasn't a line break before it.

'[git]' fix typo in blame section so code block can appear properly

---

javascript.html.markdown

This block makes more sense here, as in the type coercion on addition is what leads to the weird behavoir.

[javascript/en] Small reordering for more logical flow

---

go.html.markdown

[go/en] - Fix go math library alias

---

dart.html.markdown

[dart/en] Fixed typo

---

python.html.markdown

Now it includes motivation, an explanation of functools.wraps, and demonstrates the utility of wrapping.

[python/en] Updated Decorator and wrapping explanation

---

python.html.markdown

[python/en] add hint about leading underscore indicating internal use

---

rst.html.markdown

Since _'markdown'_ is actually one kind of [_'markup languages'_](https://en.wikipedia.org/wiki/Markup_language), it seems better to use _'markup'_ here.

[rst/en] use 'markup' instead of 'markdown'

---

python.html.markdown

The description of expression `li[::2]` as "selecting every second entry" is incorrect (and misleading) as it is, in fact, selecting every second entry starting from and including the 1st entry. The correct expression for "selecting every second entry" would be `li[1::2]`.
```
li = [1, 2, 3, 4, 5, 6]
li[::2] # => [1, 3, 5]
li[1::2] # => [2, 4, 6]
```

[python/en] Fix incorrect expression description

---

elm.html.markdown

No longer referred to as "union types" in Elm. :) 
https://guide.elm-lang.org/types/custom_types.html
- [ x ] I solemnly swear that this is all original content of which I am the original author
- [ x ] Pull request title is prepended with `[language/lang-code]`
- [ x ] Pull request touches only one file (or a set of logically related files with similar changes made)
- [ x ] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ x ] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ x ] Yes, I have double-checked quotes and field names!

[elm/en] Union types > Custom types

---

toml.html.markdown

Update the integer section to reflect the fact that hex, octal and binary representations are allowed in toml.
They were added to toml in version 0.5 and more work has to be done to update this document to that version, as mentioned here:
https://github.com/adambard/learnxinyminutes-docs/issues/3158

[toml/en] hex, octal and binary are valid integer formats

---

nix.html.markdown

This `builtins.` name spacing here can go. Either also have it before `toFile`, or don't have it before `toFile` and `readFile`. Since we have `with builtins; [` at the very beginning of the docs, this can be safely removed.

nix-lang: Remove a redundant `builtins.`

---

fish.html.markdown

---
(A note for anyone browsing quickly: I'm not the original author of this document; this commit just touches a lot of lines)
I've made some changes to this document to clean up some markdown issues, and to bring it more in-line with existing docs. (The main issue was the use of `>` at the beginning of code lines, leading to [the site](https://learnxinyminutes.com/docs/fish/) rendering "fancy quotes" (`“”` instead of `""`) in chunks of code intended to be copy/pasted, as well as a lack of monospacing etc.
I've elected to use the ` ```fish` header for the large code block, as github's markdown supports this. I've left the other code blocks using bare ` ``` ` marks. (These lines have a have leading `>`, equivalent to `$` in other shells; these would confuse the syntax highlighting.)
There …

[fish/en] Fish markdown syntax fixes - spacing, etc

---

objective-c.html.markdown

Without it, the program doesn't compile:
```
Interface type cannot be statically allocated
```

[objective-c/en] Add forgotten asterisk in `MyClass` implementation

---

mongodb.html.markdown

fixed mixed up $gte: and age under "Comparison operators" (and one count of duplicated $lte: -> $lt:)

[mongodb/en] Update mongodb.html.markdown

---

go.html.markdown

I don't know if anyone knows what an "underbar" is, but I think they meant "underscore".

[go/en] Update go.html.markdown with simpler wording

---

mongodb.html.markdown

[mongodb/en] correct operator order

---

sorbet.html.markdown

---
Hello! I'd like to start the Sorbet "language" on the site.
I'll admit that I haven't used Sorbet for about a year now, so some of the references to unsupported/experimental stuff near the end might be stale. I'd love for someone currently using Sorbet to pick up where this left off.
In particular, I know that `T.enum` was replaced by `T.deprecated_enum`, but I'm not sure whether it's better to accept the rename or actually replace it with a different construct.

[sorbet/en] Add Sorbet tour

---

go.html.markdown

This pull request addresses a possible ambiguity in a comment. Currently, the comment reads, "the array variable is updated in place," in the section discussing appending to slices.
- Updated the comment to use "slice variable" for better accuracy and clarity.

[go/en] Clarify comment related to the append function in slices.

---

powershell.html.markdown

Hello,
Thanks for this great set of documentation.
Clearly the fastest way for me to acquire rapidly a new language.
There was a small error in powershell regarding -eq operator on array.
I propose a fix in this pull request, and also added some extra tips for strings.
Kind regards,
Xeyownt

[powershell/en] Fix and clarify -eq operator on (some) objects

---

pug.html.markdown

During my translation process, I noticed that during the explanation about file inclusion, the pug files that were supposed to be included had the `.png` extension instead of `.pug`. I changed it because it was probably a typing error that went unnoticed, but I'm not sure if it was intentional by the author.

[pug/en] Possible typing error corrected

---

javascript.html.markdown

The word "this" needs to be quoted since - I believe - it's referring to the keyword `this`.
If it was meant as a pronoun for the subject of the sentence, it's not quite obvious what part of the example it is pointing to and should be clarified.

[javascript/en] Add missing backquotes around `this`

---

zfs.html.markdown

- Consolidate ZFS pool names in examples
- Remove `stripe` VDEV type
- Change example with compression
- Remove garbage in examples

[zfs/en-en] Reconcile ZFS pool names for all examples and remove some garbage

---

zig.html.markdown

Now that pygments.rb is updated https://github.com/adambard/learnxinyminutes-site/pull/108 we can have proper highlighting for Zig. I also did a bit of proofreading.
I verified that it works like this
```sh
git clone https://github.com/adambard/learnxinyminutes-site.git
cd learnxinyminutes-site
git checkout b6fbc104cd53e71d23bca4f57c21afd8cb6fb5c8
gem install bundler:1.16.1
bundle update
bundle install --path vendor/bundle
bundle exec middleman build
cd build
python -m http.server
chrome 'http://localhost:8000'
```

[zig/en] mark Zig code as zig

---

powershell.html.markdown

Fixed incorrect examples for arrays.
Added information for tuple
Fixed wording for Hashtables

[powershell/en] correct examples for arrays

---

fortran90.html.markdown

[fortran/en] account for non-functional typo

---

bc.html.markdown

The global variable syntax and the pre-set variable syntax is invalid. On bc 1.07.1 it produced syntactic errors. I modified the tutorial so that it doesn't include these syntaxes.

[bc/en] Update bc.html.markdown

---

hy.html.markdown

In my testing it looks like hy dropped square brackets for conditionals.
- [x ] Pull request title is prepended with `[language/lang-code]` (example `[python/fr-fr]` or `[java/en]`)

[hy/en]  drop square brackets for conditionals

---

es-es/rust-es.html.markdown

[rust/es-es] fix variable name

---

nl-nl/amd-nl.html.markdown

It was added in #1943 and then removed in https://github.com/adambard/learnxinyminutes-docs/commit/f3b10beb01795bf7513ec8d06c9e90ab98df7a83 because it used Latin-1 encoding instead of UTF-8.

[amd/nl] Recover Dutch translation of AMD

---

lean4.html.markdown

This documentation contains more comments than the usual tutorials in this repository. Most of it explains theorem proving and not fundamental programming concepts. I think it is still aimed at intermediate to experienced programmers. Please let me know if I should change it.

[lean4/en] Documentation for Lean 4.

---

python.html.markdown

The `class variables` part seems to suggest that only "class attributes" are inherited. Removing the "class" part makes the statement clearer.

[python/en] Clarify inheritance description

---

kotlin.html.markdown

This was introduced without explanation IMO.
Had to look it up here:
https://kotlinlang.org/docs/lambdas.html#passing-trailing-lambdas

[kotlin/en] Parentheses can be omitted for single lambda args

---

elixir.html.markdown

The overall order confuses people but it is not important.
We also add some background on why it matters.
This is based on feedback from maintaining Elixir and its official docs. :)
Thank you!
---

[elixir/en] Give more context around Elixir comparison operators

---

es-es/lua.html.markdown

Translation of lua's guide to spanish using `en` and `pt-br` versions as the base.

[lua/es-es] translate lua guide to spanish

---

elixir.html.markdown

This PR fixes a small typo in the `Elixir` docs, where `theiar` should be `their`.

[elixir/en] Typo Fix

---

go.html.markdown

The Go wiki on GitHub has moved to go.dev 
The old link was broken, Updating the link ensures doc remains accurate and helpful.

[go/en-en] Update go.html.markdown

---

cs-cz/go.html.markdown

The Go wiki on GitHub has moved to go.dev 
The old link was broken, Updating the link ensures doc remains accurate and helpful.

[go/cs-cz] Update go.html.markdown 

---

fi-fi/go-fi.html.markdown

The Go wiki on GitHub has moved to go.dev 
The old link was broken, Updating the link ensures doc remains accurate and helpful.

[go/fr-fr] chore: update Go Mobile link to go.dev

---

rust.html.markdown

Fix typo/grammatical error in Rust section. Changed "begin" -> "beginning" on string slice section for clarity. Fix typo/grammatical error in Rust section

[rust/en] Fix typo/grammatical error in Rust section

---

latex.html.markdown

This one caught my eye and made me re-read the sentence a couple of times.
Small fix for a small problem :)

[latex/en] fix duplicate `are` in abbreviation section

---

es-es/python-es.html.markdown

This PR merely serves to:
- Remove an unnecessary closing parenthesis in one of the comments showing the result, as it would not be the result shown in the comment.

[python/es] remove unnecessary parentheses

---

rust.html.markdown

There was a small typo in one of the comments. Additionally, `&str` is internally a `&[u8]` which stores its state as a pointer and length, not two pointers.

[rust/en] fix a typo and make some explanations clearer

---

kotlin.html.markdown

lambda functions can not defined by `fun` directly, use `val` (or `var` if mutability is required) instead
```
fun fooLambda: (Int) -> Int = { n -> n + 1 } // Incorrect     X
val fooLambda: (Int) -> Int = { n -> n + 1 } // Correct       ✓
```

[kotlin/en] lambda functions wrong defined

---

yaml.html.markdown

Two value description texts contain the wrong key name. This commit corrects both key names in the description texts.

[yaml/en] Fix key names in yaml.html.markdown

---

hocon.html.markdown

It's been a while since I originally contributed the HOCON document. After re-reading it recently, I noticed much of it could be clearer or more concise if reworded, so I spent a few hours editing the whole thing. I also updated the HOCON Playground resource to a maintained fork (the original site is dead).

[hocon/en] clean up document

---

pl-pl/java-pl.html.markdown

The duplicate `filename` field clashes with the English version

[java/pl-pl] Remove duplicate `filename` header field

---

go.html.markdown

In the same sentence, the word "close" was used to refer to "to close the file" and "is close to another line of code".

[go/en] minor wording: disambiguate "close" in learnDefer()

---

zig.html.markdown

[zig/en] Remove incorrect comment in enum section

---

cs-cz/javascript.html.markdown
de-de/javascript-de.html.markdown
es-es/javascript-es.html.markdown
fa-ir/javascript-fa.html.markdown
fr-fr/javascript-fr.html.markdown
it-it/javascript-it.html.markdown
javascript.html.markdown
ko-kr/javascript-kr.html.markdown
ms-my/javascript-my.html.markdown
pt-br/javascript-pt.html.markdown
ta-in/javascript-ta.html.markdown
tr-tr/javascript-tr.html.markdown
uk-ua/javascript-ua.html.markdown
zh-cn/javascript-cn.html.markdown

**Changes**
*  Update JavaScript Garden site link in the Further Reading section of the article
- [ x] The YAML Frontmatter was not changed.

[javascript/en] Update Javascript Garden link

---

de-de/haskell-de.html.markdown
fortran.html.markdown

Fixed overly long comment lines > 80 characters that overflow their line when displayed online.  This includes rephrasing and moving some explanations.  Content was added : one additional comment at 'subroutine'.

[fortran/en] Fixed overly long comment lines

---

fortran.html.markdown

Addresses https://github.com/adambard/learnxinyminutes-docs/issues/5170.
The previous version had a line
real, parameter :: PI = 3.1415926535897931
that was misleading, since real variables are single precision by default in Fortran and will not store all the digits shown.

[fortran/en] declares single precision pi without extraneous digits

---

ruby.html.markdown

Reflows a bunch of comments that were breaking the Style Guideline of 80 characters.

[ruby/en] Reflow comments

---

java.html.markdown

This commit fixes a very minor typo in the `java` (English) tutorial.

[java/en] Fix minor typo

---

haskell.md

I made three small changes to the Haskell file:
1. There was no mention of the indexing operator having linear time complexity-- most programmers tend to assume that the `[]` syntax stands for an array, and the term "list" is overloaded in several programming languages to also refer to a data structure like an array, so I think this clarification is necessary.
2. There was a function definition later down in the file that referred to lists as arrays-- I have changed the name to discourage misconceptions.
3. I have added a mention of `filter` in the main document, because I think it's an important function to know.

[haskell/en] Minor changes to Haskell document that were bothering me

---

.github/PULL_REQUEST_TEMPLATE.md

See discussion at https://github.com/adambard/learnxinyminutes-docs/issues/5216

fix link to CONTRIBUTING.md

---

rust.md

[rust/en] fix typo

---

nim.md

Fixed wrong instantiation of the reference object `Room`.
While using `var defaultRoom = new Room` instead of `var defaultRoom = new Room()` is also valid, I opted to use the preferred syntax `var defaultRoom = Room()`

[nim/en] Fixed instantiation of the reference object

---

de/lua.md

[lua/de] typos

---

de/java.md

About the changes: The old version was wrong. O(n) is not "constant time". I decided to include wikipedia references for clarity.

[java/de] Corrects the O-Notation of hashmaps

---

csv.md

The CSV page used the wrong front matter, which caused CI failures starting in 49be924382b896a33c8cea97ddd07454a23fd5f9.
"language" should be "name".

[csv/en] Fix incorrect front matter name

---

smalltalk.md

This is mostly an opinionated change to the language. I set out to fix the s/Event/Even/ typo, but in my view the language in the following paragraph seemed unnecessarily condescending or expressed too much of the original author's opinions regarding the programming language.

[smalltalk/en] Improve wording and fix typo

---

gleam.md

Fixes issue #5273 
Rust link on the Gleam guide now takes you to the correct guide.

[gleam/en] Update rust link on Gleam page

---

lua.md

In addition, the cited list of metamethods isn't exhaustive.
A detailed list of operations controlled by metatables is available at: https://www.lua.org/manual/5.4/manual.html#2.4

[lua/en] Fix awkward wording in English Lua documentation 

---

es/python.md

The multiline string is used as documentation and the original post refers it as documentation and not only comments

[python/es] Multiline string as documentation

---

python.md

Relevant issue: https://github.com/adambard/learnxinyminutes-docs/issues/5347
The `__code__` example doesn't work as described but the `__doc__` does so I added a docstring and replaced the use of `__code__` with `__doc__`.
I also find it a little simpler.

[python/en] Fix @wraps decorator example
