- tcl.html.markdown
> Tcl overview

- java.html.markdown
It is a good practice to use `@Override` when implementing methods
for interfaces.
> java: Add `@Override` for interfaces.

- c.html.markdown
Fixed one line being cut off and a comment about the export attribute was referring to the wrong function and variable.
> C: two minor fixes

- de-de/bash-de.html.markdown
- de-de/yaml-de.html.markdown
First translation, which i have to offer. Hope with that everything is all right with the structure of the document.
> [YAML/en] translated to [YAML/de]

- zh-cn/matlab-cn.html.markdown
new file `zh-cn/matlab-cn.html.markdown` added
> Chinese translation of MATLAB tutorial

- rust.html.markdown
This adjusts the English Rust tutorial for changes to the language and generally tweaks a few other things.
Fixes #860.
> [rust/en] Update the Rust tutorial

- pt-br/swift-pt.html.markdown
> [swift/pt-br] Remove an extra comma

- r.html.markdown
Added a definition of the `parakeet` variable.  It's currently never defined, but referenced.
> [r/en] Add definition of parakeet variable

- elixir.html.markdown
The list's getting bigger, but figured it's worth mentioning ranges since it's one of the value types. Thanks for reviewing.
(cc/ @mrshankly and @dskecse)
> [elixir/en] Add ranges under 'Basic types'

- objective-c.html.markdown
One code and four comment fixes.
> [obj-c/en] Fix typos in objective-c doc

- javascript.html.markdown
Added some markdown formatting to the comments throughout to clarify meaning. Also tweaked a couple of other quote marks as well. Also shortened a couple of long lines.
More to do, but stopped here for now. :)
> javascript/en: added some md formatting

- hack.html.markdown
[The Hack language](http://hacklang.org/)
This article covers the major features of the Hack language. A few details are currently missing, but these aren't critical for understanding what the language offers. (Missing items include collections, `invariant()`, and predefined Interfaces and classes).
> [hack/en] Add english Hack language page

- nim.html.markdown
- The section on sequences was quite short, added a bit
- Fixed a typo
- Using proper Nim syntax highlighting. Is pygments used as highlighter?
> Fix Nim a bit

- swift.html.markdown
- zh-cn/swift-cn.html.markdown
* Optional init
* Enum with associated values
> Add two swift feature and make a full translation for swift to zh-cn

- git.html.markdown
Added info about the `-a` switch which can come in handy at times.
> [git/en] Added the handy -a switch

- ruby.html.markdown
> [Ruby/en] Add logical operators to Ruby tutorial

- javascript.html.markdown
- zh-cn/javascript-cn.html.markdown
keep zh-cn version sync with the English one
> [javascript/zh] Translation tracking

- racket.html.markdown
This topic is confusing for a lot of people, so I think it’s worth to add it here. Thanks for reviewing!
CC: @elibarzilay @gustavoschmidt @cmpitg 
References:
1. http://docs.racket-lang.org/reference/booleans.html
2. http://docs.racket-lang.org/reference/eval-model.html
3. https://groups.google.com/forum/#!topic/plt-scheme/T1k49HMl450
4. http://stackoverflow.com/questions/16299246/what-is-the-difference-between-eq-eqv-equal-and-in-scheme
5. http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html
> [racket/en] Add detailed explanation of eq?, eqv?, and equal?

- haskell.html.markdown
Noticed when reviewing #1006, the two fib definitions are off by one.
> [Haskell/en] Make the two fib functions consistent

- perl6.html.markdown
Probably just a paste-o mistake.  Want to count 3 times not 5.
> thrice .... gather ^3 counts three times "0 1 2" not 5

- ruby.html.markdown
In reference to https://github.com/adambard/learnxinyminutes-docs/issues/717
Adding has_key? and has_value? methods for Hash
Adding include? method for Array
Note: I have used paranthesis while giving examples of these functions because the fact that they are optional is stated far below. It might create confusion if someone is reading from top to bottom.
> [ruby] Array and Hash specific functions

- python3.html.markdown
1. Some changes related to spacing
2. Added an online resource
> Update python3.html.markdown. Changes to spacing and online resources

- python3.html.markdown
Terminology related to Python special functions
> [python3.html.mardown] Added a short statement about magic methods

- tr-tr/python3-tr.html.markdown
> [python/tr] Turkish Translate

- erlang.html.markdown
As required by Erlang:
http://erlang.org/doc/reference_manual/expressions.html#id78310
> [erlang/en] Fix syntax error in erlang if-expression

- tr-tr/markdown-tr.html.markdown
> [markdown/tr] Markdown Turkish Translate

- scala.html.markdown
- zh-cn/scala-cn.html.markdown
update and translate learn.scala
> [scala/cn]translate scala doc into chinese

- python.html.markdown
"Hello " "world!" # => "Hello world!"
This is very useful for quick scripts.
> [python/en] Adding strings without + added.

- python3.html.markdown
Added for Python3 docs as well.
> [python3/en] Adding strings without + added.

- python.html.markdown
- python3.html.markdown
Range function with start and stop.
> [python/en] Range function arguments.

- python.html.markdown
> [python/en] Moved to default python2 print statements.

- standard-ml.html.markdown
Intro misrepresents SML by suggesting it has no references. Fixed buggy wording of introduction and added sample usages of references, while and seq.
> [standard-ml] Standard ML has references!

- python.html.markdown
Changed "Revert" to "Reverse".
> Fix Python typo.

- fr-fr/json-fr.html.markdown
Hello,
A new PR wiith only the json.
You can find the older PR at #1078.
Thank you @vendethiel for the review.
> [json/fr] Adding french to JSON guide

- fr-fr/typescript-fr.html.markdown
Hello,
I made a new branch for this PR.
The old one can be found at #1075.
Sorry for the wrong manipulation.
Tank you @vendethiel for the review.
> [typescript/fr] Adding french to TypeScript guide

- json.html.markdown
Just a small error found by @vendethiel on the [french translation](https://github.com/adambard/learnxinyminutes-docs/pull/1078#discussion-diff-29556040).
> Fix Markdown

- it-it/c++-it.html.markdown
Ciao! Added italian translation of C++ guide
> [C++/it] italian translation of C++

- php.html.markdown
Just adds a missing `;`.
(Yep, just one character changed.)
> [php/en] Add missing ;

- haxe.html.markdown
...for "do statement always runs at least once" section.
Note: This is my first pull request on GitHub, so please be gentle if I made a mistake (:
> [haxe/en] Correct the condition variable

- haxe.html.markdown
* correct the array name in a for loop iterating on an index
* add an assignment for "case _" in first switch example
* fix case of variable name in trace for control statement returning as an expression
* move some inline comments to a separate line above the statement and shorten some comments to prevent text overflow
> [haxe/en] Few cosmetic fixes

- bash.html.markdown
> fix spelling errors in bash

- java.html.markdown
As per adambard/learnxinyminutes-docs/pull/1115.
> Further improve for loop description.

- zh-cn/javascript-cn.html.markdown
Line 344: From "行数" to  "函数", which should means 'Function' here.
> Fix typo of chinese translation

- zh-cn/bash-cn.html.markdown
> [bash/cn]update bash-cn

- standard-ml.html.markdown
Tripped over this a little while ago when seeing a record in the wild for the first time. I think it's worth noting as a compound datatype along with lists and tuples.
> Add record notes to the Standard ML page

- pl-pl/python-pl.html.markdown
I added translation of python tutorial to polish :) This website is a great idea!
> Python 2.x script translation to polish

- ruby.html.markdown
> [Ruby/en] Fix explanation of "and" and "or"

- zh-cn/rust-cn.html.markdown
Hi, it is a Chinese translation for rust
> rust/zh Add chinese translation for rust

- chapel.html.markdown
Created a from-scratch tutorial for the Chapel Language.
Code compiles as seen using release version Chapel 1.11.0
Covers many topics that a beginner would be interested in knowing but not interested enough to scour the specification, miscellaneous slides, or technical academic and white papers.
> Chapel Tutorial

- python.html.markdown
If line 117 is accurate, then {n} style string formatting is the preferred style, and it should be reflected in the examples.
> Changed %s formatting to {n} style.

- chapel.html.markdown
After down merging, included correct capitalization of Chapel, correct use of apostrophes.
> Merged fix from upstream, added slight corrections

- perl.html.markdown
Variables might start with `$`. Edited to make that point clearer.
Also `#` is more commonly called number sign than number symbol.
> Fixed misinfo regarding sigils

- scala.html.markdown
> [scala/en] Consistent code format & some minor language corrections

- es-es/julia-es.html.markdown
> RFC: Update julia-es to v0.3.11

- de-de/yaml-de.html.markdown
So it can be view´d on the website!
> Fixed some stuff in yaml-de.html.markdown

- ru-ru/objective-c-ru.html.markdown
> [objective-c/ru] Updating Objective-C guide

- tcl.html.markdown
Also, elaborated on name resolution with set vs. variable.
> [tcl/en] Updating line 167 to fix name resolution error at line 173. 

- ruby.html.markdown
#push is commonly used imho and it is also used in other languages (e.g. Javascript).
> Add #push to Array besides shovel operator

- es-es/python-es.html.markdown
Added the advanced section, and update some parts to match the english version.
> [python/es] Added missing section and fixes some typos

- ro-ro/clojure-ro.html.markdown
> Romanian translation of the Clojure tutorial

- zh-cn/javascript-cn.html.markdown
> input typo fixed

- python.html.markdown
https://docs.python.org/2/tutorial/errors.html
> Python: add finally and with statements

- zh-cn/go-cn.html.markdown
> A tiny bug

- ruby-ecosystem.html.markdown
> [ruby-ecosystem/en] Fix typo

- git.html.markdown
I gave this tutorial a read through and it's very extensive. I think it's a solid addition to the "further information" section.
> Add Udemy's new git tutorial as a resource.

- make.html.markdown
Here is a first draft of a make tutorial. I'm not an expert at make at all so corrections are probably needed!
> [make/en] Adding a tutorial on (gnu) make

- make.html.markdown
I just found two small errors in the tutorial. One was a tab error!
> fix two small bugs - tab error and quotation marks

- tr-tr/swift-tr.html.markdown
> [Swift/tr] Turkish For Swift

- fr-fr/livescript-fr.html.markdown
Hi, it's the french translation of the LiveScript guide.
> [livescript/fr] initial commit

- no-nb/bash-no.html.markdown
Added a Norwegian translation of the bash file. My first request, so let me know if there's something I should do differently.
> [bash/no-nb] copy/translation

- es-es/julia-es.html.markdown
I didn't notice they wouldn't fit well, because they fitted ok in gitHub preview.
> [Julia/es] Use smaller images.

- xml.html.markdown
> Fixed the description of attributes and elements.

- php.html.markdown
> [php/en]Align the comment block

- javascript.html.markdown
https://github.com/adambard/learnxinyminutes-docs/issues/1248
> [javascript]  Fix for issue 1248

- css.html.markdown
Fixed a few minor typos and grammatical issues.
> Fix some grammatical issues/typos

- id-id/json-id.html.markdown
Hi, I translated JSON to Indonesian (json-id).
Thanks.
> [json/id] Translated JSON to Indonesian (json-id)

- id-id/xml-id.html.markdown
Hi, I translated XML to Indonesian (xml-id).
Thanks. 
(No silly mistakes this time)
> [xml/id] Translated XML to Indonesian (xml-id)

- pt-br/c++-pt.html.markdown
Fix translate in portuguese about how objects can be edited inside methods.
> [c++/pt-br] Fix translate on editing object as parameters

- es-es/c++-es.html.markdown
Hi, I translated the C++ Guide to Spanish.
> [c++/es] added es-es translation for c++

- erlang.html.markdown
turns out tabs look bad on the webpage, also fix two typos
> Fix poor formatting and typos

- de-de/git-de.html.markdown
- de-de/go-de.html.markdown
Added missing second half of a word.
> [git/de] fixed typo

- pt-br/javascript-pt.html.markdown
Hi, I translated the Javascript Guide to Brazilian Portuguese =)
> Added pt-br translation to Javascript

- fr-fr/python-fr.html.markdown
French Python 3 does not exists (yet).
> Update French Python 2 with link to English Python 3.

- tr-tr/swift-tr.html.markdown
> swift-tr.html.markdown

- c++.html.markdown
Regarding issue #1216, Better explaining the Reference 'fooRef'.
> {C++}Clarified fooRef address.

- common-lisp.html.markdown
Comment explaining '-p', in line 178. issue #1157
> {common-lisp}Issue #1157 comment for '-p'

- pt-br/javascript-pt.html.markdown
I'm sorry, when I was reviewing right now, I found some typos and fixed them...
> Fixing some typos

- c.html.markdown
Fixed Issue #1170
Variable size array, user size input added.
> {c}Variable size array, user size input added.

- hack.html.markdown
- pt-br/hack-pt.html.markdown
Hi! I fixed a few typos on hack/en and added a pt-br translation.
> [hack/en] Fixed some typos and added pt-br translation

- java.html.markdown
Added abstract classes in java. Explained briefly how they are different from interfaces. Also listed a few Caveats while using them. All through code of course. (I had created a pull request earlier but I closed it, since it had 3 commits, and now I have squashed my commits into 1).
> [java/en] Added abstract classes in java

- php.html.markdown
This PR adds some new PHP operators, in particular:
- ternary shortcut
- spaceship operator
- null coalesce operator
> [PHP] Adds some new php operators

- java.html.markdown
- php.html.markdown
Added section on how to declare and initialize both single variable and multiple variables with the same value. Important concept for large structured programs. Separated this a little bit.
> Added how to declare and initialize variables for single and multiple instances

- java.html.markdown
- php.html.markdown
Added example of when string concatenation can also be helpful with combination of strings with html tags as this is important to understand when templating say output code from a database transaction.
> String concatenation with html tags also supported example

- css.html.markdown
And changed "CanIUse" to “Can I Use…”
> [css/en] Added some Further Reading Links for CSS

- python3.html.markdown
A description of the step parameter of the range function is added. An example of its use in a for loop is also given.
> [python3/en]Add step parameter to range function

- python3.html.markdown
Quick-list of changes:
* Compared is and ==.
* Discussed the use use of the end argument in print.
* Noted that tuples of length 1 require an ending comma.
* Discussed that keys of dictionaries have to be immutable.
* Added that elements of a set have to be immutable.
* Included an explanation of returning multiple values with tuple assignments.
* Added some clarifying remarks to comments.
> [python3/en] edits and additions

- pt-br/brainfuck-pt.html.markdown
> Fixed typos

- git.html.markdown
* added gitignore section (7b7ce66)
* added shallow cloning & single branch cloning (037ff22)
* added `--amend` option for commit (e75a9e0)
> [git/en] added gitignore section plus few other things

- erlang.html.markdown
- pt-br/swift-pt.html.markdown
> Comment translation for swift-pt

- fr-fr/python-fr.html.markdown
> [python/fr] Fix typo in french python doc 

- objective-c.html.markdown
Added additional reading for both iOS and OS X for Objective-C from Apple Developer site. Added contribution line.
> [objective-c/en] Added additional reading for both iOS and OS X for Objective-C

- swift.html.markdown
Just add a simple example of such operator.
> [swift/en] Add generics operator in Swift

- nim.html.markdown
- perl6.html.markdown
Fixes the typos mentioned in the end: https://github.com/adambard/learnxinyminutes-docs/issues/1390
> Fixes typos and removed useless spaces

- json.html.markdown
> Mention of trailing commas in JSON and that they should be avoided

- python.html.markdown
- python3.html.markdown
Added examples of map() and lambda functions when used with multiple variables, to increase clarity around this use case.
> [python3/en] Added examples of multiple parameters to higher order functions

- php.html.markdown
Added the error handling blocks
> [php/en] Adding error handling

- go.html.markdown
Minor typos, increased readability, and added link to official docs for further reading.
> [go/en] Minor typos/Increased readability/Added link to official docs

- swift.html.markdown
Added clearer description of Optionals and Unwrapping. Minor typo changes as well. Also forgot to add myself as a contributor from swift-1 pull request.
> [swift/en] Added clearer description of Optionals and Unwrapping. 

- matlab.html.markdown
Added a simple example to explain Matlab classes. Classes in Matlab almost seem like an afterthought by Mathworks, so I thought they'd be appropriately at home at the end of the document. 
Closes  #1038
> [matlab/en] Added simple class example to Matlab

- git.html.markdown
Added [Git Immersion](http://gitimmersion.com/) as a resource
> [en/git] Add Git Immersion tutorial as a resource

- json.html.markdown
> [json/en] Typo

- coffeescript.html.markdown
Just fixed a spelling mistake and changed the grammar slightly to make it read better
> [coffeescript/en] Fixed grammar

- forth.html.markdown
> [Forth/en] fixes forth typo

- forth.html.markdown
Fixes another Forth typo. I should of checked for more typos before making a pull request, this should be it though.
> [Forth/en] Another typo fix

- perl.html.markdown
Post condition ifs are mentioned, but not post condition for loops.  Post condition for loops are pretty widely used in my experience so I felt they should be listed.
> Add example of post-condition for loop.

- es-es/visualbasic-es.html.markdown
Hopefully I’ve done everything correctly. If not, please tell me and I’ll amend the patch.
> [visualbasic/es] Create Spanish translation of VB tutorial

- fr-fr/haml-fr.html.markdown
I just translated the article about HAML in French.
Feel free to make suggestions about the translation, and I hope you will enjoy it ! :)
> [haml/fr] Added translation in French for the HAML article

- java.html.markdown
Just some quick cleanup to make the code correctly formatted in parts
and fixed some typos.
> Fix some grammar, spelling and indentation

- xml.html.markdown
Children makes more sense grammatically and is found in a lot of tutorials online, so makes sense to include it here
> [xml/en] Grammar fixes

- learnsass.scss
- sass.html.markdown
Added Sass tutorial (written in SCSS syntax). 
Sass request in issue #1112
> [sass/en] Add Sass tutorial

- ru-ru/php-ru.html.markdown
Improved PHP ru-ru translation
> [PHP/ru] Improved PHP ru-ru translation

- coldfusion.html.markdown
[coldfusion/en] Adding Coldfusion
> [coldfusion/en] Adding Coldfusion

- c.html.markdown
Also added a note about the convention of constant names being all caps
> [C/en] Accessing command line arguments in main

- ruby.html.markdown
I thought some simple demonstrations of these methods would be helpful, particularly when working with arrays.
> [ruby/en] Add modulus, array.first, array.last, and each_with_index

- java.html.markdown
Added a simple example on how to switch strings in Java 7 and above.
> [java/en] Add Switching on String Example to Java

- latex.html.markdown
Revisited the initial latex quick reference and reorganised its structure. Instead of multiple comments and commands, created a compile-able latex document to show off the bare-bones basic structure of latex documents and a few built-in features. 
Includes pull request #1055 
Closes issue #1119
> [latex/en] Initial latex whirlwind showcase revisited

- latex.html.markdown
Initial version for LaTeX.
First time requesting for a pull. Let me know if something is not right.
> initial version for latex

- css.html.markdown
Also fixed extraneous whitespace, code mistakes, made sure line width was <80 characters.
> [css/en] Fixed grammar, increased clarity.

- README.markdown
- c.html.markdown
- json.html.markdown
added swap function as an example for call by reference.
also added usage of "goto" in C.
> example function added for call by reference

- rust.html.markdown
> Mention meaning of asterisk. Explain *ref_var2

- csharp.html.markdown
Another tool I found useful when learning C#
> Added info C# null-propagation

- python3.html.markdown
Remove the line describing the range is a generator.
Also removed useless spaces at the end of lines.
adambard#1323
> Range is not a generator

- java.html.markdown
Brief explanations of what BigInt and BigDecimal are for and what they consist of. Also added the ranges for float and double according to Java documentation.
> Added BigInteger and BigDecimal explanations to Java tutorial

- python3.html.markdown
These have been valuable resources to me, but I'm not sure whether it fits this section or not.
The PEP8 should definitely be there imho, but we might want to add another section for this kind of resources.
> [python/en] Add resources to the "Free Online" section

- python3.html.markdown
Unified the formatting throughout the document, clarified the output of a few lines, and tried to make it easier to visually separate comments from code when reading.
> [python3/en] Cleaned up formatting and clarified output

- python.html.markdown
Added instructions on how to perform input operations in Python 2.7. 
I believe this is an important instruction currently missing from this document. Please review it, @vendethiel.
> [python/en] Added instructions on how to perform input operations

- d.html.markdown
> [d/en] Next set of improvements

- python3.html.markdown
Added instructions on how to perform input operations in Python 3.
This is similar to the pull request #1471 which added input instructions for Python 2.7. Please review it and let me know. Thanks.
@levibostian
> [python3/en] Added instructions on how to perform input operations

- es-es/javascript-es.html.markdown
corrected typo in javascript doc
> [javascript/es] corrected typo in javascript doc

- xml.html.markdown
XML is singular so the word should be carries
> A minor typo.

- javascript.html.markdown
Added backticks for the “this” keyword.
> Added backticks for a keyword.

- ocaml.html.markdown
I added some spaces between some words that were merged.
> [ocaml/en] - Added some needed spaces

- README.markdown
Just a typo. Changed `tag your issues pull requests with` to `tag your issues and pull requests with`
> Fix typo on readme

- de-de/latex-de.html.markdown
Hi,
this adds the german translation for the LateX tutorial.
Greetings,
Moritz
> Adds german translation for LateX

- c++.html.markdown
Added in some information about enums in C++ including some different
use cases
> [C++/en] Added in Enum information

- nl-nl/yaml-nl.html.markdown
Translated YAML document to dutch
> [YAML/nl] Translated YAML to dutch

- zfs.html.markdown
ZFS is a great filesystem, that many developers and sysadmins may come across in their careers. Thought people might like a basic guide.
> Adding some documentation about zfs

- de-de/ruby-de.html.markdown
- de-de/ruby-ecosystem-de.html.markdown
- de-de/scala-de.html.markdown
Translated scala article into german and added paragraph on traits.
Translated ruby article
> Scala and Ruby article in german

- it-it/bash-it.html.markdown
7bc99fcaf4329b3c25cca671f62a03b67aa4d46e
8b7a2fff9a71b8fa8754947434b8b1f184ed2de1
e4c261567533921f35ce4e65ebfe6621a128992b
8909457ae46dc8fb151ef146acb3f6b8402f3407
de676b62b83fcaaa9977cca9adb9c38383b64f35
acc9a73c018a28a9c8ead7b108dd1fdfee7a797b
960ee4a1856db8eadb96277bb2422edfa8f2a81c
f4022052471d6dc0a9c2fb8794e1352253b4c5ad
> Bring this version up to date with the english one

- pt-br/json-pt.html.markdown
> [json/pt-br] Correção de palavra.

- javascript.html.markdown
This pull request simply adds examples of modulo division and their expected outcomes to the JavaScript article. :panda_face:
> [javascript/en] Adding modulo division

- csharp.html.markdown
- elixir.html.markdown
I added some documentation on how the receive do block works for receiving messages in Elixir. I explained how a receive do block only waits for one message. In order to deal with multiple messages, a function with a receive do block must recursively call itself.
> Receive do documentation for Elixir

- ruby.html.markdown
Adding more string operations that are sometimes seen in open source projects.
> [ruby/en] Adds more string operations to ruby doc

- it-it/json-it.html.markdown
Fixed some typos, improved syntax & fixed the contributors table
> [json/it] Updated translation & fixed table

- it-it/c++-it.html.markdown
462ac892179d64437b1124263402378a6054e50b
3db1042157204ad05484d6b42140261f849040cc
cea52ca43490b74316781c23779654fd46aaeab4
47d3cea47e8c5203efa857070a00dcfbff67b019
894792e1e17173823a5d50de24439427c69d63f4
06889be239622266d9c36c750f7ee755ccdae05d
97b97408eab97fbe322df4266cda9ab2ed21fceb
1d1def16a5d7925bb8f7fba7dc49182e33359e85
a230d76307ecbc0f53c4b359cdb90628720f915e
fc9ae44e4887500634bf3a87343d687b4d7d4e3c
85f6ba0b57b9d894c694df66449b1e1c555c625b
8eb410208a8d9b0a42f6c52411455ace04c78101
ae86e4ebabb0c78c1bd8052e6ab5916446ef39c2
455afa3a7bf59fc272f3439825da55659765eec0
12286a4b78f82bde3907d4bf348e20c12dd6d46f
9bc553c46ce9b7154ec7c82451d71608f4beda82
87e8e77e5fd8d84a252dbb6d6697202118378774 …
> [c++/it] Bring this version up to date with the english one

- javascript.html.markdown
> [javascript/en] Small typo fix

- it-it/coffeescript-it.html.markdown
7afadb01811e1fb97a928a0e2d8b1a3b7a3a42f6
960ee4a1856db8eadb96277bb2422edfa8f2a81c
a67d9d9e0ed3d351ce0139de18a4b212b47ab9cb
d115a86ac8602c680a059e7a53d227cbccdf157a
ef40704f9b66ae85d7a8a6853abbbf8810af3b90
> [coffeescript/it] Bring this version up to date with the english one

- it-it/coffeescript-it.html.markdown
- it-it/elixir-it.html.markdown
> [elixir/it] Bring this version up to date with the english one

- php.html.markdown
The existing code works - this is just better style.
> Remove an extraneous space

- javascript.html.markdown
Added some additional information on declaring variables.
> Updated javascript.html.markdown

- objective-c.html.markdown
Added how to switch objects between the two types with examples.
> Mutable And Immutable Changing

- c.html.markdown
Dynamically allocated arrays and pointers can be confusing. I added some examples and clarifications.
> [C/en] More info on dynamically allocated arrays

- csharp.html.markdown
- ruby.html.markdown
Basic arithmetic bitwise xor operator example
> ruby and csharp code example updates

- python.html.markdown
- python3.html.markdown
For both Python 2 and Python 3
Python 3 only:
- Tuples: added extended unpacking
- Dictionaries: added new unpacking from Python 3.5
Both Python 2 and 3:
- Lists: added `remove`, `insert` and `index`
- Sets: added ^, <=, >= operators
- Classes: added propery decorator (including getter, setter, deleter)
> [python/en] Add some stuff to lists, tuples, dicts, sets and classes

- es-es/ruby-es.html.markdown
Update and fix typos on the ruby translation.
> [ruby/es] General translation update

- php.html.markdown
Added some clarifying examples to sections on echo(), constants, and
cleaned up formatting on others. Added further explanation about the
spaceship operator.
> [php/en] Add more examples and explanations

- php.html.markdown
added use of '...' for variable amount of arguments
> [php/en] Added variable amount of parameters as of php 5.6+

- python.html.markdown
Updated official python docs link to always use the latest version of python 2.x
> Updated official python docs link.

- javascript.html.markdown
Added the setInterval function provided by most browsers
> [javascript/en] Added setInterval

- de-de/bash-de.html.markdown
- de-de/git-de.html.markdown
The first two sections
- variables
- conditionals
rest will follow in the next days
> [bash/de] #1452 Several sections need to be translated

- javascript.html.markdown
> [javascript/en] Spacing and capitalization of comments

- fsharp.html.markdown
change github flavored markdown programming language to fsharp
correct typos
> [fsharp/en] correct a few simple mistakes

- chapel.html.markdown
undestanding -> understanding
uninterupted -> uninterrupted
> [chapel/en] Fix typos

- java.html.markdown
- matlab.html.markdown
Where neighboring lines are in spaces, but this line is indented in tabs.
>  [java,matlab/en] Inconsistent tabs and spaces.

- fr-fr/livescript-fr.html.markdown
Correct the translator github repository
> [livescript/fr] Correct the translator github repository

- c.html.markdown
Details in the commit message.
I'm not a C expert by any means, but the current VLA example didn't seem to work as intended for me.  This is my attempt at a simple fix.
> [C/en] Fix VLA example

- javascript.html.markdown
Small change, but I think showing that `int + strings = string` is good, since that's somewhat atypical.
Didn't add myself to contributors since it's so minor.
> [javascript/en] Adding a small blurb to extend upon string concatenation

- ru-ru/php-ru.html.markdown
Delete unnecessary line on english.
> Delete unnecessary line on english.

- java.html.markdown
Short overview about enum type.
> [java/en] Enum Type

- hu-hu/coffeescript-hu.html.markdown
Just a Hungarian translation of the currently existing coffeescript.html.markdown file, no new content added.
> [coffeescript/hu] add Hungarian translation

- fsharp.html.markdown
improve whitespace around operators for readability
> Make whitespace more consistent

- matlab.html.markdown
Added some entries about:
1) Generating an array with increment other than 1
2) More concise transpose operators
3) A couple more plotting options
4) Some complex number specific math functions
5) the find() function, which I use quite a bit and think others might find useful
> Added a couple functions to the matlab doc.

- de-de/haskell-de.html.markdown
Added changes from a7b8858 to HEAD (b5cb14703) to the
german version, where appropiate.
> [haskell/de] Synchronized with english version

- css.html.markdown
Reverts adambard/learnxinyminutes-docs#1936
> Revert "Closed a comment that was not properly closed"

- pt-br/json-pt.html.markdown
There were some typos, and added more information (translated from the en version).
> [json/pt-br] Improved the JSON document translation

- swift.html.markdown
Added MARK with separator and a couple of mutable explicit declarations of empty Array/Dictionary
> Include MARK style and two collection declarations

- git.html.markdown
Also mentions graph flag for the log command
> Adds documentation for revert command

- php.html.markdown
Line 159 - echo isn't a function, print() is
Line 337 - unneeded semicolon (it's a pre-test loop)
> [php/en] echo fix and cleanup

- pt-br/java-pt.html.markdown
Translating java interfaces, abstract classes and enum to pt-br
> [Java/pt-br]

- pt-br/css-pt.html.markdown
fixing selector name(color) that was improperly translated
> [CSS/pt-br]

- python.html.markdown
the existing info seems incomplete
> add more details on truthiness

- ru-ru/php-ru.html.markdown
Edit translate for creating new object of class using new.
> Edit translate for creating object.

- ru-ru/python-ru.html.markdown
Edit descriptions for function setdefault.
> Edit descriptions for function setdefault.

- css.html.markdown
- More relevant introduction
- More consistent and clear wording
- More consistent formatting
I can see you're swamped with Hacktoberfest PRs, but I do feel this improves the article by a fair amount.
> [css/en] Update CSS for clarity.

- d.html.markdown
overrideing -> overriding
referece -> reference
Also made minor adjustment to how the "overrideing" sentence was formatted. It seemed confusing and awkwardly styled.
> [D/en] Fixed two typos and made minor formatting adjustment

- xml.html.markdown
Also fixed incorrect code and added information about XML schemas. Also added links and references.
> [xml/en] Grammar, formatting. Made more 'inlined'.

- nl-nl/amd-nl.html.markdown
Still a bit unsure about renaming the variables in the code examples.
> [AMD/nl] Added Dutch translation of AMD.

- matlab.html.markdown
Give information about using comments for code sections
> Add section heading info (MATLAB)

- fr-fr/perl-fr.html.markdown
Perl deserves a French translation :)
> [perl/fr] Add French translation for Perl 5

- fr-fr/d.html.markdown
Hi,
I translated the D learnbyexample to french.
Thanks for reviewing :-)
> [d/fr] adds translation in french for dlang

- fsharp.html.markdown
modelling -> modeling (in two instances)
compatability -> compatibility
> [fsharp/en] Fixed two typos

- ruby.html.markdown
+ Added a better description for 'nil'
> Fixed typo in docs

- es-es/brainfuck-es.html.markdown
Hi,
I've updated the Spanish brainfuck article with the latest changes of the English one. Also, I've fixed some typos and I've changed some translations to feel more natural in Spanish.
Regards.
> [brainfuck/es] Update and fix Spanish brainfuck article

- fr-fr/css-fr.html.markdown
This corrects minor French mistakes
> [css/fr] Improves the translation

- julia.html.markdown
It is noteworthy to mention that strings can be directly compared with comparison operators which is a not available in many languages.
> Strings can be lexicographically compared with comparison operators

- hu-hu/coffeescript-hu.html.markdown
> "lang: hu-hu" line was missing in hungarian coffeescript

- perl6.html.markdown
> Fix typo in Perl 6 example (closes #2025)

- fr-fr/javascript-fr.html.markdown
Hi,
I translated updates from https://github.com/adambard/learnxinyminutes-docs/pull/1905 to french.
I took the reviews you made there into account and removed the iterators part and added for..in / for..of loops.
> [javascript/fr]: Add es6 updates to javascript

- json.html.markdown
Also removed some duplicate information.
> [json/en] Cut noise, formatting, links.

- sass.html.markdown
Very small tweaks to wording.
The big changes are cleaning up comment block spacing and formatting to enforce consistency throughout the document.
> [sass/en] Cleaning up wording and formatting

- cs-cz/python3.html.markdown
- es-es/python3-es.html.markdown
- fr-fr/python3-fr.html.markdown
- ru-ru/python3-ru.html.markdown
- tr-tr/python3-tr.html.markdown
- zh-cn/python3-cn.html.markdown
See a1ed02d6fad2b39137f52c6a04264a59e237d747
> [python3/cs] [python3/es] [python3/fr] [python3/ru] [python3/tr] [python3/zh] Corrects the result of math.sqrt(16)

- python3.html.markdown
Erroneous outputs corrected and added a little clarity on the subject.
> [Python 3] Fixed erroneous outputs stated in comments

- powershell.html.markdown
I started from the Bash tutorial and converted it to PS1 + Added PowerShell specific stuff.
Related Issues:
https://github.com/adambard/learnxinyminutes-docs/issues/1020
https://github.com/adambard/learnxinyminutes-docs/issues/1750
> New language: PowerShell

- common-lisp.html.markdown
Links :
: CLiki
: Awesome Common Lisp
: COMMON LISP A Gentle Introduction to Symbolic Computation
: Common-Lisp.net
> [common-lisp/en] More links

- pl-pl/ruby-pl.html.markdown
> [Ruby/pl-pl] Translation for Ruby from en-en to pl-pl

- fi-fi/markdown-fi.html.markdown
The whole document is translated now.
> [markdown/fi] Translate markdown/en to Finnish

- less.html.markdown
duplicated sass tutorial to less. address #1112.
> [less/en] Add Less tutorial, similar to sass

- cs-cz/markdown.html.markdown
Czech translation for Markdown
> [markdown/cs] Czech translation for Markdown

- pt-br/javascript-pt.html.markdown
- Removing line 439 that is already translated
- Translating line 509
> fixing javascript translate

- d.html.markdown
Change `Futhermore` to `Furthermore`.
> [d/en] Fix Typos

- elisp.html.markdown
responsability -> responsibility
> [elisp/en] Fixed minor typo in disclaimer

- fr-fr/typescript-fr.html.markdown
> [TypeScript/fr] Make TypeScript indentation consistently 2 spaces

- elm.html.markdown
Previously attempted at #1164 but this version is a bit more fleshed out, updated for 0.16, and I've paid special attention to the order in which concepts are introduced.
As cited in the other PR, there is no Markdown parser for Elm, so I used Haskell. It should be okay.
Feedback welcome, but the intention is to cover common cases and best practices, not be a definitive reference.
> [elm/en] Create intro to Elm

- cs-cz/sass.html.markdown
> [sass/cs] Czech translation for Sass

- java.html.markdown
Fix spacing inconsistency in PennyFarthing Constructor
> [Java/EN] Fix Spacing Inconsistency

- tmux.html.markdown
> Update tmux home page.

- tmux.html.markdown
I'm sorry, missed a link in #2081 @geoffliu
> [tmux/en] Update tmux home page, again.

- factor.html
- wolfram.md
> Add tutorials (Factor, Wolfram Language)

- d.html.markdown
> fix parallelism example typo

- pythonstatcomp.html.markdown
PEP8 fixes (spaces and multiline statements) - in Python readability and code style matters. :)
> Statistical computing with Python - PEP8 fixes

- php.html.markdown
> [PHP/en] Add binary number example.

- julia.html.markdown
Add some extra type of declaration syntax for arrays
> [julia/en] Add different array declaration syntax

- groovy.html.markdown
sdkman (sdk in console) is the new name for gvmtool
> Updated to sdkman instead of GVM for installing groovy

- powershell.html.markdown
2nd attempt at fixing the code blocks.
Didn't manage to run the middleman script offline but it should work this time :)
> [PowerShell/en]: didn't recognize code blocks

- es-es/latex-es.html.markdown
- es-es/php-es.html.markdown
I've translated the PHP and LaTeX learning files to spanish.
> Translate learn PHP and LaTeX to es-ES

- scala.html.markdown
Added a note about importing Java classes to Scala.
> [scala/eng] Added Java import to misc

- elm.html.markdown
This patch includes some minor improvements to my previous contribution, #2054. It also includes typofixes from #2059, thanks @we-build-dreams! (I fixed the merge conflicts so it's better to do this in one go.)
> [elm/en] Minor copyediting and typo fixes

- hu-hu/yaml-hu.html.markdown
A Hungarian translation of the YAML article, no new content added
> [yaml/hu] add Hungarian YAML translation

- zh-cn/lua-cn.html.markdown
1. fib() fixed.
2. add 'local' in `LoudDog:new`.
3. more explain of self-reference.
4. enable Markdown syntax highlight of section `4. Modules.`
5. completed translation of the end.
6. update link style to Markdown.
> [lua/cn] synchronized with EN version. (revised edition)

- solidity.html.markdown
Solidity is a contract programming language for the Ethereum blockchain. For more details, see:
http://solidity.readthedocs.org/en/latest/
> Added Solidity, Ethereum's Contract Programing Language

- perl.html.markdown
These topics are central to modern usage of Perl.
> [perl/en] Add info on references, modules, and objects

- de-de/go-de.html.markdown
Improvements to intro and resource information sentences plus fixing small typos.
> [go/de] More infos, reformulation and typo fixes for Go.

- pt-br/ruby-pt.html.markdown
Changes:
- Remove `each` duplication
- Add more resources
> [ruby/pt-br] - Update Ruby Resources

- python.html.markdown
- python3.html.markdown
> Added Python Resources

- ja-jp/php-jp.html.markdown
- ja-jp/php.html.markdown
Changes
-------------------
* Create `ja-jp/php.html.markdown` file
> [php/ja] Translated PHP tutorial to japanese

- java.html.markdown
Fixed statement on line 441 to say that it is _not_ good practice to keep many classes in the same file.
> [java/en] Fixed statement about many classes in one file

- fi-fi/ruby-fi.html.markdown
I chose to skip translating the methods, variables and other code because they looked funny.
> [ruby/fi] Translate Ruby docs to Finnish

- php.html.markdown
Updated add item to associative array.
> [php/en] Update php.html.markdown

- swift.html.markdown
> Add documentation comment for If let

- pt-br/amd.html.markdown
I've translated the whole article about AMD.
> [AMD/pt-br] Asynchronous Module Definition translation

- ocaml.html.markdown
> Fix typo in ocaml doc

- julia.html.markdown
dimentional -> dimensional
fuction -> function
> [julia/en] fix typos

- pythonstatcomp.html.markdown
> Write a bit better code

- ru-ru/typescript-ru.html.markdown
> [typescript/ru] Added Russian translation of TypeScript tutorial

- factor.html.markdown
> [factor/en] minor typo. dont -> don't

- git.html.markdown
> Update link to Salesforce Git cheat sheet

- make.html.markdown
> [make/en] enviroment -> environment

- nl-nl/xml-nl.html.markdown
> [xml/nl] Add Dutch XML translation

- elm.html.markdown
> [elm/en] Fix typos

- es-es/forth-es.html.markdown
Adds the Spanish translation of Forth.
references #1428
> [Forth/es] Adds Forth in Spanish

- csharp.html.markdown
- pt-br/csharp.html.markdown
Alter header configuration following the main rules.
> Alter header configuration

- csharp.html.markdown
- pt-br/csharp.html.markdown
I started the feature to translate csharp docs to portuguese from Brazil
(pt-br).
Still not finish, but I want to send my first part of contribution.
> Create a new translate for csharp to pt-br language

- csharp.html.markdown
- pt-br/csharp.html.markdown
Created new more translated lines to pt-br language.
> New translated words

- ro-ro/python-ro.html.markdown
Fix some of the line lengths for the Romanian version of the python article.
> [python/ro] fix line lengths

- ro-ro/bash-ro.html.markdown
Tweaked around with the old translations
> [bash/ro] Changed some old stuff and added diacritics

- asymptotic-notation.html.markdown
Big-O Cheatsheet is a great page for visualising common big-O considerations, it should be included.
> [asymptotic-notation/en] added link to Big-O Cheat Sheet

- pt-br/ruby-ecosystem-pt.html.markdown
The whole article was translated and revised.
> [ruby-ecosystem/pt-br] Full translation to portuguese

- es-es/yaml-es.html.markdown
Add more content on YAML-es page and fix some typos.
> [yaml/es] Update yaml-es content

- cs-cz/json.html.markdown
> [json/cs] JSON translation to cs_CZ

- nl-nl/json.html.markdown
I added a Dutch translation for the JSON document.
> Add translation to Dutch for json

- asymptotic-notation.html.markdown
* added small-o, small-omega and theta notations
* clarified difference between big-o and small-o notations and big-omega and small-omega notations
* slightly modified big-o and big-omega notations content
> [asymptotic-notation/en] Added content, closes #2174

- c.html.markdown
removed whitespaces all over document
> [c/en] fixed whitespaces

- java.html.markdown
> [java/en] removed whitespaces, fixed content extending beyond 80 chars

- make.html.markdown
> [make/en] fixed typos and spellings, added content

- asymptotic-notation.html.markdown
> Fixed typos and content exceeding beyond 80 chars

- de-de/hack-de.html.markdown
I have translated the Hack article to German. Translating this article was fun because I've learned something new about the language :+1:
> [hack/de] Hack article translation to German

- ro-ro/coffeescript-ro.html.markdown
One-to-one translations of coffeescript to Romanian.
> [coffeescript/en] Add coffeescript translation to Romanian

- pt-br/paren-pt.html.markdown
Content translated and revised.
> [paren/pt-br] Translation to Brazillian Portuguese

- nl-nl/json-nl.html.markdown
> [nl/JSON] Add dutch translation of JSON

- es-es/javascript-es.html.markdown
Changed wording for overview of comments so it would make more sense to a beginner. Corrected grammar error.
> Changed wording for comments section

- tmux.html.markdown
> Updated tmux link

- de-de/git-de.html.markdown
- git.html.markdown
I made some improvements to the german translation of the Git document.
I also add some more example commands.
> Improvements for german translation of Git.

- kotlin.html.markdown
I can see an existing pull request for Kotlin - https://github.com/adambard/learnxinyminutes-docs/pull/1074 - but it does not seem to have been updated for a while.
> [kotlin/en] Add Kotlin

- nl-nl/typescript-nl.html.markdown
Add dutch translation of TypeScript
> [nl/TypeScript] Add dutch translation of TypeScript

- de-de/bash-de.html.markdown
> [bash/de] follow english original

- de-de/haskell-de.html.markdown
I changed a few simple typos (missing umlaut or missing letter, extra letter that didn't belong) and spelling errors.
> [haskell/de] Fixed a few typos and spelling errors

- fsharp.html.markdown
dont -> don’t
defintion -> definition
> [fsharp/en] typos

- css.html.markdown
- Reduced almost all lines to less than 80 characters in length.
- ie -> e.g.
- occuring -> occurring (line 209)
> [css/en] several fixes

- markdown.html.markdown
> fixed content extending beyond 80 chars

- kotlin.html.markdown
Added extra Kotlin links to the "Further Reading" section. Also removed unnecessary brackets from example of using a for loop.
> [kotlin/en] Add links to other resources

- git.html.markdown
> fixed whitespaces, content extending beyond 80 chars

- nim.html.markdown
The language was changed to JavaScript in [this commit](https://github.com/adambard/learnxinyminutes-docs/commit/f3b10beb01795bf7513ec8d06c9e90ab98df7a83).
> [nim/en] Correct syntax highlighting

- ocaml.html.markdown
Change into what is supposed to be better style, or maybe a more idiomatic way of writing the predicate.
> Change anonymous function in List.filter example

- zh-cn/common-lisp-cn.html.markdown
> [Common Lisp/zh-cn] Add ANSI Common Lisp

- it-it/ruby-ecosystem-it.html.markdown
as requested in https://github.com/adambard/learnxinyminutes-docs/pull/1700
> Add `lang: it-it` to metadata

- zh-cn/lua-cn.html.markdown
the filenameis is "learn-cn.lua", so the command should be "lua learn-cn.lua".
> the filenameis is "learn-cn.lua", so the command should be "lua learn-cn.lua".

- cs-cz/elm.html.markdown
> [elm/cs] Add Czech translation of Elm

- ru-ru/php-ru.html.markdown
"A constant" should be translated as a "Константа"
> Small change

- objective-c.html.markdown
> [objective-c/en] Grammar + spelling errors

- es-es/self-es.html.markdown
Sorry about the inconveniences :coffee:
> self spanish translation

- cs-cz/hack.html.markdown
> [hack/cs] Add cs_CZ locale for Hack

- java.html.markdown
> [Java/EN] Fixed typo(s) in Java

- zh-tw/elixir-tw.html.markdown
- [v] PR touches only one file (or a set of logically related files with similar changes made)
- [v] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [v] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [v] Seriously, look at it now. Watch for quotes and double-check field names.
[Elixir/zh-tw] Translation for Elixir of Traditional Chinese.
> [Elixir/zh-tw] Translation for Elixir of zh-tw

- el-gr/java-gr.html.markdown
[Java/el] Translated Java to Greek
> [Java/el] Translated Java to Greek

- typescript.html.markdown
Fix url for language specifications
> [TypeScript/en]

- tr-tr/fsharp-tr.html.markdown
Adding Turkish translation of fsharp tutorial
> [fsharp/tr-tr] Translation of fsharp tutorial to Turkish

- tr-tr/python3-tr.html.markdown
> small additions.

- tr-tr/typescript-tr.html.markdown
- Translated into Turkish
- Type checked in Playground to make sure that UTF-8 does not cause any problems.
> [typescript/tr-tr] TypeScript Turkish translation

- es-es/asymptotic-notation-es.html.markdown
Hi. 
Translation for asymptotic-notation.
> [asymptotic-notation/es] es-es translation for asymptotic-notation

- es-es/typescript-es.html.markdown
> typescript spanish translation

- es-es/pythonstatcomp-es.html.markdown
> pythonstatcomp spanish translation

- vim.html.markdown
Apologies for for closing my previous pull request and opening it again. I managed to screw up the branches of my repo, which invalidated my previous pull request.
Here is the link to my [previous pull request](https://github.com/adambard/learnxinyminutes-docs/pull/1355).
And the short description here again:
I've added a new tutorial for Vim as a tool. Please let me know if there's any changes I should make, or anything else I should add. Thanks!
> [vim/en] Added vim.html.markdown (Reopened #1355 after closing it myself)

- git.html.markdown
> Add Git Reflog Section To Git.html.markdown

- uk-ua/javascript-ua.html.markdown
> [javascript/uk-ua] fix few small mistakes in code and comments

- git.html.markdown
Issue: https://github.com/adambard/learnxinyminutes-docs/issues/2258
> Fix git pull --rebase explanation

- el-gr/css-gr.html.markdown
> Comment out HTML section

- ro-ro/haskell-ro.html.markdown
- ro-ro/latex-ro.html.markdown
Sorry for opening a request for two files! but I thought it would be redundant to have a whole pull request just for a few typos.
> [haskell/ro, latex/ro] Added Haskell translation, fixed Latex typos

- cs-cz/css.html.markdown
> [css/cs] Czech translation for CSS

- cs-cz/javascript.html.markdown
Czech translation for JavaScript
> [javascript/cs] Czech translation for JS

- es-es/groovy-es.html.markdown
- groovy.html.markdown
Although the code examples have not been translated in their entirety, now the
guide for groovy is in Spanish.
> [groovy/es] Groovy translated to Spanish

- zh-cn/zfs-cn.html.markdown
This is to add Simplified Chinese translation for zfs. Kindly review and let me if any update is needed.
thanks,
Alan
> zfs/zh-cn add simplied Chinese translation for zfs

- solidity.html.markdown
With changes in Ethereum and Solidity best practice, I've updated the doc to highlight security risk - and fix errors and/or bad security patterns in the previous doc
> Security additions + edits

- python.html.markdown
> [python/en] Add dict .items() function

- bash.html.markdown
- javascript.html.markdown
- pcre.html.markdown
`trap` is a very important command to intercept a fatal signal, perform cleanup, and then exit gracefully. It needs an entry in this document.
Here a simple and most common example of using `trap` command i.e. cleanup upon receiving signal is added.
> Add an example of trap command 

- es-es/c-es.html.markdown
Hi.
Updated translation: Further reading.
> [C/es] Updated translation

- es-es/css-es.html.markdown
Hi.
Updated translation: resources and further reading.
> [css/es] Updated translation

- es-es/git-es.html.markdown
Hi.
Updated translation: further information
> [git/es] updated further information

- pt-br/php-pt.html.markdown
Hello, 
I added an example of echo and print and added one ; was missing on line 69.
(sorry my bad english)
> correcoes ortograficas e adicao de alguns exemplos

- matlab.html.markdown
This is pretty helpful for MATLAB users especially in exploratory programming and demos
> Add a section on code sections/cells

- csharp.html.markdown
Added example of using string interpolation
> [csharp/en] Add string interpolation

- python.html.markdown
More details and code on the same example as before.
> [python/en] Generator explanation for python

- hu-hu/typescript-hu.html.markdown
Hungarian translation of the TypeScript entry, no new content added
> [typescript/hu] add Hungarian TypeScript translation

- pt-br/python3-pt.html.markdown
- python3.html.markdown
The third line of the sample is invalid, only two values are generated.
> Output example had a value more

- bash.html.markdown
Added a few simple examples of parameter expansion and brace expansion.
> [bash/en] basic parameter expansion, and brace expansion

- de-de/python3-de.html.markdown
It's based on the german translation of python2, because of the similarities. 
Because of this, I kept the original translator in the credits.
> [python3/de] Add german translation

- nl-nl/markdown-nl-html.markdown
Add dutch translation of markdown
> [nl/Markdown] Add dutch translation of markdown

- kotlin.html.markdown
Added examples of Kotlin sequences. Also made some minor capitalization and punctuation changes.
> [kotlin/en] Add examples of sequences

- racket.html.markdown
- standard-ml.html.markdown
Details added include:
* Other types of `let` expressions
* Structs
* `car` and `cdr` additional helper functions
> [racket/en] Add more details about Racket

- rust.html.markdown
> Minor formatting and wording change in rust doc.

- python3.html.markdown
Add multiple inheritance example.
Put Modules chapter before Classes since this concept will be used.
> Python3/en: multiple inheritance

- id-id/markdown.html.markdown
Added Indonesian translation for markdown
> Added id-id translation for markdown

- rst.html.markdown
Add a simple introduction to Restructured Text.
> [en/RST] Add RST introduction

- de-de/sass-de.html.markdown
Original pull request: https://github.com/adambard/learnxinyminutes-docs/pull/2072
> Added suffix to filename and changed minor content errors

- php-composer.html.markdown
Feedback desired. Hope you like it!
> [php-composer/en] Add new tool document for Composer, PHP's dependency manager

- de-de/java-de.html.markdown
This is an initial translation of the original Java_en markdown into german language.
> [java/de] Initial translation added.

- c++.html.markdown
> Added the Logical and bitwise operators section, fixes merge issue with  #1817

- csharp.html.markdown
- [ X ] PR touches only one file (or a set of logically related files with similar changes made)
"DidWeCreateEnoughBycles" -> "DidWeCreateEnoughBicycles"
> Correct "Bycles" to "Bicycles""

- julia.html.markdown
Update Dict Syntax and Set Syntax
> Update Dict and Set Syntax

- python.html.markdown
- python3.html.markdown
Updated both Python 2 and 3 documentation.
- [x ] PR touches only one file (or a set of logically related files with similar changes made)
> [python/en] Set, dict, and generator comprehensions

- java.html.markdown
- [Y ] PR touches only one file (or a set of logically related files with similar changes made)
- [N] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [Y] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [Y ] Seriously, look at it now. Watch for quotes and double-check field names.
Adding reference for a treemap
> [Java/en] Adding a reference for treemap

- css.html.markdown
Adding border related styleguides. Most of the modern designs have borders for their elements.
> [CSS/en] Adding border related styleguides

- id-id/java-id.html.markdown
> [java/id-id] ID translation

- bash.html.markdown
Incorporates information from #1807 and #1465. I attempted to make the information a little less basic and moved the "prologue" I had initially into the bash code itself.
> [bash/en] Addition to bash

- smallbasic.html.markdown
New article about SmallBASIC.
Includes a brief history of the project, sample program and links to other resources.
> [smallbasic/en] New article about SmallBASIC

- smallbasic.html.markdown
Thanks for accepting my article. This is just a minor correction and some other added information.
Cheers
Chris
> [smallbasic/en] minor fact check fix

- c++.html.markdown
> [C++/en] Some minor (mostly stylistic) fixes

- zh-cn/kotlin-cn.html.markdown
Simplified Chinese translation for Kotlin tutorial.
> [kotlin/cn] Chinese translation for Kotlin tutorial

- it-it/rust-it.html.markdown
- rust.html.markdown
> Translation to Italian of Rust tutorial

- zh-tw/bash-tw.html.markdown
> [bash/zh-tw] add zh-tw translation

- sv-se/json-sv.html.markdown
> [json/sv-se] Synced with english version.

- fortran95.html.markdown
Here is a Fortran tutorial. I really don't know Fortran though so this was a learning exercise for me, it would be great if someone who does know it could check it over!
> [fortran/en] Adding a Fortran (95) Tutorial

- fsharp.html.markdown
I was confused when reading the sieve function and thought it could be explained a little more. I got some help from http://hestia.typepad.com/flatlander/2010/07/f-pattern-matching-for-beginners-part-4-lists-and-recursion.html
> [fsharp/en] Explain the cons pattern, and introduce recursion keyword

- es-es/powershell-es.html.markdown
> [ps/es] Added initial version of powershell Spanish guide (based on the latest English version)

- fr-fr/rust-fr.html.markdown
Suggestions et/ou des commentaires bienvenus!
---
> [rust/fr] - French translation for Rust tutorial

- c.html.markdown
> Remove undefined behavior

- less.html.markdown
> Fix inconsistencies and add resource links

- es-es/java-es.html.markdown
This replaces #1952, with the identation issue fixed.
> Added info on Java generics in Spanish.

- java.html.markdown
---
java.html.markdown | 8 ++++++--
1 file changed, 6 insertions(+), 2 deletions(-)
> java: In Java 8, interfaces can have default method.

- zh-cn/yaml-cn.html.markdown
> Sync with the English version & minor tweaks

- vim.html.markdown
It is a a text --> It is a text
> Fix typo on vim page

- vim.html.markdown
> Fix another typo on vim page

- zh-cn/vim-cn.html.markdown
> [vim/zh-cn] translation

- python3.html.markdown
The previous version of this file had the original Dive Into Python, which was written with Python 2 in mind.
It has come to my attention that the author of the original has published an updated version designed for Python 3, so I added this version back in.
> [python3/en] Adding "Dive Into Python 3"

- fr-fr/HTML-fr.html.markdown
- html.html.markdown
The French HTML tutorial is not visible from the webpage because there is no English language HTML tutorial. So this is an almost direct translation of the French version to English. If anything I find that this tutorial is a little basic for this site but it would fix the above problem properly.
> [html/en] adding translation of html/fr

- cs-cz/go.html.markdown
Adding Czech **Golang** translation.
> add Czech [cs-cz] translation of the Go intro.

- Meteor.html.markdown
- livescript.html.markdown
The brief description on meteor js .
> Meteor Js 

- python3.html.markdown
> [python3/en]correction for the set comprehension in py3

- pt-br/python3-pt.html.markdown
[python3/pt-br] - fix head description for correct layout view on the site main page https://learnxinyminutes.com
> [python3/pt-br] - fix head description

- zh-cn/ruby-cn.html.markdown
> [ruby/zh-cn] sync with English version & minor tweaks

- kotlin.html.markdown
> [kotlin/en] Add "if" usage as an expression

- git.html.markdown
> [git] Add very cool interactive tutorial

- pt-br/self-pt.html.markdown
Adds a brazilian portuguese translation of Self language.
Signed-off-by: Ricardo de Almeida Gonzaga <xricardotk@gmail.com>
> [self] add pt-br translation

- pt-br/julia-pt.html.markdown
This is a translation of the article published in the site to Brazilian Portuguese.
Isso é uma tradução do artigo postado no site para Português Brasileiro.
> [pt-br] Julia

- pyqt.html.markdown
> Fixed a bad naming which overlapped with C++ version

- logtalk.html.markdown
> [logtalk/en] Initial version of the Logtalk language tutorial

- ru-ru/javascript-ru.html.markdown
> [javascript/ru] function body is missed

- CHICKEN.html.markdown
First draft of the article for CHICKEN scheme.
> [CHICKEN/en] Adding CHICKEN

- zh-cn/visualbasic-cn.html.markdown
> [vb/zh-cn]Update translators info

- latex.html.markdown
Add table of contents
Add small changes in style:
- LaTeX -> \LaTeX
- improve alignment for formulas in Math section
> [latex/en] Add Hyperlinks description

- c.html.markdown
Added a note mentioning that string.h needs to be included in order to use strlen() function
> [C/en] Add note about string.h header

- id-id/json-id.html.markdown
> [json/id] Fix the missing ":" on YAML Frontmatter

- id-id/asciidoc-id.html.markdown
> [asciidoc/id] Create asciidoc-id.html.markdown

- id-id/pyqt-id.html.markdown
> [pyqt/id] Create pyqt.html.markdown

- qt.html.markdown
- "is beautiful for creating applications" -> "is great for creating applications"
- Added a link to PyQt page
- changed "Slots and Signals" link from Qt 4.8 to Qt 5, to maintain consistency with "Widgets" link
- Furter -> Further
- Tidy up "Further Reading"
> [qt/en] Tidy up

- id-id/smallbasic-id.html.markdown
- id-id/smallbasic.html.markdown
> [smallbasic/id] Create smallbasic-id.html.markdown

- clojure.html.markdown
- fr-fr/clojure-fr.html.markdown
> Add as-> macro documentation

- csharp.html.markdown
Rebased my earlier PR from [https://github.com/adambard/learnxinyminutes-docs/pull/1291]. (Sorry @vendethiel, I didn't manage to get around to this ><)
> [csharp/en] Add more C# 6 features

- bash.html.markdown
Getting is redundant.
Observe, not observer.
> Reword pwd comments

- es-es/html-es.html.markdown
Hello everyone! I translated HTML to spanish, Any questions I am ready to answer. thank you.
> Translation - HTML english to spanish

- id-id/coffeescript-id.html.markdown
> [coffeescript/id] Create coffeescript-id.html.markdown

- html.html.markdown
One typo and closed anchor element
> [html/en] few changes to the file

- it-it/bash-it.html.markdown
4e5439c21f5ab5ba33e46926b2fc5e44e25362ae
d1216a4253c1b03641c10b171030d04227ad8408
8cd7c230aaa708dffb544887baa85de8f3377251
b16c7ee2d8b41b5db4f713360280c284ca9b1a80
527eab7108f4b5587f4a4afd9dad53ef0de2c565
> [bash/it] Bring this version up to date with the english one

- markdown.html.markdown
> [markdown/en] Fixed "<br />" example tag by showing it as code

- kotlin.html.markdown
> [Kotlin/en] correct object clarification

- kotlin.html.markdown
> [Kotlin/en] Add when smartcast example

- kotlin.html.markdown
> [Kotlin/en] Add more destructuring examples

- es-es/kotlin-es.html.markdown
> [kotlin/es] Translated Kotlin to spanish

- es-es/vim-es.html.markdown
> [vim/es] Translated Vim to spanish

- es-es/php-composer-es.html.markdown
> [php-composer/es] Translated php-composer to spanish

- es-es/binary-search-es.html.markdown
- es-es/html-es.html.markdown
Hello, I have translated file binary search to Spanish, if there is any doubt I am willing to resolve it. Thank you
> Translate binary search to spanish 

- swift.html.markdown
- [✔] PR touches only one file (or a set of logically related files with similar changes made)
- [✔] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [✔] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [✔] Seriously, look at it now. Watch for quotes and double-check field names.
> Updated code according Swift v.3

- ru-ru/binary-search-ru.html.markdown
> line "lang: ru-ru" was missing

- ru-ru/swift-ru.html.markdown
- [ ✔] PR touches only one file (or a set of logically related files with similar changes made)
- [ ✔] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [ ✔] YAML Frontmatter formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [✔ ] Seriously, look at it now. Watch for quotes and double-check field names.
> [swift/ru]  Updated code to Swift v.3, added some new sections from english version

- de-de/asciidoc-de.html.markdown
> [asciidoc/de] Translate asciidoc to german

- java.html.markdown
- Added documentation and sample code pertaining to try-with-resources to
the Java documentation.
- Converted all Oracle, Amazon and GitHub http links to https.
- Added my name to the contributors list since this is my second time
contributing.
- Special shoutout to @enkidevs for teaching me about try-with-resources.
Sorry for the previous bad PR. This is for real. Happy Hacktoberfest.
> Added try-with-resources to Java docs

- csharp.html.markdown
- elixir.html.markdown
> Csharp parallel

- es-es/binary-search-es.html.markdown
- es-es/dynamic-programming-es.html.markdown
- es-es/html-es.html.markdown
Hello, dynamic file translated to Spanish programming, any questions I am ready to answer. Thank you
> Translate - Dynamic Programming to spanish 

- pt-br/dynamic-programming-pt.html.markdown
> [dynamic-programming/pt-br] Translation to portuguese

- kotlin.html.markdown
- anonymous function -> lambda expression: they are different in Kotlin.
- change coding style according to Kotlin Reference.
- Remove remove unnecessary semicolons.
- Replace code block language `java` with `kotlin`.
---
kotlin.html.markdown | 37 +++++++++++++++++++------------------
1 file changed, 19 insertions(+), 18 deletions(-)
> Several changes on Kontlin.

- bash.html.markdown
There is no $ when one referencec the name of a variable as Bash is not PHP.
> Removed excessive dollar signs

- pt-br/amd.html.markdown
Fix tag language to pt_br and not ptr_br
> [AMD/pt_br]fix tag language pt_br for amd

- sass.html.markdown
> [sass/en] Fix typos in Sass tutorial

- less.html.markdown
> [less/en] Fix typos and improve styles

- sass-es.html.markdown
> [sass/es-es] Add Spanish version for the Sass tutorial

- pyqt.html.markdown
> useless "lang: en"

- de-de/html-de.html.markdown
> [html/de] Translate html to german

- logtalk.html.markdown
> Fixes and improvements to the Logtalk tutorial

- pt-br/vim-pt.html.markdown
> [vim/pt_br] Translate vim to portuguese

- python3.html.markdown
prev. docs were confusing, did not show how to actually divide.
> [python3] updated docs on division for python3

- python3.html.markdown
* explain that you can place the human and bat classes into seperate
files
* explain how to import specific functions from other files
> Add python3 class notes

- de-de/go-de.html.markdown
Just some basic typos that needed fixing
> [go/de] fixing typos

- csharp.html.markdown
This was a really cool & useful trick/feature that I found while
learning C#.
> Added example of C# inline properties

- es-es/sass-es.html.markdown
> Added line "lang: es-es"

- latex.html.markdown
Follow through for PR https://github.com/adambard/learnxinyminutes-docs/pull/1821
> [latex/en] minor typo fixes

- pt-br/php-composer-pt.html.markdown
> [php-composer/pt_br] Translate Composer to portuguese

- es-es/less-es.html.markdown
> [less/es-es] Add Spanish version of Less tutorial

- uk-ua/ruby-ua.html.markdown
> [ruby/uk-ua] Created Ukrainian's Ruby translation

- c++.html.markdown
> [c++/en] Fix typo of iterator

- kdb+.html.markdown
Added a new file for kdb+, an APL like language and database used heavily in finance
> [kdb+/en] Added new file for kdb+

- pt-br/asciidoc-pt.html.markdown
> [asciidoc/pt_br] Translate asciidoc to portuguese

- ko-kr/xml-kr.html.markdown
> [xml/ko-kr]Translate XML doc

- ko-kr/markdown-kr.html.markdown
> [md/ko-kr]Translate Markdown doc

- pt-br/tmux-pt.html.markdown
Grammar fixes and update to a more comprehensive language to explain concepts. In addition updating the tmux.conf as done on the original doc.
> [tmux/pt-br] Grammar fixes + comprehensive language

- jquery.html.markdown
I felt like this part was kind of disorganised, with stuff being used at the beginning and explained afterwards, thus creating repetition
> [jquery/en] Reorganisation of Part 2 ( Events and Effects )

- zh-cn/latex-cn.html.markdown
> [latex/zh-cn] translation

- nl-nl/xml-nl.html.markdown
> Fix the xml file which was saved as ISO-8859 or Latin 1 which wasn't being generated before

- fr-fr/dynamic-programming-fr.html.markdown
> A translation of dynamic programming in french

- fr-fr/binary-search-fr.html.markdown
This commit solves issue #2435
> A translation of the binary search in french

- jquery.html.markdown
The class name "div" might be confusing, and there was a better class name in the comments
> [jQuery/en] Changes ambiguous class name

- fr-fr/jquery-fr.html.markdown
I translated the jQuery article to French.
> [jquery/fr] Adds French translation for jQuery

- es-es/jquery-es.html.markdown
- jquery.html.markdown
This fixes 2 syntax errors in the jQuery code ( discovered by @vendethiel )
> [jQuery/en] [jQuery/es] Fixes syntax errors

- fr-fr/vim.html.markdown
> [vim/fr-fr] New translation

- perl6.html.markdown
> [perl6] Add myself as contributor

- es-es/java-es.html.markdown
- java.html.markdown
> Adding new Java 8 features

- CHICKEN.html.markdown
> [CHICKEN/en] Corrected small spelling error

- css.html.markdown
> [css/en] Fixed small typo

- powershell.html.markdown
> [Powershell/en] Fixed a few spelling errors

- matlab.html.markdown
These are really helpful blogs with tips and tricks and write ups on common pitfalls when writing MATLAB code.
> Add new reading resources on MATLAB

- pt-br/jquery-pt.html.markdown
> [jQuery/pt-br] Add jQuery pt-br translation

- zh-cn/ruby-cn.html.markdown
`查询一个不存在地键将会返回nil` ->`查询一个不存在的键将会返回nil`
> [ruby/zh-cn]fix a typo

- pl-pl/vim-pl.html.markdown
Translated vim tutorial from English to Polish language.
> [vim/pl] Tutorial translation to Polish language

- pl-pl/vim-pl.html.markdown
> [vim/pl] fixed a typo

- html.html.markdown
> [html/en] small correction to english

- kdb+.html.markdown
> [kdb+/en] fixed a typo and a broken external link

- sk-sk/elixir.html.markdown
> Translation fixes.

- es-es/wolfram-es.html.markdown
> Translate to Spanish Wolfram.html.markdown

- kdb+.html.markdown
> [kdb+/en] minor typos and corrections

- python3.html.markdown
The result of division is always a float.
e.g. 
35/5 = 7.0
10 / 3  = 3.3333333333333335
10.0 / 3  = 3.3333333333333335
10 / 3.0  = 3.3333333333333335
> [python3/en] Edit python3 division

- .travis.yml
- Gemfile
- Rakefile
- tests/encoding.rb
- tests/yaml.rb
Build is passing on my branch, you can see the results here: https://travis-ci.org/samcv/learnxinyminutes-docs/
I'm not sure if @adambard would need to set this up or if somebody else can do this ( @vendethiel )?  Let me know your thoughts on this :)
> Add support for checking YAML validity using Travis CI

- vim.html.markdown
> [vim/en] useful tip for saving a buffer as sudo

- kdb+.html.markdown
> [kdb+/en] series of minor corrections and improvements - someone with a very sharp eye looked over it!

- fsharp.html.markdown
- [ X] Pull request title is prepended with `[language/lang-code]`
- [ X] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [ X] Yes, I have double-checked quotes and field names!
> [fsharp/en] Use "elif"

- php.html.markdown
- [v] Pull request title is prepended with `[language/lang-code]`
- [v] Pull request touches only one file (or a set of logically related files with similar changes made)
- [v] Content changes are aimed at *intermediate to experienced programmers* (this is a poor format for explaining fundamental programming concepts)
- [v] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [v] Yes, I have double-checked quotes and field names!
Add a missing semi-colon at Line 470 so now it is `variable("Separate", "Hello", "World"); // Separate || Hello | World |` 😸
> [php/en] Add a missing semi-colon

- typescript.html.markdown
> [typescript/en-us] Clarify function section in typescript

- python.html.markdown
The result should be {'a', 'b', 'c'} (not {'d', 'e', 'f'}).
> [Python/en] Fix comment in set comprehension example

- powershell.html.markdown
Only the first chunk of code was highlighted, done the rest of it.
> [powershell/en] Add syntax highlight

- dynamic-programming.html.markdown
> [dynamic-programming/en] Fix minor spacing typo

- python3.html.markdown
refer about boolean of empty tuple was missing.
https://docs.python.org/3.4/library/stdtypes.html#truth-value-testing
> [python3/en] Add empty tuple to "False if evaluated" list

- racket.html.markdown
> [racket/en] Expand list section

- php.html.markdown
> [php/en] Fix typo

- python3.html.markdown
`StopIterator` Exception: no such Exception.
It should be `StopIteration`.
> [python3/en] fixed "StopIterator", no such Exception

- zh-cn/less-cn.html.markdown
> [zh/cn] New translation: less-zh-cn

- less.html.markdown
> [en] typo in less: missing right parenthesis

- fr-fr/javascript-fr.html.markdown
> [Javascript/fr] Small mistake fix

- zh-cn/sass-cn.html.markdown
> [sass/zh-cn] new translation

- zh-cn/r-cn.html.markdown
> [r/zh-cn] fix a bug

- crystal.html.markdown
If this pull request is accepted, I can do the same in french.
> [crystal/en] It would be greate to add crystal language :)

- python.html.markdown
Actually nearly compliant, I ran `pep8 code.py --ignore=E402,E501,E712`
> [python/py-en] Made the file `pep8` compliant

- angularjs.html.markdown
> [angularjs/en] typo fix

- es-es/elixir-es.html.markdown
> [elixir/es] Add Spanish translation for Elixir

- fr-fr/crystal-fr.html.markdown
Add the crystal tutorial in french.
Ajout du tutoriel pour crystal en français.
> [crystal/fr] French language for crystal

- zh-cn/angularjs-cn.html.markdown
> [AngularJS/zh-cn] new translation

- elm.html.markdown
> [elm/en] Fixes #2584

- ko-kr/kotlin-kr.html.markdown
> [kotlin/ko-kr] Add korean translation for kotlin

- fr-fr/rust-fr.html.markdown
> [fr/rust] Update rust-fr.html.markdown

- ko-kr/bash-kr.html.markdown
> [bash/ko] Translate Bash to Korean

- html.html.markdown
> [html/en] a word was duplicated, I took it off.

- cs-cz/elm.html.markdown
Implements https://github.com/adambard/learnxinyminutes-docs/pull/2610 for Czech
---
> [elm/cs] Fixes #2584 for Czech

- julia.html.markdown
Update the broken Julia reference link.
> [Julia/en] edit broken link in julia.html.markdown

- perl.html.markdown
- [-] If you've changed any part of the YAML Frontmatter, make sure it is formatted according to [CONTRIBUTING.md](https://github.com/adambard/learnxinyminutes-docs/blob/master/CONTRIBUTING.markdown)
- [-] Yes, I have double-checked quotes and field names!
> [perl/en] some more examples of interacting with arrays and hashes

- rst.html.markdown
> [rst/en] Correcting English language

- pt-br/scala-pt.html.markdown
> [PT-BR/Scala] Translates Scala file to Brazilian Portuguese 

- python3.html.markdown
My first merge request in github, please tell me if I have done anything wrong.
I created that example since I really googled the value of True and False.
> [python3/en] Add examples to Bool operators with ints

- tcl.html.markdown
[tcl/en] Fixed fold example to return actual result instead of the word "res"
> Update tcl.html.markdown to fix the fold example

- no-nb/bash-no.html.markdown
removes two lines of english already translated in the two lines below
> [bash/no-nb] removes two lines of english

- pl-pl/haskell-pl.html.markdown
> [haskell/pl-pl] Translate Haskell docs from English to Polish

- typescript.html.markdown
> [typescript/en-us] Use ```ts for typescript syntax highlight

- python.html.markdown
Should add return to double_numbers function, without it next expression wiil fall with "TypeError: 'NoneType' object is not iterable" error
for value in double_numbers(range(1000000)):  # `test_non_generator`
print value
if value > 5:
break
> [python/en] Fix a bug

- pt-br/java-pt.html.markdown
[java/pt] Improving the consistency of a few sentences.
> [java/pt] Some translation fixes.

- java.html.markdown
Duplicate declarations break the build
> Remove duplicate int declarations

- haskell.html.markdown
> [haskell/en] some minor fixes

- asymptotic-notation.html.markdown
Improved definitions for Asymptotic Notations
> [Asymptotic Notations] Small modifications to definitions of functions

- perl.html.markdown
C-style for-loops aren't Perlish, and should not be encouraged.
Also I added a `map` version, because it's worth knowing it seeing as how it's the most efficient operator for lists/arrays.
> [perl/en] more perlish iterations on perl5

- kdb+.html.markdown
added personal kdb+ group, added github id for author
> [kdb+/en] added group information

- python.html.markdown
> [python/en] Python decorators example added

- csharp.html.markdown
> [csharp/en] Add exception filters, pragma directives

- standard-ml.html.markdown
> [standard-ml/en-en] Format fixing and some APIs

- logtalk.html.markdown
> [logtalk/en] Fixes and improvements to the Logtalk tutorial

- it-it/logtalk-it.html.markdown
> [logtalk/it-it] Add Italian translation of the Logtalk tutorial]

- bash.html.markdown
> [bash/en-us]Fix spelling

- c.html.markdown
Original link displays "This file has moved to process/coding-style.rst"
> [c/en] fix further reading url

- de-de/java-de.html.markdown
> [java/de] Add missing closing parenthesis

- julia.html.markdown
The Julia mailing list has been archived and discussion moved to the Discourse forums.
> [julia/en] Julia mailing list converted to forums
